### ISSUE TITLE
Swap interface - v2 tokens/pools

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#10]
On v2 pools, you need to check that you actually have enough balance to support the trade as we use more of the reserve due to liquidity amplification.

**Comment by Velua** [comment]
@yudilevi this is easy enough to do when just 1 hop, how might we approach this check in the case of 3 hops?

**Comment by yudilevi** [comment]
@Velua the easiest (but not as efficient) way to do it is to check the trade with different path - if it fails with the long path, test the balance vs. the liquidity and if there's enough liquidity, shorten the path by 2 and retry etc.

**Comment by ashachaf** [comment]
will be added to the getReturn function.
meaning, the response when testing the values will indicate if there is sufficient balance.
nothing to do on the frontend.
