### ISSUE TITLE
Toast notifications

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#1000]
@Velua I like the idea of a toast notification system. Maybe we can come up with a system that monitors pending transactions and errors as well.

About sentry, I just checked and sofar no error in that regard has been logged. Will keep an eye on it.

_Originally posted by @pingustar in https://github.com/bancorprotocol/webapp/issues/974#issuecomment-776539539_

**Comment by Velua** [comment]
@ashachaf We were wondering about your thoughts toast notifications for certain errors or events to convey to the user when we don't have a dedicated Modal going for it. 

If you're keen, can we get a design for it?

**Comment by pingustar** [comment]
@ashachaf if my memory isn't failing me, I believe we have mockups for this somewhere? Are those designs still around?

**Comment by ashachaf** [comment]
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=507%3A1911

**Comment by pingustar** [comment]
@ashachaf The Notifications system has two parts:

### Notification Alerts:
![image](https://user-images.githubusercontent.com/7262066/109123448-24959480-774a-11eb-9f67-bff75f2676e1.png)


### Notification History:
![image](https://user-images.githubusercontent.com/7262066/109123234-e26c5300-7749-11eb-9bad-01f06e85625b.png)

**A notification currently has the following data:**

```
interface INotificationView {
  id: number;
  status: ENotificationStatus;
  title: string;
  description: string;
  txHash?: string;
  timestamp: Date;
  showSeconds?: number;
  alertOnly?: boolean;
}
```

**we currently have 5 statuses:**

```
enum ENotificationStatus {
  success = "success",
  info = "info",
  warning = "warning",
  error = "error",
  pending = "pending"
}
```

**Comment by ashachaf** [comment]
@pingustar 
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2

**Comment by ashachaf** [comment]
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2844%3A2143

please note:
1. notification movement:
fly in - animate the notification as they fly in from the side (right side). on entry, allow 2seconds fade in.
keep notification visible for 7 seconds
fly out - fade the notification out for 3 seconds and in the last second close it to the right (move outside of the view).

2. menu item movemement:
appear - allow opening from the icon in a top to bottom movement (reference the settings and right side menu icon)
close - same as the settings and right menu

3. menu item deletion:
when clicking the 'x' on a specific notification, fade it out of view (moving to the right) for 1 second.
clear all items - fade all together in the same format as a single notification 'x'
