### ISSUE TITLE
swap token - auc token bug 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1005]
**Describe the bug**
### showing liquidity for empty pool
![image](https://user-images.githubusercontent.com/40430285/107647636-0a58b280-6c84-11eb-91cf-eb42c7606fa7.png)

API response:
"pool_dlt_id":"0x164A1229F4826C9dd70Ee3D9f4f3d7B68a172153","name":"AUC/BNT","decimals":18,"liquidity":{"usd":"91230.692969"},"volume_24h":{"usd":"0"},"fees_24h":{"usd":"0"},"fee":"1000","supply":"108912.489530614453884081","version":9,"converter_dlt_id":"0x3B0116363e435D9E4EF24ecA6282a21b7CC662df"},{"reserves":[{"address":"0x1F573D6Fb3F13d689FF844B4cE37794d79a7FF1C","weight":"500000","balance":"4484.935796331895916223"},{"address":"0xc944E90C64B2c07662A292be6244BDf05Cda44a7","weight":"500000","balance":"8280.715307549089961795"}]

pool on the blockchain is empty.

**check API to see why the pool data return balances**

### EDG token decimals:
API: 
{"symbol":"EDG","dlt_id":"0x08711D3B02C8758F2FB3ab4e80228418a7F8e39c","decimals":18,"liquidity":{"usd":"0.000397"},"rate":{"usd":"397175460754095.546000"},"rate_24h_ago":{"usd":"371180213824927.257000"}}

etherscan: edg token has 0 decimals

**Comment by yudilevi** [comment]
EDG request -
https://api-v2.bancor.network/tokens?dlt_id=0x08711D3B02C8758F2FB3ab4e80228418a7F8e39c&dlt_type=ethereum

returns this -
{"data":[{"dlt_type":"ethereum","dlt_id":"0x08711D3B02C8758F2FB3ab4e80228418a7F8e39c","symbol":"EDG","name":"Edgeless","decimals":0,"liquidity":{"usd":"0.000478"},"price":{"usd":"478020013863734.010000"},"price_24h_ago":{"usd":"462196820080762.008000"},"volume_24h":{"usd":"0","base":"0"}}]}

0 decimals.

How come we're seeing different results?

**Comment by Velua** [comment]
We're now seeing 0 decimals coming from EDG.

**Comment by Velua** [comment]
@ashachaf are we tackling the other API issue in #1023 then?

**Comment by yudilevi** [comment]
The other API issue (EDG token decimals) was already fixed.

**Comment by ashachaf** [comment]
i am closing this issue as both items have been fixed.
