### ISSUE TITLE
share of pool error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#101]
when adding liquidity:
1. share of pool only indicate the "new" share of pool. if you already have pool tokens, this is not visible.
expected: if the walleet already hold pool tokens, show the share of the pool tokens it holds. when indicating the amount to stake, calculate the new pool token amount and show the share including all pool tokens (ones the wallet already owns + new they plan to stake).

2. calculation seems to be incorrect.
when i try to stake, the expeected share of the pool indication is much lower than what it should be.
ropsten:
staking 285 link to the pool indicate i will own 0.0316% share of the pool.
![image](https://user-images.githubusercontent.com/40430285/90423774-bcdcfd80-e0c5-11ea-9373-3362755d77d9.png)

however, looking on etherscan, 285 link will make me double the liquidity and make me hold 50% of the pool tokens' supply
![image](https://user-images.githubusercontent.com/40430285/90423634-7c7d7f80-e0c5-11ea-87c2-c61197c6e35a.png)
https://ropsten.etherscan.io/token/0xbaB16b79B4b4FD0eF300A26De0C25A5caa474073#balances

**Comment by Velua** [comment]
I've recognised a bug where the UI wasn't converting dec to a percent form. 

However I don't think that's the whole picture, atm the pecentages are being worked off the stakedReserve balance, is that right? Or should it be based off the reserve balance itself of the converter or...? @ashachaf  @yudilevi

**Comment by yudilevi** [comment]
The cost is based off the ratio between the staked balance and the pool token supply.
The share is based off how much you're gonna put as a share from the staked balance (including the amount you put in).

@ashachaf correct me f I'm wrong.

**Comment by ashachaf** [comment]
your share is your pool token balance (existing balance + any new indicated amount) / (total pool supply + any new indicated amount).

**Comment by Velua** [comment]
Wrote the code for V1 and will push shortly, with v2 it's currently 

    any new indicated amount / same staked reserve balance

Do we want 

    (existing user pool token balance + pool token return of any new indicated amount) / pool token supply

 ?

**Comment by Velua** [comment]
@ashachaf

**Comment by ashachaf** [comment]
yes

**Comment by Velua** [comment]
Closing as we're not supporting this for V2 pools now.
