### ISSUE TITLE
Automatic git merging from GitHub

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#1019]
We're seeing GitHub PR's suggesting to merge when it should not be necessary, please investigate.

**Comment by Velua** [comment]
@Ran73Cohen looking at https://github.com/bancorprotocol/webapp/pull/1018 which is recently branched from ```master``` I don't see the merge button.

**Comment by Ran73Cohen** [comment]
Settings changed in the repository
Number 7 [here](https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule)
