### ISSUE TITLE
Abnormally high gas fee charged and error when trying to supply BNT

### ISSUE THREAD

**Issue by Gitsomelearnsome** [bancorprotocol/webapp#102]
Hello,

Tried to supply to the BNT/LINK v2 pool. There does seem to be room for additional liquidity(normally it says the cap is reached). 
However, after enabling BNT and putting in the second tx to supply BNT to the pool I am getting the following error and am being charged 11M in gas limit costs:
![image](https://user-images.githubusercontent.com/40437233/90428379-2f4cde00-e0c4-11ea-8584-ad85a9cf3fb9.png)

Which i've naturally rejected. 

I tried different amounts (smaller amounts) in case it had anything to do with the cap. All show the same issue. 

I am using the latest version of metamask (no hardware wallet) and Brave browser. 

Oh and another minor unrelated issue. Swap.bancor.network does not seem to load in my chrome browser.
I tried clearing my cookies and cache, but still doesn't load. In Brave it only loads after putting down my shields. 

Please let me know if you need any additional details. 

Thanks in advance.

**Comment by Velua** [comment]
From @ashachaf 
> bnt staked is way below the limit for this pool now.
153k while the limit is 238k
i've tried adding 10 bnt of liquidity and got  to the same result

**Comment by Velua** [comment]
@yudilevi So is it expected for Web3 to estimate absurd gas amounts when the contract is expected to throw?

**Comment by Velua** [comment]
Thanks @Gitsomelearnsome we've recognised your Brave issue in #97 

I'd love to see exactly what's going to Web3 when this transaction is being created, at the moment the app will log this in the console. 

In Brave if you right click and press Inspect or hit CTRL + SHIFT + I and click on ```Console``` and then enter in the filter ```received```  it should come up after you've triggered a metamask tx. 

If you could take a screen shot just like this one below that would be great. 

![Screenshot at 2020-08-18 10:44:25](https://user-images.githubusercontent.com/8017434/90457876-1a159500-e140-11ea-9ed7-4919cac3ba6b.png)

You may need to press the little dropdown icon > to make it expand to show more information,

**Comment by Gitsomelearnsome** [comment]
This is what it says:

![image](https://user-images.githubusercontent.com/40437233/90475711-47eedf80-e128-11ea-8204-58e897c71b7e.png)


Error still persistent..

**Comment by Velua** [comment]
Thanks @Gitsomelearnsome I've recognised a fault on my end and pushed an update. Can you try again now?

**Comment by Velua** [comment]
Lifting this issue of it's priority status, keeping open as I need to further polish the formula 

    (pool token supply / staked balance ) * amountEntering

**Comment by Gitsomelearnsome** [comment]
Works fine now, thanks!

**Comment by ashachaf** [comment]
@Velua 
did you update the process to use the global variable?

**Comment by Velua** [comment]
@ashachaf do you mean slippage tolerance?

**Comment by Velua** [comment]
If so then yes.
