### ISSUE TITLE
Ropsten ETH to Link

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#103]
@ashachaf has experienced an issue trading between ETH to Link on Ropsten

![image_2020-08-17_20-33-57](https://user-images.githubusercontent.com/8017434/90455176-bd62ac00-e138-11ea-8249-129b4822e7b2.png)

**Comment by Velua** [comment]
@yudilevi @ashachaf 

Should I hit up Etherscan on Ropsten at ```0xbe76bC6d0fC627EDE9B4B96A674AE6655919803f``` which is the network contract the UI is currently using.

### getReturnByPath
    ["0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE", "0xA220a3E30Af94E066e5A31fCE4aB03d08634B840", "0x98474564A00d15989F16BFB7c162c782b0e2b336", "0x51ccc0fd09f7dcD8bE1c10ac7Aa80d68476b2766", "0x20fE562d797A42Dcb3399062AE9546cd06f63280"]

with amount ```10000000000000000```

returns nothing... So I'm assuming an error. 
![Screenshot at 2020-08-18 10:01:27](https://user-images.githubusercontent.com/8017434/90455608-d586fb00-e139-11ea-9d8e-f2324cea30bc.png)

I get the same experience when using 

    ["0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE", "0xA220a3E30Af94E066e5A31fCE4aB03d08634B840", "0x98474564A00d15989F16BFB7c162c782b0e2b336"]

**However** when I use a path that doesn't include the ```0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE```

    ["0x20fE562d797A42Dcb3399062AE9546cd06f63280", "0x51ccc0fd09f7dcD8bE1c10ac7Aa80d68476b2766", "0x98474564A00d15989F16BFB7c162c782b0e2b336", "0xE5350d243f612aA23F9D296501ae078D6849DE7f", "0xBde8bB00A7eF67007A96945B3a3621177B615C44"]

it works fine. Can we confirm the contract I'm using ```0xbe76bC6d0fC627EDE9B4B96A674AE6655919803f``` is correct and ```0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE``` is working?

**Comment by yudilevi** [comment]
There's also an empty ETH / BNT v2 pool on ropsten, maybe the network generates a path that includes that one which obviously wouldn't work

**Comment by Velua** [comment]
To review path generation, this is currently done client side.

**Comment by Velua** [comment]
Fixed.
