### ISSUE TITLE
Alchemy whitelisting for firebase preview links

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#1047]
Currently the firebase preview links do not seem to load the vote section due to the requests being blocked by alchemy.

We need to check if we can add some sort of dynamic whitelisting that allows us to use the preview links with full functionality

**Comment by ashachaf** [comment]
i will add a new api with no domain restriction for our tests.

**Comment by ashachaf** [comment]
https://dashboard.alchemyapi.io/apps/d2irho67oza5xd4h

**Comment by pingustar** [comment]
how do we add this? I only found the option for changing the alchemy api token based on mainnet or ropsten.

Can we change the key based on host url and have it work with both ropsten and mainnet @Velua @ashachaf ?

**Comment by pingustar** [comment]
> i have added the domain to our alchemy key.
> please test to see if this works now

`unable to load vote
Error: Returned error: Origin "bancor-v2-beta--pr1081-feature-unlimitedapp-cs32lqjh.web.app" is not on whitelist.`

**Comment by Velua** [comment]
Is there a wildcard we can use? So *.web.app or whatever domain we're deploying too?

**Comment by pingustar** [comment]
> Is there a wildcard we can use? So *.web.app or whatever domain we're deploying too?

yeah that's what we did
