### ISSUE TITLE
support the option for unlimited approve

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1052]
**Is your feature request related to a problem? Please describe.**
as a user, i would like to have the option to select between specific approve for the amount of the transaction or unlimited approve. selecting unlimited approve will result in approving the specific token and contract once for all future transaction on this token. this will result in 2 main benefits for the user:
1. cheaper transactions as you do not need to sign the approve on every transaction
2. faster transactions as you execute the transaction you wish immediately without waiting for the approve to be confirmed (can take few min at times)

**Describe the solution you'd like**
on the confirmation popup before we trigger the web3 transaction call, we will include the option to select specific approve or unlimited approve.
once user select the option, we set the approve amount based on that.

(seems that unlimited amount is typically set as `(2**256 - 1) / 10**18` in the approve amount)

mockups 
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2606%3A5275

which flows should we update/add the popups:
1. add single side liquidity
2. add dual side liquidity
3. limit order (part of a different story)
4. swap
5. withdraw pool token liquidity
6. withdraw protected position liquidity

**Comment by Velua** [comment]
I've added the logic for this to work behind the scenes, Jan will come through soon and wire it up with the View layer.
