### ISSUE TITLE
stake liquidity into a pool that disable liquidity

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1053]
**Is your feature request related to a problem? Please describe.**
when we identify a pool with disable liquidity on one reserve, we suggest the user to stake that disabled token when there is no more space in the pool.

![image](https://user-images.githubusercontent.com/40430285/108378606-d47c7680-720d-11eb-8f9d-a33fed022c71.png)

**Describe the solution you'd like**
when we identify such issue we should update the error message.

IF you wish to stake liquidity into a pool with the token that is enable AND space available is less than 1 unit,
display only space available (remove "BNT NEEDED TO OPEN UP VBNT SPACE 0.682983 BNT" part)
reference to what to remove
![image](https://user-images.githubusercontent.com/40430285/108380109-3689ab80-720f-11eb-92c2-0cda413dab45.png)

IF the input amount is greater than space available, 
current error: vBNT limit reached. Additional BNT liquidity should be staked to allow for vBNT single-sided staking.
update error message: {token} limit reached. Please wait until some space opens up.
(reference to the error we need to replace)
![image](https://user-images.githubusercontent.com/40430285/108379923-0cd08480-720f-11eb-8bef-2029e5affab6.png)

**Comment by Ran73Cohen** [comment]
@ashachaf 
You mean dont display the  "token needed to open up space" only when he is disabled (not sure how "space available is less than 1 unit" matters if I cant stake the other token)
and on the second we need to display the "additional bnt liq should be staked..." message when it is not disabled
and show the new message when other token is disabled

**Comment by ashachaf** [comment]
please remove the "space available" indication on this case
IF the selected token is disable from adding more liquidity, remove the "space available" box.


![image](https://user-images.githubusercontent.com/40430285/108841800-ff394700-75e0-11eb-94f1-3b67e642a86f.png)
![image](https://user-images.githubusercontent.com/40430285/108841889-2132c980-75e1-11eb-9c3b-3595177e3714.png)
