### ISSUE TITLE
auto refresh swap rates

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1054]
**Is your feature request related to a problem? Please describe.**
as a user, when i open the swap interface and check token price, i would like it to keep refreshing and show most recent rates.

**Describe the solution you'd like**
refresh the rate and re-pull that information from the blockchain every 10 seconds.
- keep doing it as long as the user is active on the page

how to view this?
go to swap -> select 2 tokens -> enter an amount on the "from token"
expected: token rate and "to amount" to refresh every 10 sec with more recent rates

when we refresh, we want to show an indication to the user.
please use the same circular animation used on "space available" check
if possible, make sure that this animation is shown for 1 full second. anything faster than that looks like a mistake/glitch.
![image](https://user-images.githubusercontent.com/40430285/108975063-c2c42480-768e-11eb-93cf-78b798701664.png)

**Comment by ashachaf** [comment]
@pingustar

**Comment by ashachaf** [comment]
@Velua added slippage task on https://github.com/bancorprotocol/webapp/issues/1207

**Comment by ashachaf** [comment]
@pingustar what is the status of this?

**Comment by pingustar** [comment]
@ashachaf getting started on this now.

> @pingustar what is the status of this?
