### ISSUE TITLE
adding multiplier indication on the protection table

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1055]
**Is your feature request related to a problem? Please describe.**
as a user, i would like to have visibility into my rewards multiplier.
rewards multiplier is only available on the pool+reserve level, so we should display it next to the rewards in the protected table.

**Describe the solution you'd like**
in order to identify the multiplier we would need to check this function for each 
1. user wallet
2. pool address
3. reserve address
combination.
we currently go thru this process to pull the rewards data, so it is the same flow but calling a different function.

function rewardsMultiplier(address provider, IDSToken poolToken, IERC20Token reserveToken) external view returns (uint32) {
        ProviderRewards memory providerRewards = providerRewards(provider, poolToken, reserveToken);
        PoolProgram memory program = poolProgram(poolToken);
        return rewardsMultiplier(provider, providerRewards.effectiveStakingTime, program);
    }

mockups:
TBD

**Comment by Ran73Cohen** [comment]
Merged
