### ISSUE TITLE
0% APR for some protected positions

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#1072]
**Describe the bug**
@ashachaf has brought to our attention that some tokens show 0% APR for protected positions.

**Screenshots**
![telegram-cloud-photo-size-4-5882237903109731597-y](https://user-images.githubusercontent.com/7262066/108695584-bf029780-7500-11eb-9c91-6c319711a067.jpg)

![telegram-cloud-photo-size-4-5882237903109731598-y](https://user-images.githubusercontent.com/7262066/108695664-d80b4880-7500-11eb-854b-6eeab828e0c5.jpg)

**Comment by ashachaf** [comment]
seems that following a pool upgrade, the APR shows 0% as the new converter doesnt have any historical data.
