### ISSUE TITLE
Darkmode Button-Designs not distinguishable between active and disabled

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#108]
@katyarozenfeld 

looking at the dark mode button when disabled on the swap view and the active buttons on data table view, I feel like those gray colors are to close together. 

What do you think?

![Screenshot 2020-08-19 at 09 09 25](https://user-images.githubusercontent.com/7262066/90603591-ccf6f900-e1fb-11ea-8094-670494419fd1.png)
![Screenshot 2020-08-19 at 09 09 32](https://user-images.githubusercontent.com/7262066/90603599-ce282600-e1fb-11ea-8bf0-880063953710.png)

**Comment by katyarozenfeld** [comment]
Yes, I completely agree - the color of the text should be different. Please check Zeplin, I just updated disabled button
https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f1d2dbfaf220c37fb5fa2b1/

**Comment by Velua** [comment]
@pingustar Same deal, confirm this remains a thing and if able assign to @Ran73Cohen
