### ISSUE TITLE
swap indication for pools with no liquidity

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1099]
**Is your feature request related to a problem? Please describe.**
as a user, there are cases where tokens are still visible but they dont have any liquidity so conversion cannot be performed. 

example:
AUC token
![image](https://user-images.githubusercontent.com/40430285/109156009-fd09f080-7778-11eb-8488-63292999fadb.png)

in such cases, check and do the following:
IF reserve balance = 0, do not display the token on the swap drop down option.
(this should not return the token in this case)
![image](https://user-images.githubusercontent.com/40430285/109156662-c5e80f00-7779-11eb-81c0-501d125d00a0.png)

on the data table, disable the swap button
![image](https://user-images.githubusercontent.com/40430285/109156568-ab159a80-7779-11eb-85f3-fc037df63a50.png)

**Comment by ashachaf** [comment]
please also disable on the data->token tab
![image](https://user-images.githubusercontent.com/40430285/109184390-a069fe00-7797-11eb-89ba-4ec767c02ea6.png)

**Comment by Velua** [comment]
My fault @Ran73Cohen for some reason I didn't see you assigned to this.
