### ISSUE TITLE
Add max slippage option in the settings

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#1103]
There's a problem with users executing transactions with huge slippage without noticing and losing lots of funds in the process.
In order to circumvent it, we'd like to add a new setting - "Max Slippage", default at 5%.
When the user attempts to execute such a transaction, the app should prevent it and show a popup instead that says:
"This swap slippage will exceed the maximum slippage set. To execute it anyway, set a higher maximum slippage in the app settings."

**Comment by Velua** [comment]
Discussed in meeting with Asaf, @ashachaf to engage you on strategy with this one, placing on hold for now.

**Comment by yudilevi** [comment]
Ok, Asaf is working on a new design for this. Let's keep this one here and update it with the new design once it's ready.

**Comment by ashachaf** [comment]
as a user, when slippage increase i would like to be aware of this.
currently, when slippage is > 3%, we color the slippage section in red.
![image](https://user-images.githubusercontent.com/40430285/111168808-15687080-85ab-11eb-878d-37d5bca18693.png)


mockup:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=3268%3A0

update the flow in the following way:
0-3% slippage, do nothing.
3%-5% slippage, color the slippage value red (as we do today)
new warning levels:
5%-10% slippage, update the CTA text 
10%+ slippage, update the CTA text+color
