### ISSUE TITLE
limit orders

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1105]
**Is your feature request related to a problem? Please describe.**
as a user, i would like to have the option to set limit orders which will be fulfilled when the price/market is right.

https://docs.google.com/document/d/1ns_kHM2cb6ytOY-eTcP4qKVVwzUWZ052rjNvQ5o6-q0/edit#

**Comment by Velua** [comment]
@Ran73Cohen in commit fad5f7ca36f6d0ca06964e8345f6e178136de1cf on ```feature/rxOptimistic``` I made a change in ```SwapAction.vue``` which is an example for creating an order and accesses the getter for the orders. I've also created ```vxm.ethBancor.cancelOrder``` which just needs the ID of the order.

**Comment by pingustar** [comment]
@Velua I have added the table to feature/rxOptimistic. Not done yet, but made good progress.

@Ran73Cohen I have split the market and limit orders in separate components. We should clean them up and see what we actually need for each component. Probably also a good idea to create a route for each. limit order modal is in a good state and we can hook it up to the logic.

Lets discuss further on our call tomorrow. We have so many branches floating around here, I hope this doesnt become a nightmare to merge at the end...
