### ISSUE TITLE
Analytics app shouldn't show the "connect your wallet" button

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#111]
Since it's a read only app.

**Comment by Velua** [comment]
Is the Analytics app the data page where we are listing the liquidity depths? 

It's just another page in the existing app.

**Comment by yudilevi** [comment]
Yeah but it's going to be on a different subdomain and it should be treated as a separate app even though it's the same one technically.

**Comment by Velua** [comment]
So there's going to be a subdomain which defaults to this page? Will it include swap functionality? Or should that be disabled? @yudilevi

**Comment by pingustar** [comment]
@Velua because we have multiple data pages now (details pages for pool and token), I changed the way we determine if showLogin is true/false:

`get showLogin() {
    return !this.$route.fullPath.includes("data");
  }`

closing this for now. Please reopen if subdomain is happening @yudilevi

**Comment by yudilevi** [comment]
it's not 100% clear if we're gonna use the data subdomain from day 1 or shortly after but it's still the plan to have it.
