### ISSUE TITLE
data table sort bug

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1130]
**Describe the bug**
when trying to sort the data table based on specific column, the data jumps and change the view

**To Reproduce**
1. Go to data table
2. Click on the APR column to sort the view descending (highest APR first)
3. wait 5-10 seconds

**Comment by Velua** [comment]
Still yet to tackle.

**Comment by Ran73Cohen** [comment]
This bug isn't happening anymore but in #1295 there is a different bug related to sorting.
