### ISSUE TITLE
multiple claim bnt transactions

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1138]
**Describe the bug**
as a user, if i have unclaimed bnt (as a result from withdrawing protected positions), when i claim it, i would only need to trigger a single transaction.

however, it seems that we trigger multiple transactions.
 
**To Reproduce**
1. Go to protection
2. withdraw a protected bnt position in several parts in order to have multiple locked bnts
3. wait for them to finish lock time
4. click claim
expected to see 1 metamask transaction.
actual, we trigger multiple transactions (while the first one i sign actually claims all my bnt balance. meaning, the others are just waisting my money)

we should make sure that when we trigger a claim transaction we set the start as 1 and the end as a very large number in order to grab all required claims.

**Comment by Velua** [comment]
@yudilevi 

> we should make sure that when we trigger a claim transaction we set the start as 1 and the end as a very large number in order to grab all required claims.

Can we get away with that? I thought there was a limit on how far we can expand, at the moment I'm just chunking all claims in groups of 5 then on ```claimBalance``` claiming from the first index then going +50 for the second param. 

@ashachaf Multiple transactions was done on purpose, as I didn't believe we could get away with doing them all in one hit while developing the feature.

**Comment by yudilevi** [comment]
@Velua I'm pretty sure it can work for a very large number of tx, did you see any issue?

**Comment by Velua** [comment]
Not that I've seen just thought there was one. 

I'll just sort all balances by order then and go from the lowest index to the highest.

**Comment by Velua** [comment]
Following discussion with Yudi we're now just gonna hard code indexes from 0 to 1,000.
