### ISSUE TITLE
Once a swap is in progress display this feedback in the UI

### ISSUE THREAD

**Issue by RussellDias** [bancorprotocol/webapp#1139]
**Is your feature request related to a problem? Please describe.**
When you execute a Swap, you see a modal redirecting you to Etherscan to see your transaction progress. 

**Describe the solution you'd like**
Similar to Uniswap it'd be very helpful to have feedback that your swap is in progress and then additional feedback when it's been confirmed.

**Comment by ashachaf** [comment]
we are about to release something to address this specific request.
task #1000
