### ISSUE TITLE
Remove liquidity - output/exit fee numbers remain static

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#114]
Report from user:

"there might be some bug in the v2 pool 'remove liquidity' screen. the exit fee and output fields are blank, unless i press the '25%' in amount, at which point it shows up, but the number then doesn't change when you change the amount to something else."

It might be a latency issue but worth checking.

**Comment by pingustar** [comment]
I have fixed this and added a loading icon to the output while calculating return. 

please review on staging.
