### ISSUE TITLE
Swap - "current rate" doesn't change when clicking the 2 arrows (switch)

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#116]
From the user:

I went to swap.bancor.network from safari on my iPad, selected PEG token, and then clicked on the double-arrow swap icon to switch them:

![image](https://user-images.githubusercontent.com/1134236/90914664-ef009f00-e3e6-11ea-9c34-06270b5c27a3.png)

**Comment by pingustar** [comment]
fixed in commit: https://github.com/bancorprotocol/webapp/commit/da207b058204880568dfd4ae6304e5f771ed7e05
