### ISSUE TITLE
Unlimited Approval - Flow update

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#1164]
#1081 EPIC 

from @ashachaf 
```
7. add dual side liquidity
  approve trigger 2 approve transactions (one for each reserve)
  there is no confirm add liquidity popup
8. add single side liquidity
  there is no "add liquidity" popup if i see the approve popup first
```

from @pingustar 
```
@Velua can you take a look at 7. and 8. please. Seems to be the case for most if not all confirm prompts. The confirm prompt only shows up when the amount is already approved. If the approve screen is first, then right after approve it goes straight to metamask.

Correct flow:
approved? -> yes -> confirm modal -> metamask
approved? -> no -> approve modal -> metamask -> confirm modal -> metamask
```

**Comment by pingustar** [comment]
handed over to @Velua

**Comment by Velua** [comment]
@pingustar try out the ```feature/rxOptimistic``` branch now.

**Comment by pingustar** [comment]
> @pingustar try out the `feature/rxOptimistic` branch now.

lets discuss on monday. Not sure I understand what I am looking at.

**Comment by Velua** [comment]
This is where onPrompt should await for a new confirmation after approvals.

**Comment by pingustar** [comment]
@Velua couple things I noticed on `feature/rxOptimistic` branch. 

- The confirm button needs to be pressed twice if the amount has been pre-approved.
- Not sure if thats intended but I thought I share it: When I approve limited amount, eg 4 XXX. I get asked to approve again for a new swap with same amount of 4 XXX.
- swap view seems to have merge issue:
![image](https://user-images.githubusercontent.com/7262066/111187624-75174980-85b4-11eb-971d-3d7bbaa314b5.png)

**Comment by Velua** [comment]
Solved the merge issue, still reviewing the approval process.
