### ISSUE TITLE
swap confirmation popup - vbnt case

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1175]
**Is your feature request related to a problem? Please describe.**
when vBNT is one of the tokens the user is swapping (from or to tokens), we would like to update the summary popup and include a link to the blog post explaining more about vBNT.

**Describe the solution you'd like**
update the confirmation popup with additional text link below the CTA.
only IF vBNT is one of the traded tokens.

text link: Read more about vBNT
clicking the link would open this: https://blog.bancor.network/using-bancor-vortex-46974a1c14f9

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2606%3A5275
![image](https://user-images.githubusercontent.com/40430285/110607073-823acf80-8193-11eb-861e-1ca3c8296698.png)

**Comment by pingustar** [comment]
@ashachaf I had to place the text above the CTA button. Hope thats okay. Placing it below is possible but will require a custom slot for the modal component.

Let me know if this works or if I should place it at the bottom.
