### ISSUE TITLE
protection table - missing protected positions

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1182]
sometimes, when loading/refreshing the protection page, data is missing.
this time, it indicates that i have no positions and console has lots of errors

![image](https://user-images.githubusercontent.com/40430285/110780301-39574980-826d-11eb-8ce0-5627405df156.png)

**Comment by ashachaf** [comment]
@Velua @pingustar

**Comment by pingustar** [comment]
@ashachaf I cannot reproduce. Any additional steps required to reproduce this? How often does this happen?
