### ISSUE TITLE
insufficient balance when removing liquidity error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#119]
when a user is trying to remove liquidity from a pool which "current balance" of the reserve is smaller than the required remove liquidity amount, the interface doesnt indicate this to the user.
process:
consider the following settings: 
user owns 1000 XYZ pool tokens
current balance of the XYZ reserve is smaller than (1000 pool tokens * staked balance / XYZ pool token supply) 
flow:
got to swap.bancor.network
select pool
remove liquidity from XYZ pool
indicate you would like to liquidate 1000 XYZ pool tokens
expected:
- identify api error and display relevant error message
actual:
- allow the user to process and receive metamask error

https://streamable.com/bgor7o

screens:
https://zpl.io/bWOQO7x

**Comment by Velua** [comment]
@pingustar I've fixed this in commit c905c4536d1bcf31b121478b636d121761b196e2 can we make sure that all of these types of vuex methods are handled when they throw, could even be due to a network error.

**Comment by pingustar** [comment]
@Velua I'll make sure, yes. In this specific case the code was written by you.
