### ISSUE TITLE
data table not showing rewards

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1193]
**Describe the bug**
protection indication took very long to load.
rewards took even longer.
no special errors in console.

![image](https://user-images.githubusercontent.com/40430285/111061833-e8826380-84ad-11eb-8145-39ecdd8f4209.png)

**Comment by pingustar** [comment]
seems to be back to normal. As this data comes from alchemy it was probably a temporary slow response or timeout.

Please reopen if issue is persistent.
