### ISSUE TITLE
instrument.js:109 web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1196]
**Describe the bug**
when loading the site, there are many warning on this:
instrument.js:109 web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.

**reproduce**
go to protected tab

**Comment by Ran73Cohen** [comment]
Web3 is displaying this message, nothing we can do
See [this](https://github.com/ChainSafe/web3.js/issues/3898)
