### ISSUE TITLE
inpage.js:1 MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead. For more information, see: https://eips.ethereum.org/EIPS/eip-1193#disconnect

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1197]
inpage.js:1 MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#disconnect

**Comment by Ran73Cohen** [comment]
Web3 is displaying this message, nothing we can do
See [this](https://github.com/ChainSafe/web3.js/issues/3699)
