### ISSUE TITLE
Display APR data (iframe)

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#12]
Asaf Shachaf, [1. Aug 2020 at 13:47:30]:
...here is some data from dune for APR.
for the "data" page, we can use these queries and show the information in iframe.
https://explore.duneanalytics.com/dashboard/bancor-v2-data

for example:
APR iframe (current APR d)

`<iframe src="https://explore.duneanalytics.com/embed/query/7246/visualization/14373?api_key=0JOEgS4xyp8QdpQrPMWMxxNUDvcESjosA9tQ7fc7" width="720" height="391"></iframe>`

APR graph (once you click to view the APR data)
`<iframe src="https://explore.duneanalytics.com/embed/query/7244/visualization/14367?api_key=ArpRf26MhZgYpjJOU1fMk3pg8HkRjMcqVoIPDvAz" width="720" height="391"></iframe>`

**Comment by pingustar** [comment]
@asaf 

how should this be handled? I assume the apr number should be displayed for each token in a separate column of the table in the data section?

the iframes are to big to put in each row of the table. What should I display as a button to open a window that presents the iframe?

and how would I get each iframe for all the tokens?

**Comment by Velua** [comment]
@ashachaf My current understanding is that we require some more links?

**Comment by Velua** [comment]
@ashachaf closing till we get some more direction on this.

**Comment by ashachaf** [comment]
we are working with blocklytics to have bancor v2 subgraph ready.
an APR query should be there soon.
https://thegraph.com/explorer/subgraph/blocklytics/bancor-v2?query=Converters

**Comment by Velua** [comment]
@ashachaf Is this now going to be replaced with the new GraphQL endpoint we have?

**Comment by yudilevi** [comment]
@Velua that's the plan

**Comment by Velua** [comment]
Alright @yudilevi will close this and continue work towards the new graph.
