### ISSUE TITLE
calculating spot price for slippage calculation

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1207]
**Is your feature request related to a problem? Please describe.**
as a user, i would like to know the exact slippage based on the difference between spot rate and the rate i receive based on the input value.

**Describe the solution you'd like**
when a user interacts with the widget and set up a swap, we identify the pools involved in the path and:
1. pull the reserve balance from the blockchain
2. calculates the spot rate in the pools
3. pull new data from the blockchain every 15 seconds 

example:
Suppose we have two pools - AAABNT and BNTCCC
We want the spot price 1XXX = how many YYY
calculation:
AAABNT.balanceOf(BNT) / AAABNT.balanceOf(AAA) *
    BNTCCC.balanceOf(CCC) / BNTCCC.balanceOf(BNT)

case of 3 hops:
We have 3 pools:
- AAABBB
- BBBCCC
- CCCDDD

Then 1 AAA =
    AAABBB.balanceOf(BBB) / AAABBB.balanceOf(AAA) *
    BBBCCC.balanceOf(CCC) / BBBCCC.balanceOf(BBB) *
    CCCDDD.balanceOf(DDD) / CCCDDD.balanceOf(CCC)
DDD

**Comment by ashachaf** [comment]
connected to #905.

few edge cases:
very small numbers - when the user inputs a number that is smaller than the allowed decimals (meaning it is basically 0). for example, USDT supports 6 decimals, so 0.0000001 is basically smaller than the smallest unit allowed.
disable the input field based on the selected token decimals. when switching tokens, trim any input value based on decimals.
current: 
![image](https://user-images.githubusercontent.com/40430285/111446799-714f0880-8715-11eb-99fb-33820c5b59b3.png)

**Comment by Velua** [comment]
@pingustar Reckon we should be passing a precision prop down to ```token-input-field``` or whatever to limit the number entry?

**Comment by pingustar** [comment]
> @pingustar Reckon we should be passing a precision prop down to `token-input-field` or whatever to limit the number entry?

yeah sounds good. @Velua can you add the precision to `ViewReserve` please. I can take it from there then.

**Comment by ashachaf** [comment]
@Velua
