### ISSUE TITLE
Remove or change the top warning message "This interface is in beta. Use it at your own risk."

### ISSUE THREAD

**Issue by DavidMillerCL** [bancorprotocol/webapp#1212]
**Is your feature request related to a problem? Please describe.**
Not a problem directly related. However it is discouraging people onboarding Bancor.
Several people have publicly acknowledge in twitter that they are scared of using bancor because it says it's in beta.

**Describe the solution you'd like**
Contracts are audited and so will be so the beta warning can be misleading. We should warn about the UI is constantly changing instead. Proposed solution would be to:

1) Completely remove the banner which is very predominant in the top of the site (and blue color makes it even more visible).
or
2) Move it to the bottom of the page without such blue background + maybe modify the text to something like:

_"This Interface is subject to real-time changes. If you encounter any data not showing as expecting try force reloading the page with Ctrl+F5"_

![photo_2021-03-17_12-24-04](https://user-images.githubusercontent.com/63974332/111460079-d4dc3480-871b-11eb-9b54-d1eb2ee28ad5.jpg)

**Comment by ashachaf** [comment]
on mainnet - remove the banner.
