### ISSUE TITLE
Colour coding check

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#122]
![Screenshot at 2020-08-26 07:41:17](https://user-images.githubusercontent.com/8017434/91230846-9d05a380-e76f-11ea-8dcb-f0f2239bdf6b.png)

This message is displayed to the user as a warning rather than an error, traditionally errors are red and warnings might be a orange/yellow colour, is this worth changing?

**Comment by katyarozenfeld** [comment]
@Velua Thanks for this comment, I completely agree. Let's please use F6AB30 for the warning text and FFF8ED for the warning message background. Zeplin is updated.

**Comment by pingustar** [comment]
implemented. And ready for review on staging.
