### ISSUE TITLE
deposit and withdraw for ETH-WETH 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1221]
**Is your feature request related to a problem? Please describe.**
as part of the limit order epic #1105, 
when a user creates a limit order between ETH-token, they first need to switch their ETH to WETH.
we would like to show the following popups in this order once a user clicks the confirm limit order on the widget:
1. deposit eth popup (new) 
2. approve weth spend (existing popup)
3. limit order confirmation (existing popup)

as now the user has weth in his account, we also want to provide the option to withdraw the weth back to eth.
1. on the limit order table, we would like to add a call to action "Withdraw WETH"
2. once clicked, we will open the withdraw popup and allow the user to select the amount they wish to withdraw (new)
3. trigger confirmation popup (new)

mockups:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2606%3A5275

**Comment by Velua** [comment]
@pingustar I've added methods ```depositWeth``` and ```withdrawWeth``` to ```ethBancor``` with prompt support, though we are not expecting any token approvals to take place so not sure if it's worth doing. Branch ```feature/rxOptimistic```

**Comment by Velua** [comment]
Outlined the last leg of work to do on this one with @pingustar will be shipped shortly in ```feature/rxOptimistic```

**Comment by pingustar** [comment]
implemented.

@ashachaf can be tested on feature preview link in branch `feature/rxOptimistic`

**Comment by ashachaf** [comment]
tested it and it looks as expected.
