### ISSUE TITLE
new landing page

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1256]
**Is your feature request related to a problem? Please describe.**
as a user, when i arrive to bancor.network, i would like to land on this new landing page and select my options on what to see next.

https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=1056%3A0

users going to bancor.network -> open this page
clicking the option for swap -> open https://app.bancor.network/eth/swap
clicking the option for earn -> open https://app.bancor.network/eth/data/

about bancor social links:
medium -> blog.bancor.network
discord -> https://discord.gg/EHK8wHbgau
telegram -> https://t.me/bancor
twitter -> https://twitter.com/Bancor

bancor dao links:
vote -> https://app.bancor.network/eth/vote/
discussions -> https://gov.bancor.network/

**Comment by ashachaf** [comment]
few updates.
1. text changes see updated mockup: https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=1703%3A798
2. web view -> trade and earn boxes should be clickable and not just the button
3. footer link update (see in the mockup)

**Comment by pingustar** [comment]
done.
