### ISSUE TITLE
Recommend in a banner in "protection" tab that those not seeing users to view their individual stakes for dual-sided positions --> can see them in zapper, zerion, etc

### ISSUE THREAD

**Issue by DavidMillerCL** [bancorprotocol/webapp#1267]
When staking in a protected pool, the place users go is the "protection" tab
However this tab only shows those stakes which really have IL protection and they can't see anywhere their individual stakes for dual-sided (not IL protected) stakes.

Since the plan is to grow in users, confusing them not showing part of their stakes could be a problem. 

Suggestion would be to show a little banner below all the protected stakes that warns like:

_"If you have provided liquidity to a non-protected pool, we recommend monitoring them in platforms like zapper"_

See this image as an example:
![image](https://user-images.githubusercontent.com/63974332/113358354-f1948100-9345-11eb-9306-44ad9521c8dc.png)

**Comment by ashachaf** [comment]
we are aware of this issue and are about to release a fix that addresses it.
