### ISSUE TITLE
mfg swap error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1271]
go to swap, and try to swap mfg to eth

![image](https://user-images.githubusercontent.com/40430285/113502223-890af700-9533-11eb-8cd0-7bf7a539bd95.png)

**Comment by Velua** [comment]
Any tips on reproducing? Struggling to repeat the same error.

**Comment by ashachaf** [comment]
meytal had the same issue the other day.
it might be related to stale api data?

**Comment by Ran73Cohen** [comment]
Doesn't occur anymore, most likely fixed during the refactor.
Closing
