### ISSUE TITLE
bond token image

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1272]
bond token
![Token Image_bond](https://user-images.githubusercontent.com/40430285/113504517-4819df00-9541-11eb-99dc-1c0572145d4f.png)

**Comment by Velua** [comment]
Is this the token address? https://etherscan.io/token/0x5Dc02Ea99285E17656b8350722694c35154DB1E8

**Comment by ashachaf** [comment]
https://etherscan.io/token/0x0391D2021f89DC339F60Fff84546EA23E337750f
