### ISSUE TITLE
Decomission stale View layer properties

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#1289]
There are several properties on ```ViewReserve``` on ```ViewRelay``` which would be good if we can decomission. 

## ViewReserve
Can we remove ```balance``` and ```reserveWeight```
Using ```tokenBalance``` getter in favour

## ViewRelay
```name```

**Comment by pingustar** [comment]
Also removed can be the following Components: @ashachaf please confirm that they are indeed decomissioned and not planning a comeback.

- [ ] AddProtectionDouble
- [ ] WithdrawProtectionDouble

**Comment by Velua** [comment]
@ashachaf can discuss this one in a meeting either tonight or tomorrow.

**Comment by ashachaf** [comment]
we do not have plans on bringing back the option to:
- [ ] AddProtectionDouble - where a user can stake pool tokens into protection
- [ ] WithdrawProtectionDouble - where a user can withdraw 2 separate protected positions together.
you can remove.
