### ISSUE TITLE
Swap/Pool tabs - hover 

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#129]
Please change the color of hover states in "swap/pool" tabs ( just the background of the button).

Zeplin:
Light mode (Color: E9F2FD) : https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=506%3A1086 
Dark Mode (Color: 0A316E) :  https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1913%3A4

Thanks

**Comment by Velua** [comment]
Same thing, confirm this is still a present issue.

**Comment by Velua** [comment]
@Ran73Cohen
