### ISSUE TITLE
Swap popup box top isn't aligned

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#1302]
When switching between swap/pool popups, the top of the background box height differs.

1. Go to the swap popup
2. Note the box top
3. Switch to the pool tab
4. Note the box top now changed

The top of the background box should stay fixed.

![image](https://user-images.githubusercontent.com/1134236/114438656-f4059f00-9bbf-11eb-8cdb-631c50145a0d.png)

**Comment by pingustar** [comment]
@yudilevi is this still happening after the recent feature launch? Cannot seem to reproduce

**Comment by pingustar** [comment]
closing, please reopen if issue is still happening.
