### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#1307]
### Create a Status Page

Requirements that come to my mind:

- [ ] Simple One Pager
- [ ] Hosted on its own
- [ ] preferably hosted on baremetal or similar - NO Firebase / Cloudflare
- [ ] Needs IP and subdomain access

@ashachaf @yudilevi I assume this is pretty low priority, I am just documenting this here for later.

@ashachaf do we need mockups for this or should we use the Landing Page design elements to build this? I think that would be the easiest and fastest.

**Comment by pingustar** [comment]
Any other ideas @Velua @Ran73Cohen ?

**Comment by Velua** [comment]
I really like the idea, Alchemy, Ethereum, Cloudfare, Github for token meta, Firebase the API... anyone piece could fail us.

**Comment by ashachaf** [comment]
should we consider something like this?
https://www.atlassian.com/software/statuspage



> I really like the idea, Alchemy, Ethereum, Cloudfare, Github for token meta, Firebase the API... anyone piece could fail us.

did you mean to include their status within ours?

**Comment by Velua** [comment]
Yeah pretty much as it's all related to making Bancor operational. 
Also forces us to illustrate what our dependencies are too.

**Comment by ashachaf** [comment]
https://docs.google.com/document/d/1VRjCB4UqK46fJlI6MOEUmegShhb3Z0lQF875BKNrVQA/edit
