### ISSUE TITLE
refactor/fix pool select modal - search

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#132]
- [x] pool select modal search for uppercase string will result in no matches found.

- [ ] @Velua I think we can abstract the search behaviour to the ModalSelect.vue component and remove it from the ModalTokenSelect.vue and ModalPoolSelect.vue component. What are your thoughts about that?

- [ ] @ashachaf posted this to telegram: https://streamable.com/45ld4s ... can we add search by address, is that the same as the token.id prop @Velua ?

**Comment by Velua** [comment]
Given the search on a token is different than search on a pool and can be different than any other item introduced on I think they should remain in their own components. 

Technically ```id``` would work but ```contract``` should be favoured, pretty sure it's offered by the getter that's being used.
