### ISSUE TITLE
data page - tokens are not visible

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1324]
**Describe the bug**
occasionally, the token list on the data table do not load and the user see only the "swap" events below the table.

![image](https://user-images.githubusercontent.com/40430285/115148564-cf4e7300-a068-11eb-9651-70cc47cb0c98.png)

**To Reproduce**
open new incognito browser
1. go to bancor.network
2. click "earn"
3. click "tokens" to view the tokens on the data table

expected - see the list of tokens
actual - tokens are not visible.

**Comment by ashachaf** [comment]
@Velua might be part of #905

**Comment by Velua** [comment]
Tried replicating this but failed, any further steps on reproducing? Is it still happening for you?

**Comment by ashachaf** [comment]
we need to run more tests on #905 
it is acting up on some random cases.

**Comment by pingustar** [comment]
Steps to reproduce:

1. Private Window
2. go to https://bancor.network
3. Click "Earn" CTA
4. Click Token Tab

![image](https://user-images.githubusercontent.com/7262066/116219061-7909c000-a74b-11eb-958c-1982a290a3a0.png)

**Comment by Ran73Cohen** [comment]
Fixed
