### ISSUE TITLE
Empty Swap Widget 

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#1328]
**Describe the bug**
Occasionally I see an empty Swap Widget

**To Reproduce**
1. Use private browser window
2. got to https://app.bancor.network/eth/swap

**Screenshots**
![image](https://user-images.githubusercontent.com/7262066/115203945-4252fa80-a0f8-11eb-8bca-427e4e4a95a1.png)

**Additional context**
Refresh usually fixes the issue.

**Comment by pingustar** [comment]
might be related to #1324

**Comment by ashachaf** [comment]
this happens more often.
typically, if you go thru the landing page and dont have prior caching.

**Comment by Velua** [comment]
We believe this one to now be fixed @ashachaf with my recent update, let us know if you think otherwise.

**Comment by ashachaf** [comment]
cannot reproduce.
