### ISSUE TITLE
Site Enhancements 

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1344]
https://docs.google.com/document/d/13O5jql3EQn_rT792j6Nc_lMBtX-NPlo_B-SWm_L_kn4/edit

**Comment by pingustar** [comment]
@yudilevi can we revive the staging subdomain? Or any domain I can use for testing these headers?

I have them all lined up but one of them seems to be locking down the site to aggressively and causes the app to show just a blank site. To test which response header is faulty I would like to test this on a staging/testing environment.

**Comment by yudilevi** [comment]
Sure but isn't it possible to test it in one of the test deployments?

**Comment by pingustar** [comment]
> Sure but isn't it possible to test it in one of the test deployments?

yeah thats the idea, but to be as close to the production environment I thought it would be good to use a bancor.network subdomain like we use on production. 

But I will test it with the firebase provided domain, should be sufficient.
