### ISSUE TITLE
WETH deposit transaction - gas too low

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1345]
**Describe the bug**
when we create a transaction for ETH<>WETH deposit (as part of the limit order process), we trigger it with about 50% of the required gas for the transaction. this results in the transaction to fail.

**To Reproduce**
1. Go to 'swap'
2. Click on 'limit'
3. set a transaction from ETH to any token
4. first popup would be to deposit ETH into WETH, confirm
5. check metamask transaction - gas should be around 48k and we send it with 28k

**Comment by Velua** [comment]
@ashachaf I've now just doubled the estimate,
