### ISSUE TITLE
"Choose your country" popup

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#135]
Here is a design for "choose your country" popup in Zeplin:

Step 1: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f4d354bfeea9caf6d7af908/
Step 2: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f4d354e99c4a7bb548aa17c/
Step 3: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f4d354f6bfcc7104ad929f7/

**Comment by Velua** [comment]
@yudilevi @ashachaf can we get a run down on how/when this is to be used?

**Comment by yudilevi** [comment]
I'm guessing it should be used when the app can't identify the country on its own, due to brave browser shield, ad blockers etc.

**Comment by Velua** [comment]
And we'll take the users entered country as truth then?

**Comment by yudilevi** [comment]
@ashachaf ?
