### ISSUE TITLE
following "withdraw protected position" - website shows blank page

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1356]
**Describe the bug**
after withdrawing protected position, the site i see is blank.

![image](https://user-images.githubusercontent.com/40430285/115766325-83753400-a3b0-11eb-8a76-f1cc7406e1e9.png)

**To Reproduce**
1. go to protfolio
2. withdraw a protected position
3. sign the trnasaction on metamask
expected: see the portfolio page
actual: see blank page

**Comment by Velua** [comment]
@pingustar to investigate now that ropsten should be 100% operational.
