### ISSUE TITLE
Wrong message displayed when trying to remove liquidity

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#136]
When trying to remove liquidity, the app might show the wrong message -

![image](https://user-images.githubusercontent.com/1134236/91770184-66a1ab80-ebe9-11ea-9374-6581897146b6.png)

The pool was WINGS / BNT in this particular case and here's the console log -

![image](https://user-images.githubusercontent.com/1134236/91770250-86d16a80-ebe9-11ea-9288-1dcec05e2374.png)

**Comment by Velua** [comment]
What's the public IP of this user? The app will block the user if the API response returns an unknown as well, should we stop this behaviour and allow unknowns?

**Comment by Velua** [comment]
@yudilevi

**Comment by yudilevi** [comment]
I can't get the IP but I think the solution in case we can't identify the country is this -
https://github.com/bancorprotocol/webapp/issues/135

**Comment by pingustar** [comment]
@yudilevi I am closing this, as it is expected behaviour to block UNKOWN IP until we have implemented #135. If you want to allow UNKOWN IP please reopen.
