### ISSUE TITLE
Google Tag Manager Integration

### ISSUE THREAD

**Issue by Ran73Cohen** [bancorprotocol/webapp#1374]
Doc for the events needed to be integrated
https://docs.google.com/spreadsheets/d/1MO8vHa_YIsqUIr0DJmTZFkPKwUvrQE0w3h0Xb_VoDLw/edit#gid=1439640141

**Comment by Velua** [comment]
To create our own inhouse wrapper with methods to call so we're not stuck using the direct ```push``` system in can we wanna change things later down the track.
