### ISSUE TITLE
Setup Staging Environment for testing on Firebase

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#14]
- [x] create firebase project 

- [x] setup GitHub actions for CI (https://github.com/marketplace/actions/github-action-for-firebase)

- [x] setup subdomain and add TXT/A Records in DNS zone settings (optional)

**Comment by Velua** [comment]
@yudilevi what sub domain do you want to use for beta?

**Comment by yudilevi** [comment]
staging.swap.bancor.network?

**Comment by pingustar** [comment]
closed. 

CI is setup using GitHub Actions. Whenever you push to master it will be auto deployed to firebase production instance. Same goes for staging.

@yudilevi @Velua we can also talk about rules to those branches to protect them from accidental deployments. 

Subdomain is also set up and will be available shortly.
