### ISSUE TITLE
"Create a pool" UI review 

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#140]
Hi, 

Please fix following points:

**Create a pool step 1**

- [ ] add separation line below the title (screenshot 1)

- [ ] please change the design of the slider as it is in Zeplin (screenshot 1)

- [ ] please replace PLUS button (screenshot 1)

- [ ] please change the color of "select a token" text (screenshot 1)
 
- [ ] please change the style of inactive button (screenshot 1)

**Select a token**

- [ ] please add a separation line (screenshot 2)

- [ ] please align the title centrally   (screenshot 2)

- [ ] search icon is missing (screenshot 2)

- [ ] search box should be 32 px height (screenshot 2)

- [ ] please add border and shadows to token images(screenshot 2)

- [ ] can we remove "more" button and leave infinite scroll?(screenshot 3)

- [ ] can you please reduce white space to 16 px? (screenshot 3)

**Create a pool step 2**

- [ ] please change input text color to 0A2540 (screenshot 4)

- [ ] please change % color to D0D7DF (screenshot 4)

**Confirmation**

- [ ] can you please align pool name left + add token images if possible

- [ ] please change box bg to grey

- [ ] please fix spacing between rows

Thank you!

<img width="1175" alt="1" src="https://user-images.githubusercontent.com/69288176/91866167-e1ff6d80-ec7a-11ea-8022-22b4d73ff267.png">

<img width="1019" alt="2" src="https://user-images.githubusercontent.com/69288176/91866179-e62b8b00-ec7a-11ea-9630-81845c846b85.png">

<img width="1193" alt="3" src="https://user-images.githubusercontent.com/69288176/91866191-e9bf1200-ec7a-11ea-8bd2-ea4d49fdfedf.png">

<img width="1017" alt="4" src="https://user-images.githubusercontent.com/69288176/91866204-edeb2f80-ec7a-11ea-9c74-36b510238221.png">

<img width="945" alt="5" src="https://user-images.githubusercontent.com/69288176/91866224-f17eb680-ec7a-11ea-980c-a58199aca4a5.png">

**Comment by Velua** [comment]
@pingustar please validate this one, not sure if these screen shots are too stale to work with anymore. Assign to @Ran73Cohen if you can.

**Comment by pingustar** [comment]
seems pretty outdated. Lets close this.
