### ISSUE TITLE
Pool creation for users who are not connected

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#141]
Users who haven't connected their wallets have an access to pool creation flow which ends up with a complicated error message. In order to improve user experience, is it possible not to allow users who haven't connected their wallets to be able to progress in pool creation flow? I would change main button to "connect a wallet" on the first step. 

Zeplin: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f4f320c8fe8fdb1a8fa0868/.

Thanks!

**Comment by pingustar** [comment]
@katyarozenfeld thanks for bringing this to my attention.

On swap we open the login modal when a user clicks the button but isnt logged in. To have a consistent UX we should do either or for all action buttons. My suggestion is to open the login modal. What are your thoughts about that?

**Comment by katyarozenfeld** [comment]
Yes, I think consistently displaying login modal on early steps when user wants to continue with a specific task is a good solution. The intention is not to allow users to progress within specific flow before they connect their wallets in order to avoid frustration. Thanks!

**Comment by pingustar** [comment]
fixed.
