### ISSUE TITLE
portfolio -> pool token view : search doesnt work

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1412]
**Describe the bug**
![image](https://user-images.githubusercontent.com/40430285/116576327-22051600-a918-11eb-8a6d-1ed7bf26371f.png)

**To Reproduce**
1. Go to portfolio -> pool tokens
2. try to search
expected: table list will display based on the search critiria
actual: nothing happens.

logic:
when search -> try to match the search string with the pool name (basically one of the two reserves in the pool) based on token symbol.

**Comment by tiagofilipenunes** [comment]
As a related issue, the search feature on the portfolio->liquidity protection page finds the tokens you've staked, and not by the pool name. E.g. if you've staked BNT in the LINK/BNT pool and search "LINK", that position won't show up unless you search "BNT". Is this behaviour expected?

**Comment by ashachaf** [comment]
@tiagofilipenunes 
given that bnt is in all pools, the update you suggest will result that you are unable to search for bnt positions.
to view a specific pool, you can use the filter option.

**Comment by tiagofilipenunes** [comment]
@ashachaf I completely agree, the search in the Liquidity Protection tab makes more sense that way, thanks for explaining!
