### ISSUE TITLE
Add Portuguese translation

### ISSUE THREAD

**Issue by tiagofilipenunes** [bancorprotocol/webapp#1416]
I've translated the en.ts file to Portuguese (Portugal). Is there any ongoing work on translations?
[pt.zip](https://github.com/bancorprotocol/webapp/files/6406368/pt.zip)

**Comment by Velua** [comment]
Muito brigado!

Not that I know of, just voluntary submitted stuff as far as I know.

**Comment by ashachaf** [comment]
hi @tiagofilipenunes,
we actually are working on several languages at the moment. 
i'll compare your text to the translations we have.

thanks for the contribution!
