### ISSUE TITLE
KNCL pool issues with add/remove dual side liquidity

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1417]
**Describe the bug**
when trying to add/remove dual side liquidity from the KNCL pool, something doesnt work as expected.

**To Reproduce**
add dual side
1. Go to https://app.bancor.network/eth/pool/add/0x248AFFf1aa83cF860198ddeE14b5b3E8eDb46d47
2. enter BNT amount
expect the KNCL amount to be filled automatically based on the pool rate.
actual: nothing happens

remove pool tokens
when trying to view the pool token and value on the "pool tokens" tab, their value and amount is 0.

![image](https://user-images.githubusercontent.com/40430285/116807566-8a344180-ab3c-11eb-83ad-10524e047752.png)

**Comment by ashachaf** [comment]
@Velua seems like something is off with KNCL pool.
pool anchor: 0x248AFFf1aa83cF860198ddeE14b5b3E8eDb46d47
KNCL token address: 0xdd974D5C2e2928deA5F71b9825b8b646686BD200

**Comment by Velua** [comment]
Looks like this has now been fixed as a side effect after merging this [PR](https://github.com/bancorprotocol/webapp/pull/1432)

**Comment by pingustar** [comment]
This has been an API issue.
