### ISSUE TITLE
error "Failed calculating slippage Rates are bad"

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1418]
**Describe the bug**
while on the add dual side liquidity, waiting for my approve transaction to go thru (in the process of the add liquidity for KNCL/BNT), i have noticed this error message in the console
![image](https://user-images.githubusercontent.com/40430285/116805310-33277000-ab2e-11eb-8f28-7ebd6c5e862d.png)

**To Reproduce**
1. Go to add liquidity dual side for KNCL/BNT
2. initiate the add liquidity process
3. sign the approve transaction
see the error in the console

wider view of the console log:
![image](https://user-images.githubusercontent.com/40430285/116805343-96b19d80-ab2e-11eb-86d4-86f1d57804a8.png)

**Comment by Velua** [comment]
Is there any issues for the user here or just console logs?

**Comment by ashachaf** [comment]
just console log at this stage.
but it is triggered in a place where there is no need for this type of data anyways.
