### ISSUE TITLE
Data - transactions table - displaying "swap/add/remove" amounts

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#142]
Hi, 

Following our conversation yesterday - please merge 2 columns of token amount and display transactions in a following way:
1. Swaps - token "arrow" token
2. Add liquidity - tokens that were added with "comma"
3. Remove liquidity - tokens that were removed with "comma"

Updated Zeplin: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f1d282239206735b62d9cbd/

Thanks!

**Comment by Velua** [comment]
@pingustar bump

**Comment by pingustar** [comment]
If I remember correctly, we decided to leave it as is.

@ashachaf please reopen if there is any changes required.
