### ISSUE TITLE
new fiat provider: mercuryo.io

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1421]
we would like to add a new fiat on/off ramp solution to the fiat page (https://app.bancor.network/eth/fiat/)

mockup:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=548%3A7980

buy URL:
https://exchange.mercuryo.io/?widget_id=d7702dc1-c8ee-4726-a5be-5f18e31849b6&currency=ETH&type=buy

sell URL:
https://exchange.mercuryo.io/?widget_id=d7702dc1-c8ee-4726-a5be-5f18e31849b6&currency=ETH&type=sell

logo:
`<svg width="993" height="182" viewBox="0 0 993 182" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M90.1 180.9C66.0129 180.9 43.4375 171.527 26.4051 154.495C9.37282 137.462 0 114.887 0 90.7997C0 66.7126 9.37282 44.1372 26.4051 27.1049C43.4375 10.0725 66.0129 0.699707 90.1 0.699707C114.187 0.699707 136.763 10.0725 153.795 27.1049C170.827 44.1372 180.2 66.7126 180.2 90.7997C180.2 114.887 170.827 137.462 153.795 154.495C136.763 171.527 114.187 180.9 90.1 180.9Z" fill="black"/>
<mask id="mask0" mask-type="alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="181" height="181">
<path d="M90.1 180.9C66.0129 180.9 43.4375 171.527 26.4051 154.495C9.37282 137.462 0 114.887 0 90.7997C0 66.7126 9.37282 44.1372 26.4051 27.1049C43.4375 10.0725 66.0129 0.699707 90.1 0.699707C114.187 0.699707 136.763 10.0725 153.795 27.1049C170.827 44.1372 180.2 66.7126 180.2 90.7997C180.2 114.887 170.827 137.462 153.795 154.495C136.763 171.527 114.187 180.9 90.1 180.9Z" fill="#232323"/>
</mask>
<g mask="url(#mask0)">
<path d="M92.5188 181.404H127.591C127.591 165.379 145.43 142.4 145.43 107.832C145.43 78.4033 140.592 62.4796 137.569 55.0216C135.15 48.8738 132.328 45.3464 126.281 45.3464C120.234 45.3464 114.389 47.6645 112.776 61.2702C108.039 101.684 89.9993 125.066 92.5188 181.404Z" fill="white"/>
<path d="M87.1774 181.404H52.1049C52.1049 165.38 34.2664 142.401 34.2664 107.833C34.2664 78.404 39.1039 62.4803 42.1274 55.0223C44.5462 48.8746 47.3681 45.3472 53.4151 45.3472C59.4621 45.3472 65.3075 47.6652 66.92 61.2709C71.5561 101.685 89.5962 125.067 87.1774 181.404Z" fill="white"/>
<path d="M128.71 182.311H91.823V181.404C90.3113 146.23 96.7614 123.856 102.909 102.188C106.739 88.8848 110.367 76.2869 112.181 61.0686C112.987 54.6185 114.701 50.184 117.523 47.4629C119.74 45.3465 122.663 44.3386 126.593 44.3386C133.245 44.3386 136.268 48.4707 138.687 54.6185C143.827 67.5187 146.548 85.962 146.548 107.731C146.548 128.492 140.199 145.122 135.059 158.425C131.632 167.294 128.71 174.953 128.71 181.303V182.311ZM93.6371 180.497H126.896C127.198 174.046 130.02 166.488 133.346 157.921C138.385 144.719 144.734 128.291 144.734 107.832C144.734 86.2644 142.013 68.1234 136.974 55.4248C134.353 48.7731 131.532 46.3543 126.593 46.3543C121.252 46.3543 115.608 48.1684 113.995 61.4717C112.181 76.8915 108.553 89.4894 104.723 102.894C98.6763 124.058 92.327 146.029 93.6371 180.497Z" fill="black"/>
<path d="M88.3252 182.311H51.4387V181.404C51.4387 175.054 48.516 167.395 45.0894 158.526C39.9494 145.223 33.6001 128.593 33.6001 107.832C33.6001 85.9621 36.3212 67.6196 41.4612 54.7193C43.88 48.5716 46.9035 44.4395 53.5551 44.4395C57.4857 44.4395 60.3076 45.4473 62.6256 47.5637C65.4475 50.2849 67.2616 54.7193 67.9671 61.1694C69.7812 76.3877 73.4094 88.9855 77.2391 102.289C83.4877 123.957 89.837 146.23 88.3252 181.504V182.311ZM53.3536 180.497H86.612C88.0229 146.13 81.6736 124.058 75.5258 102.793C71.6961 89.3887 68.0679 76.7908 66.2538 61.371C64.742 48.0677 58.9974 46.2536 53.6559 46.2536C48.7175 46.2536 45.8956 48.6724 43.2753 55.324C38.2361 68.0227 35.515 86.1637 35.515 107.731C35.515 128.089 41.8643 144.618 46.9034 157.82C50.2293 166.488 53.0512 173.946 53.3536 180.497Z" fill="black"/>
<path d="M90.175 181.807H89.2679C81.6084 181.807 75.2591 177.674 70.8247 169.813C66.8941 162.96 64.5761 153.487 63.9714 142.4C62.762 121.034 60.444 80.3181 58.9323 62.0763C58.3276 54.0137 55.7072 53.3082 53.3892 53.3082C50.6681 53.3082 48.9548 55.5254 47.3422 61.2701C45.9313 66.41 40.9929 90.4971 43.0086 115.088C44.218 130.105 49.0555 142.703 53.3892 153.789C57.3197 163.968 60.6456 172.736 60.6456 181.303H58.8315C58.8315 173.038 55.5057 164.472 51.6759 154.494C47.3422 143.207 42.4039 130.508 41.1945 115.189C39.1788 90.3964 44.218 65.9061 45.6289 60.7662C46.9391 55.9286 48.854 51.3933 53.3892 51.3933C57.9244 51.3933 60.1417 54.5176 60.7464 61.774C62.1573 80.0157 64.5761 120.833 65.7855 142.199C66.3902 152.983 68.7082 162.154 72.4372 168.806C76.5693 176.163 82.3139 179.892 89.2679 179.892H90.175C93.8032 179.892 97.129 178.884 100.052 176.969C102.874 175.155 105.292 172.333 107.409 168.806C111.339 162.154 113.758 152.781 114.363 142.199C115.572 120.833 117.89 80.0157 119.402 61.774C120.007 54.4168 122.224 51.3933 126.759 51.3933C131.294 51.3933 133.209 55.8278 134.519 60.7662C135.93 65.9061 140.97 90.3964 138.954 115.189C137.745 130.407 132.806 143.307 128.473 154.595C124.643 164.673 121.317 173.341 121.317 181.605H119.503C119.503 173.038 122.929 164.17 126.759 153.99C130.992 142.804 135.93 130.105 137.14 115.088C139.156 90.5979 134.217 66.41 132.806 61.2701C131.194 55.5254 129.48 53.3082 126.759 53.3082C124.441 53.3082 121.922 54.0137 121.216 62.0763C119.805 80.3181 117.386 121.034 116.177 142.4C115.572 153.386 113.053 162.859 109.021 169.813C104.285 177.574 97.8345 181.807 90.175 181.807Z" fill="black"/>
<path d="M103.92 45.5481V46.8583C95.6559 48.6724 92.4308 51.7967 90.6168 60.3632H89.0042C87.1901 51.6959 84.2674 48.6724 75.6001 46.8583V45.5481C84.1667 43.734 87.0893 40.6098 89.0042 32.0432H90.6168C92.5316 40.7106 95.7567 43.734 103.92 45.5481Z" fill="white"/>
</g>
<path d="M90.1 180.9C66.0129 180.9 43.4375 171.527 26.4051 154.495C9.37282 137.462 0 114.887 0 90.7997C0 66.7126 9.37282 44.1372 26.4051 27.1049C43.4375 10.0725 66.0129 0.699707 90.1 0.699707C114.187 0.699707 136.763 10.0725 153.795 27.1049C170.827 44.1372 180.2 66.7126 180.2 90.7997C180.2 114.887 170.827 137.462 153.795 154.495C136.763 171.527 114.187 180.9 90.1 180.9ZM90.1 2.91695C41.6234 2.91695 2.21722 42.3231 2.21722 90.7997C2.21722 139.276 41.6234 178.682 90.1 178.682C138.577 178.682 177.983 139.276 177.983 90.7997C177.983 42.4239 138.577 2.91695 90.1 2.91695Z" fill="black"/>
<path d="M954.032 62.5046C932.716 62.5046 915.433 79.7878 915.433 101.104C915.433 122.42 932.716 139.703 954.032 139.703C975.348 139.703 992.631 122.42 992.631 101.104C992.631 79.7878 975.348 62.5046 954.032 62.5046ZM954.032 129.151C938.538 129.151 925.985 116.588 925.985 101.104C925.985 85.6095 938.548 73.0565 954.032 73.0565C969.526 73.0565 982.079 85.6196 982.079 101.104C982.079 116.598 969.516 129.151 954.032 129.151Z" fill="black"/>
<path d="M520.325 62.5046C509.44 62.5046 501.202 71.126 498.817 78.1505V65.5267H466.798V76.1088H488.326V126.574L466.737 126.604V137.095L525.47 137.065V126.574H498.817V94.5746C498.817 89.7737 502.961 72.3894 517.313 72.3894C521.7 72.3894 525.712 73.5517 528.32 76.594C527.299 77.9685 526.693 79.6665 526.693 81.506C526.693 86.0846 530.402 89.7838 534.97 89.7838C539.892 89.7838 543.086 85.7713 543.086 80.9097C543.107 72.915 534.061 62.5046 520.325 62.5046Z" fill="black"/>
<path d="M793.703 62.4744C782.817 62.4744 774.58 71.0553 772.195 78.0798V65.5469L740.175 65.5267V76.119H761.704V126.503L740.115 126.533V137.025L798.847 136.994V126.503H772.195V94.514C772.195 89.7131 776.339 72.3288 790.691 72.3288C795.077 72.3288 799.09 73.4911 801.698 76.5334C800.677 77.908 800.07 79.606 800.07 81.4455C800.07 86.024 803.78 89.7232 808.348 89.7232C813.27 89.7232 816.464 85.7107 816.464 80.8491C816.484 72.8443 807.438 62.4744 793.703 62.4744Z" fill="black"/>
<path d="M619.021 96.2725C623.6 96.2725 627.299 92.5632 627.299 87.9947C627.299 87.641 627.269 87.2872 627.228 86.9436C626.177 77.4025 611.198 62.6663 592.136 62.6663C570.547 62.6663 553.042 79.9899 553.042 101.346C553.042 122.703 570.547 140.026 592.136 140.026C607.085 140.026 620.062 131.718 626.632 119.519L618.182 113.808C613.007 123.056 603.385 129.464 592.126 129.464C576.44 129.464 564.139 116.881 564.139 101.356C564.139 85.8318 576.44 73.2484 592.126 73.2484C600.828 73.2484 608.166 76.5737 613.038 82.264C611.602 83.7497 610.723 85.7712 610.723 88.0048C610.743 92.5632 614.453 96.2725 619.021 96.2725Z" fill="black"/>
<path d="M878.683 76.1291H887.365L868.607 124.734L848.13 76.1392H857.024V65.5369H826.217V76.1291H836.88L863.149 138.915L848.655 176.503H859.884L898.584 76.1392H909.49V65.5369H878.683V76.1291Z" fill="black"/>
<path d="M354.619 92.8865C354.619 74.1176 342.086 62.4944 326.743 62.4944C314.695 62.4944 304.649 71.1966 300.242 80.0808C295.957 69.0539 286.082 62.4944 274.631 62.4944C263.179 62.4944 253.386 71.0652 250.333 78.0998V65.5063L228.532 65.5467V76.1289H239.842V136.994H250.333V94.4026C250.333 89.5006 256.216 72.1467 273.105 72.1467C281.11 72.1467 292.015 79.3834 292.015 94.2005C292.015 101.68 292.015 137.004 292.015 137.004H302.506C302.506 137.004 302.506 94.9484 302.506 94.2005C302.506 89.2985 307.732 72.1467 325.227 72.1467C333.232 72.1467 344.138 78.6759 344.138 93.4829C344.138 100.962 344.138 137.004 344.138 137.004H365.918V126.584H354.629L354.619 92.8865Z" fill="black"/>
<path d="M416.151 62.4644C394.784 62.4644 377.471 79.4848 377.471 100.851C377.471 101.559 377.633 104.389 377.673 104.823C379.624 124.381 396.29 139.673 416.565 139.673C431.514 139.673 444.491 131.365 451.061 119.165L442.611 113.455C437.437 122.703 427.815 129.111 416.555 129.111C402.163 129.111 390.165 118.508 388.356 104.763L453.163 104.803C453.295 103.509 453.365 102.185 453.365 100.861C453.375 79.4848 437.517 62.4644 416.151 62.4644ZM388.74 94.2614C391.712 81.8397 402.88 72.6018 416.212 72.6018C429.543 72.6018 439.256 81.8397 442.227 94.2614H388.74Z" fill="black"/>
<path d="M712.876 65.5369H702.385L702.395 107.896C702.395 117.538 692.328 130.546 679.553 130.546C671.548 130.546 660.713 122.966 660.713 109.2C660.713 101.72 660.713 65.5369 660.713 65.5369L638.932 65.5571V76.0988H650.222V109.796C650.222 128.565 662.724 139.663 678.067 139.663C688.932 139.663 697.331 132.962 702.395 125.937V137.085L724.196 137.045V126.554H712.886L712.876 65.5369Z" fill="black"/>
</svg>
`

**Comment by tiagofilipenunes** [comment]
I can help with this if you want, should be just adding it to GatewayProviders.vue. I would need the dark logo and text to put up though.

**Comment by ashachaf** [comment]
https://svgshare.com/i/Wyf.svg
https://svgshare.com/i/WxL.svg
![Group 1962 (1)](https://user-images.githubusercontent.com/40430285/117120159-a97cda00-ad9b-11eb-99b8-1fa7939c9655.png)

text:
Mercuryo is a cross-boarder payment network providing global access to fast and cheap money transfers. Working together with industry leaders, Mercuryo offers a multi-currency widget that allows purchase and sell crypto securely with the lowest fees.

@tiagofilipenunes if this helps, would be happy to see your contribution.

**Comment by ashachaf** [comment]
thanks @tiagofilipenunes !

**Comment by tiagofilipenunes** [comment]
Happy to help! 😁 @ashachaf @Ran73Cohen
