### ISSUE TITLE
error: "Failed to estimate gas"

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1425]
**Describe the bug**
when trying to swap tokens (tested swapping ETH->BNT), there is a console error indicating there was an error with calculating gas estimation for the transaction.
in my case, the metamask transaction was opened correctly.
we however get some reports of transactions with 1gwei gas settings.

![image](https://user-images.githubusercontent.com/40430285/116812251-831a2d00-ab56-11eb-9f8e-a59024f7ecd8.png)

**To Reproduce**
1. Go to swap
2. Click on eth and bnt
3. confirm the transaction on our site (in order to trigger the metamask window)
open console log to see error

**Comment by Velua** [comment]
We try to estimate gas and apply a bit of a buffer to it ourselves but MetaMask doesn't always work. 

Never do we suggest what the price should be though, that's entirely on Web 3 so weird that's happening, what is the gas amount getting estimated?

**Comment by ashachaf** [comment]
the bug is only on console from the looks of it.
as the metamask window is ok to sign.

**Comment by Velua** [comment]
Okay I've since removed the log as it's sometimes to be expected to failure and the code will expect that, given the nature of Web3.
