### ISSUE TITLE
multiple pools not shown as white listed on the main data table

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1427]
**Describe the bug**
on the main pool data table, GNO pool is not marked as white listed (as a result, adding liquidity opens dual side).
edit: i actually found another pool that is not marked as white listed. OMG. 0x99eBD396Ce7AA095412a4Cd1A0C959D6Fd67B340

pool anchor:
0xd7eB9DB184DA9f099B84e2F86b1da1Fe6b305B3d

![image](https://user-images.githubusercontent.com/40430285/116813448-90d2b100-ab5c-11eb-82cf-312294123a77.png)
![image](https://user-images.githubusercontent.com/40430285/116813478-a2b45400-ab5c-11eb-86e5-4fdad611a451.png)

**Comment by Velua** [comment]
The shield does not illustrate a pool being whitelisted but it's ability for liquidity protection which is dependent on holding BNT, being whitelisted and having enough BNT in reserves. 

While the pool does, the API is giving us reserve balance data for the old converter which is zero causing it to fail. 

I've reached out to Yariv to investigate, will see if I can get a bandaid solution going too.
