### ISSUE TITLE
incorrect network indication

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1430]
**Describe the bug**
![image](https://user-images.githubusercontent.com/40430285/116816058-10667d00-ab69-11eb-96b1-fd044365d0ab.png)

**To Reproduce**
1. Go to swap
2. open metamask and change network
3. go back to the widget, input a token amount 
see error

expected: once the network has switched to a not supported chain, we should auto force the page to open the "incorrect network" message.

please update the design of this page:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=4658%3A11060

**Comment by pingustar** [comment]
@Velua seems like the getter does not update automatically? Can I hand that over to you - or get some guidance on how to fix.

**Comment by Velua** [comment]
PR should fix the issue, give it a test.

**Comment by Velua** [comment]
@pingustar
