### ISSUE TITLE
Data - buttons that take the user to the swap app should open it in a new tab

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#145]
This should be the behavior regardless of the fact it's the same app technically.

**Comment by ashachaf** [comment]
i do not see this "new tab" behavior on staging.
@pingustar

**Comment by pingustar** [comment]
works fine on my end @ashachaf 

are you still able to reproduce this?

**Comment by Velua** [comment]
@ashachaf This is what I see on my end - https://streamable.com/4xbdsf What's the experience for you?

**Comment by pingustar** [comment]
I think he means a new tab for the Add Liquidity and Trade buttons in the table action column on the data page.

I have added it.
