### ISSUE TITLE
Data - token list has no data other than the token symbols

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#146]
Might be a sorting issue.

![image](https://user-images.githubusercontent.com/1134236/92445907-b53ce000-f1bd-11ea-8712-d2e0ff5f8f8d.png)

**Comment by ashachaf** [comment]
when navigating thru the pages (1,2,3,4,etc) i've noticed that it is not sorted by liquidity either.

default view should be:
1. pull all tokens
2. sort by liquidity from deepest to shallowest pool 
3. display by pages

if i change sort, it needs to pull the entire data and sort based on the new critiria.

**Comment by Velua** [comment]
Should be sorted now
