### ISSUE TITLE
Pool creation - ensure that the registry doesn't contain a pool with a similar config before proceeding

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#149]
The app can check it by calling `Converter.Registry.getLiquidityPoolByConfig` before proceeding.
Otherwise the user gets an exception with no reason given.

**Comment by Velua** [comment]
This should already be the case, is this not what you've seen?

**Comment by yudilevi** [comment]
There was an issue yesterday but I think it was related to an issue in the contract. Closing this one.
