### ISSUE TITLE
Swap - output amount shows 0

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#150]
Seems like it's due to timing/race conditions - usually more apparent when it takes a while to get the result.

![image](https://user-images.githubusercontent.com/1134236/92659424-030e3100-f301-11ea-8b40-646c216611bb.png)

**Comment by Velua** [comment]
Any tricks on reproducing? Seems to work okay on my end

**Comment by yudilevi** [comment]
Just reproduce again -

- loaded the app
- quickly opened the target token selection
- selected USDT
- put in 0.01 in the ETH source amount
- output amount stayed empty (waited like 10 seconds)
- changed the input amount to 0.011
- reproduced again

Might have something to do with slow connection as well.

**Comment by Velua** [comment]
Yeah might be, just tried again here. https://streamable.com/5gg6ei

@pingustar Can you see if you're able to reproduce this?

**Comment by pingustar** [comment]
@Velua @yudilevi works on my end. Followed the steps, cannot reproduce.

**Comment by Velua** [comment]
@yudilevi what browser are you using?

**Comment by yudilevi** [comment]
@Velua chrome
