### ISSUE TITLE
token logo update - MFG

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1503]
MFG have updated their logo.
token address: 0x6710c63432A2De02954fc0f851db07146a6c0312

 &lt;svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 350 350"&gt;&lt;defs&gt;&lt;style&gt;.cls-1{fill:#e5c45d;}.cls-2{fill:url(#linear-gradient);}.cls-3{fill:url(#linear-gradient-2);}.cls-4{fill:url(#linear-gradient-3);}&lt;/style&gt;&lt;linearGradient id="linear-gradient" x1="240.44" y1="135.29" x2="163.29" y2="183.67" gradientUnits="userSpaceOnUse"&gt;&lt;stop offset="0" stop-color="#e5c45d"/&gt;&lt;stop offset="1" stop-color="#987a3b"/&gt;&lt;/linearGradient&gt;&lt;linearGradient id="linear-gradient-2" x1="174.35" y1="254.01" x2="175.65" y2="187.97" xlink:href="#linear-gradient"/&gt;&lt;linearGradient id="linear-gradient-3" x1="106.13" y1="134.29" x2="173.6" y2="172.67" xlink:href="#linear-gradient"/&gt;&lt;/defs&gt;&lt;path class="cls-1" d="M248.27,199.15A66.88,66.88,0,0,1,193.73,93.54h-37.5a66.88,66.88,0,0,1-54.54,105.61,68.46,68.46,0,0,1-7-.37L114,232.37a66.89,66.89,0,0,1,121.88,0l19.4-33.59A68.46,68.46,0,0,1,248.27,199.15Z"/&gt;&lt;path class="cls-2" d="M235.49,175.77a24.6,24.6,0,0,1,20-24.17l-19.35-33.51a24.6,24.6,0,0,1-41.54-24.55h-.92a66.88,66.88,0,0,0,54.54,105.61c1.28,0,2.55,0,3.81-.11A24.62,24.62,0,0,1,235.49,175.77Z"/&gt;&lt;path class="cls-3" d="M144.76,228.16a24.61,24.61,0,0,1,11.65,28.3h38.24A24.61,24.61,0,0,1,230,227.36a25.18,25.18,0,0,1,5.5,4.18,66.89,66.89,0,0,0-121.49.83l.46.81A24.61,24.61,0,0,1,144.76,228.16Z"/&gt;&lt;path class="cls-4" d="M156.23,93.54h-.49a24.6,24.6,0,0,1-41.8,24.26L94.46,151.53a24.6,24.6,0,0,1,3.78,47.53q1.71.09,3.45.09A66.88,66.88,0,0,0,156.23,93.54Z"/&gt;&lt;/svg&gt;

**Comment by pingustar** [comment]
added
