### ISSUE TITLE
Attempt decomission of <data-table /> component

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#151]
## Task 
In house component ```<data-table />``` is currently used for components ```TablePools.vue``` and ```TableTokens.vue``` lets see if we can stop using this component and instead use the Bootstrap Vue provided component ```<b-table />``` instead, this migration has already been started with it's use in ```TableTransactionsNew.vue``` as an example of what it might look like. 

## Background
```<data-table />``` was used in the name of extra flexibility but has come at the cost of further in house logic to maintain the component, know props and lack of documentation, we're attempting a move back to ```<b-table />``` for more consistency, less code in the app and free documentation / maintenance of the component. 

## Requirements
- Migration to ```<b-table />``` must retain the same aesthetics it has in it's present form.

**Comment by Velua** [comment]
Bonus, if ```TableTransactions.vue``` is no longer in use because it's been replaced by ```TableTransactionsNew.vue``` please just delete ```TableTransactions.vue``` and rename ```TableTransactionsNew.vue``` to ```TableTransactions.vue``` in replacement.

**Comment by pingustar** [comment]
this is done and can be reviewed. Two small visual aspects are not supported by the native `<b-table />` component:

1. the sort icon can only be placed to the left or right of the table column. This restrictions is due to the way the icon is implemented by bootstrap-vue. The icon is set as CSS background and the CSS doesnt know how wide the column header text is in order to place the icon next to it.

2. Pagination isnt 100% as mockups show, there might be more options to get it closer to the anticipated design. We also might want to change the mockups to a more functional design. Like go to first/last page buttons. Which I think are pretty usefull.

I also created an optional wrapper for the native `<b-table />` component to further reduce overhead and speed up future usage of this specific table. Usage examples can be found in `TableTransactionsNew.vue` or `DataDetailsPool.vue`

**Comment by Velua** [comment]
Waiting on me.

**Comment by ashachaf** [comment]
@Velua is this done?

**Comment by Velua** [comment]
Still determining strategy, #390 has prompted a change the current component/strategy does not allow. 

Reviewing what our options are, if at the worst we'll just write it ourselves. Just cleaner if we're able to re-use things. 

Priority wise I'd say this is on the back burner compared to current priorities. 

@pingustar I know it's a long shot, but can you hop on their repo or whatever chat they may have and see if anyone there has an idea before we go with plan B?

**Comment by Velua** [comment]
@pingustar how did this go?

**Comment by Velua** [comment]
Bailing out on ```<b-table />``` and going with an inhouse maintained component, should we not receive an update in 48 hours.

**Comment by Velua** [comment]
Change of course, now writing the component in house

@pingustar lets try replicate the original props/API as much as we can unless we've got a good reason to deviate. 

Reach out to me either during design or once complete with a PR to review. 
Once done we'll give @H34D the low down so he can clear up existing roadblocks posed here.

**Comment by pingustar** [comment]
Current status:

I was able to replicate the original features using dynamic slots for the cells. Next up applying the learned knowledge to do the same with the table head.

Will let you know when I am done @Velua for review. Once review passed, I will replace all old tables with the new ones.

**Comment by Velua** [comment]
Awesome stuff! @pingustar

**Comment by pingustar** [comment]
Component is done and ready for review.

**Comment by Velua** [comment]
Cheers @pingustar

**Comment by pingustar** [comment]
merged to staging. PoolTable on data page is updated as reference. The other tables are following quickly now.

**Comment by Velua** [comment]
As much as I wanna keep this closed and move on with life, I want to make sure we don't half complete the job. 
@pingustar Have we finished migrating all the tables? 

Otherwise do some 
- [ ] Dot
- [ ] points. 

In a new comment on this issue and we'll finish the struggle.

**Comment by pingustar** [comment]
@Velua all tables are migrated except for the vote proposal tables. They are giving me a hard time with vuex mutation errors. Still working on a fix.

**Comment by Velua** [comment]
Alright, if this is still a thing when you sign off for today leave a detailed comment of what's going on and I can take a look at it if you like.

**Comment by pingustar** [comment]
escalated vuex mutation errors to @Velua

**Comment by H34D** [comment]
This component is now only used in DoneProposals

**Comment by pingustar** [comment]
is done proposals utilized? When do proposals move over to the done tab?

**Comment by H34D** [comment]
> is done proposals utilized? When do proposals move over to the done tab?

not yet, but should be a quick one, maybe we can open a specific issue for it and remove the old one afterwards?

**Comment by pingustar** [comment]
https://github.com/bancorprotocol/webapp/issues/755

created an issue with both tasks - so once 755 is closed ... we can finally close this issue here too. fingers crossed ;)

**Comment by Velua** [comment]
@pingustar can we close this?
