### ISSUE TITLE
conversion error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1529]
**Describe the bug**
we have a spike in errors when users try to complete their swap flow.

invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.2.0) (argument=null, value="", code=INVALID_ARGUMENT, version=abi/5.0.7)

**To Reproduce**
1. open swap
2. set up a trade
3. try to execute
4. see the error (i cannot reproduce, but our tracking shows a rapid increase in this error over the last 2 days.

**Comment by pingustar** [comment]
@ashachaf I cannot reproduce. What tracking are we talking about? Can you link me to the reports please

**Comment by pingustar** [comment]
@Ran73Cohen @ashachaf  I see that we send metadata like conversion_token_pair to GTM, how can I check this data on amplitude?

I wanna find out which token pairs throw this error: `invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.2.0) (argument=null, value="", code=INVALID_ARGUMENT, version=abi/5.0.7)`
