### ISSUE TITLE
slippage indication on swap widget - calculation issue

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1539]
**Describe the bug**

![image](https://user-images.githubusercontent.com/40430285/120103827-2d876f00-c15a-11eb-8eb1-d9cd3bcad139.png)
![image](https://user-images.githubusercontent.com/40430285/120103896-8525da80-c15a-11eb-83d4-a68468289b96.png)

**To Reproduce**
1. go to swap
2. select two tokens
3. switch "from" token at the time when we refresh the rates

it seems that we do not pull new rates based on the newly selected token and the slippage indication is off.
in the next rate refresh, this slippage is usually back to normal.

**Comment by Velua** [comment]
Can't seem to replicate this, @pingustar any luck?

**Comment by ashachaf** [comment]
https://streamable.com/3lwysk

> Can't seem to replicate this, @pingustar any luck?
