### ISSUE TITLE
Project contribution requires PRO fontawesome license

### ISSUE THREAD

**Issue by baart1989** [bancorprotocol/webapp#1557]
**Describe the bug**
Running yarn install fails, when you don't have fontawesome PRO account

**To Reproduce**
1. Clone project 'https://github.com/bancorprotocol/webapp.git bancor-webapp'
2. Run yarn install
3. 401 Unauthorized error is thrown because of fontawesome PRO dependencies

**Expected behavior**
All dependecies are installed correctly

**Additional context**
I think the app should use free dependencies if Bancor team wants other Devs to help them out.
If this is somehow impossible, then at least provide some information in readme about above requirement.

**Comment by Ran73Cohen** [comment]
We are aware and plan to migrate away from font awesome

**Comment by baart1989** [comment]
> We are aware and plan to migrate away from font awesome

Is there a task for this ? There are tons of libs with icons, but https://heroicons.com/ is one of my favourite ones.
