### ISSUE TITLE
swap interface - add a CTA to the new beta site

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1570]
**Is your feature request related to a problem? Please describe.**
as a user, when i open the swap page, i should be able to see an option to test out the new trading interface.

**Describe the solution you'd like**
1. add a banner that invited users to test out the new trading interface
2. when clicking the banner, open the URL in a new tab (window on mobile)

**mockups**
https://www.figma.com/file/fwADI9wqDrRAdlMX8EddCw/Bancor-v3?node-id=4842%3A93558

banner text:
title: New Design!
text: 
Check the new trading interface. 
Take Me Now!

**Comment by Ran73Cohen** [comment]
Added
