### ISSUE TITLE
remove liquidity default value missing

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#158]
when you refresh the "remove liquidity" screen:
1. selection is default at 50%, but there is not value in the "remove liquidity amount" that represent that 50%
2. after few sec, the page refresh to update this.

instead of refreshing the page, do not auto select 50%, and let the user select it.

https://streamable.com/gfexgv

**Comment by pingustar** [comment]
okay I have fixed that. Please review.
