### ISSUE TITLE
Token image quality deteriorates when resizing

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#165]
Shows in lists etc., here's an example from the actual poole page -

![image](https://user-images.githubusercontent.com/1134236/93458932-a5be4500-f8e9-11ea-88b5-195c6ec67e73.png)

**Comment by Velua** [comment]
> @yudilevi I have added a higher quality logo to the registry.
> 
> @Velua please review and merge this PR: https://github.com/Velua/eth-tokens-registry/pull/2

Done @pingustar
