### ISSUE TITLE
transaction history is not correct

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#216]
checking on etherscan, i see way more transactions.
first 50 transactions on etherscan are in the last 6 min.
https://etherscan.io/address/0x2f9ec37d6ccfff1cab21733bdadede11c823ccb0#tokentxns

![image](https://user-images.githubusercontent.com/40430285/95294609-47e4a380-087e-11eb-9aa1-ef6268bf4af3.png)

**Comment by ashachaf** [comment]
would you track this transaction in your process?
https://etherscan.io/tx/0x829c108ac6ec904c71fa43dd81fc7d956d9371516b9c29d1ad8477ada3761bd0

if not, we need to understand why.

**Comment by Velua** [comment]
@yudilevi would a Conversion emit have been emitted from the network contract for this one?

**Comment by yudilevi** [comment]
Conversion events are triggered for every conversion in the network.

**Comment by Velua** [comment]
So this will come up even if it started off with a conversion in Uniswap?

**Comment by yudilevi** [comment]
Yup, anywhere, all conversions go through the network contract and it fires these events.

**Comment by Velua** [comment]
> would you track this transaction in your process?
> https://etherscan.io/tx/0x829c108ac6ec904c71fa43dd81fc7d956d9371516b9c29d1ad8477ada3761bd0
> 
> if not, we need to understand why.

Then this should be tracked @ashachaf

**Comment by Velua** [comment]
> Yup, anywhere, all conversions go through the network contract and it fires these events.

So even if I went on Etherscan and opened up a Converter and manually put in a trade against it, that would still go to the network contract and emit an event?

**Comment by yudilevi** [comment]
You can't do a conversion through a converter, only through the network, so yeah.
There are a few (old) converters that were not upgraded that still allow it but I doubt anyone is actually doing it without going through the network.

**Comment by ashachaf** [comment]
@Velua better to check together as i believe few conversions were missing when i've checked.

**Comment by Velua** [comment]
Conversions now driven by API.
