### ISSUE TITLE
wrong network indication

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#222]
when user is using metamask on any network other than "mainnet", please include this warning message.
(relevant mostly for data as the page is blank when metamask is connected to ropsten)

https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f7d6f5e4d2dc806216e721e/

**Comment by pingustar** [comment]
@sirius651 is this something you can take of my hands. @ashachaf asked to get this implemented this week.

**Comment by sirius651** [comment]
@ashachaf  can you give me access to the link : https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f7d6f5e4d2dc806216e721e/

**Comment by pingustar** [comment]
![Uploading image.png…]()

**Comment by pingustar** [comment]
going with the quick and easy solution of replacing the blue top bar with the warning/error. Ropsten will show a warning, and unsupported networks will show an error.
