### ISSUE TITLE
Desktop - governance - not enough vBNT popup

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#225]
open gov interface
do not stake vBNT (connect new wallet if needed)
click vote 
actual: open metamask transaction with error (as i do not have the token to vote)
expected: 
open a popup indicating my vBNT balance is not sufficient and ask me to stake or add liquidity first.
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=548%3A773

**Comment by Velua** [comment]
@H34D to follow up

**Comment by H34D** [comment]
fixed
