### ISSUE TITLE
Allow embedding the swap widget on a 3rd party website

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#230]
The widget should allow configuring default tokens etc. so that 3rd parties can customize it with their own default tokens.
In addition, it should have a "closed" mode that only shows basic info like current price etc. that the user can expand to allow the full on version that supports swap / add/remove liquidity.

Requires a basic spec + design

**Comment by Velua** [comment]
@yudilevi is this still something we'd like to see one day?

**Comment by yudilevi** [comment]
Can’t tell about long term but we can close this one and add one if we do
in the future.
