### ISSUE TITLE
Discovering ROI

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#232]
When figuring out the APR I imagine ```removeLiquidityReturn``` is the way to go? changing the timestamp based on week, month etc? 

I'm currently hitting it with the following params with it returning with a generic error, any ideas? 

`[ "2", "1000000", "1607409130"]`

**Comment by Velua** [comment]
@ashachaf check this out on staging now, I'm still yet to do alchemy.

**Comment by Velua** [comment]
@ashachaf alchemy is done, are we still waiting on updates for ```poolROI``` calculation?

**Comment by yudilevi** [comment]
Yup, we're working on a new version of the contract, should be out in a few days.

**Comment by ashachaf** [comment]
@Velua i dont see this on staging.

**Comment by Velua** [comment]
@ashachaf Sent that two weeks ago, nothing to see atm.

**Comment by ashachaf** [comment]
@Velua is this task done? or was it covered in another place?

**Comment by Velua** [comment]
Done
