### ISSUE TITLE
Menu & Protection screens UI improvements

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#253]
Hi @Velua ,
Here are a few small UI fixes that aren't critical, but should be added at some point. 

**Tabs Menu** (screenshot attached): 

- [x] 1. Please align left logo with icons
- [x] 2. Active tab icon color isn’t correct, should be 0F59D1
- [x] 3.Bancor icon in “bancor wallet” tabs is smaller than other icons, should be same size
- [x] 4. Bancor logo at the top isn’t correct (icon is too big)

**Protection main screen:** (screenshot attached):

- [ ] 1. Blue filter triangle arrow should be attached to the title’s position
- [ ] 2. Please fix “stake" button width, should be 312 px

**Claim** (screenshot attached):

- [ ] 1. Timer alignment - please place it in one row. (also I don't think "h"/"m"/"s" indicators aren't relevant here, as it's clear enough as it is)

**Stake:**

- [ ] 1. Text color should be  6B7C93 (screenshot attached)

Thank you!

<img width="1015" alt="Screenshot at Oct 09 15-59-33" src="https://user-images.githubusercontent.com/69288176/95586592-91cdb500-0a49-11eb-9206-c165b7806d14.png">

<img width="943" alt="Screenshot at Oct 09 16-00-28" src="https://user-images.githubusercontent.com/69288176/95586607-97c39600-0a49-11eb-8e98-89e37041e1b6.png">

<img width="725" alt="stake" src="https://user-images.githubusercontent.com/69288176/95586570-8aa6a700-0a49-11eb-83e1-53ab067fa441.png">

<img width="1043" alt="Screenshot at Oct 09 16-05-15" src="https://user-images.githubusercontent.com/69288176/95586556-85495c80-0a49-11eb-9ea5-f668a1ac33f6.png">

**Comment by Ran73Cohen** [comment]
@ashachaf 
This is pretty old, I went over and with every issue its either the changes were made or the design is very different
The only thing I found that wasn't in staging was this

> 
> 
> Hi, in "stake" window please make the button which is not available (where is coming soon) grey D0D7DF (like all the rest inactive buttons). Thanks
> 
>     * [ ]  please make the button which is not available to be grey D0D7DF

It will look like this
![image](https://user-images.githubusercontent.com/51334627/105391252-9b5ae180-5c22-11eb-9b65-7a0dc48ae9c8.png)

Should we close this?
