### ISSUE TITLE
main protection page -  loading empty view for few sec

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#257]
when i load protection. screen,  the empty view shows up for few sec before my actual view shows up.

https://streamable.com/ar3dmi

**Comment by Velua** [comment]
In the last crazy updates I believe this loading indication has broken or can at least be improved. 

The app first learns of the position amount before the positions themselves. 

@pingustar 
Can we have these position components support a... loading prop? Which acts as a placeholder while the actual positions are being pulled. 
So first the page will be

Loading, then
Say 4 place holders there, illustrating to them 4 positions are inbound
Then finally these positions come and loading is stopped.

**Comment by Velua** [comment]
I'll work on delivering the position count as coming in and a loading getter if there isn't one there already. 
The previous racing condition is unlikely to be an issue now that the app waits for the API response before going through, so we'll already have all the pools known, this previously created some issues.

**Comment by pingustar** [comment]
@Velua sounds good. Will get started on this once my current task (rewards inside the protected table) is done.

**Comment by ashachaf** [comment]
option 1: 
IF wallet positions > 0, show a big loading animation until the data is ready to display
![loading animation-01 4](https://user-images.githubusercontent.com/40430285/105852642-64534a00-5fed-11eb-89e6-aff8a5c2e566.png)

option 2:
IF wallet positions > 0, show a protection page with place holders in the relevant places
mockup TBD

**Comment by pingustar** [comment]
added a simple loading animation until further details provided
