### ISSUE TITLE
swap->add liquidity - side menu disappears

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#277]
go to swap
add liquidity
at the end of the. proceess, th side menu is not highlighting that i am on "swap".

![image](https://user-images.githubusercontent.com/40430285/95711804-329bba80-0c6c-11eb-9ad3-6f819172db96.png)

**Comment by pingustar** [comment]
fixed active route styling and also clicking behaviour to bring you back to the main page.

**Comment by ashachaf** [comment]
nice!
