### ISSUE TITLE
Update countdown formatting

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#290]
## Current setup

![photo_2020-10-13_16-20-02](https://user-images.githubusercontent.com/8017434/95823043-4d575780-0d70-11eb-8e80-95fae3e7f2ba.jpg)

## Goal
"dd d, hh:mm:ss left until  full coverage"

**Comment by Velua** [comment]
Still open

**Comment by ashachaf** [comment]
closing as we cover this request in #426

**Comment by Velua** [comment]
Are we? I don't see the overlap with #426

**Comment by ashachaf** [comment]
check the part on cliff and how to display time left for full protection.

**Comment by pingustar** [comment]
@ashachaf is this still a request? Reopen if so.

Current design is based off of [this mockup](https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2) mentioned in #426
