### ISSUE TITLE
direct url to show supported whitelisted pools

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#293]
we would like to create. a url that display the list.
can be a very basic text list.
[pool, pool contract], 
for example: [ethbnt, 0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533],...

![image](https://user-images.githubusercontent.com/40430285/95838222-3140bf80-0d4a-11eb-954e-5343c10624f1.png)

**Comment by ashachaf** [comment]
URL can be:
https://bancor.network/eth/protection/whitelistedPools

**Comment by ashachaf** [comment]
update to this list:
we can expand it:
[pool symbol, pool token contract address, reserve symbol, reserve token contract address, available amount of single staking in reserve units, reserve symbol, reserve token contract address, available amount of single staking in reserve units]... [pool symbol, pool token contract address, reserve symbol, reserve token contract address, available amount of single staking in reserve units, reserve symbol, reserve token contract address, available amount of single staking in reserve units]

**Comment by Velua** [comment]
@ashachaf just put something into staging, should be able to find it [here](https://staging.swap.bancor.network/eth/protection/whitelistedPools) soon.

**Comment by Velua** [comment]
Single staking in reserve units is currently only pulled/figured out per pool when relevant in context. 

Will update so that in the event this page is navigated too it will perform the calculation in bulk.

**Comment by ashachaf** [comment]
@Velua i think we can close this issue at this stage.
