### ISSUE TITLE
loading animation

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#296]
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=582%3A0

**Comment by pingustar** [comment]
@Velua currently we are using the getter `vxm.ethBancor.loadingPools` which stops loading before the positions show up. Is there a way to add a getter that reflects the loading of the positions rather than the pools?

**Comment by Velua** [comment]
Not at the moment, was using pools because positions would usually resolve after the positions would. Will come up with a more accurate representation.

**Comment by ashachaf** [comment]
@Velua -  can you clarify the status of this?
was it dropped?

**Comment by Velua** [comment]
Still yet to be done.

**Comment by Velua** [comment]
This has completely changed given the API stuff, to do would be awaiting

- [ ] Protected positions loading
- [ ] Pools and tokens loading
- [ ] Pool APRs loading
