### ISSUE TITLE
Remove all liquidity for small numbers

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#3]
Balance needs to be in number format that the process can use. I’ve selected to liquidate my entire balance and got this value and error in metamask

<img width="458" alt="image" src="https://user-images.githubusercontent.com/7262066/89394965-0106f000-d70d-11ea-8319-7fd39302894a.png">

**Comment by pingustar** [comment]
I am able to reproduce this on add v2
![image](https://user-images.githubusercontent.com/7262066/89527042-fa4dab00-d7e8-11ea-9d72-7489375c4116.png)
@Velua can you help me out here and have a look please

**Comment by pingustar** [comment]
seems to be happening in swap as well.

![image](https://user-images.githubusercontent.com/7262066/89527993-91ffc900-d7ea-11ea-8df0-d74cc93913a3.png)

**Comment by pingustar** [comment]
and another weird one that I feel like it is related

![image](https://user-images.githubusercontent.com/7262066/89528840-05560a80-d7ec-11ea-9a67-cf4f38a38096.png)

**Comment by Velua** [comment]
> and another weird one that I feel like it is related
> 
> ![image](https://user-images.githubusercontent.com/7262066/89528840-05560a80-d7ec-11ea-9a67-cf4f38a38096.png)

Solved that recently, should not be an issue anymore.

**Comment by Velua** [comment]
So looks like balances are coming back as dec numbers, some numbers being so small they come back in this form, to ensure there's no loss I'll send back balances back as dec strings, it will still be up to the UI to make it pretty/format nice. Vuex/logic layer shouldn't be concerned with formatting. 

I've created a new branch ```balancetostring``` to deliver this.

**Comment by Velua** [comment]
@pingustar would you like to review the type changes and add any UI level changes required, then we'll merge.
