### ISSUE TITLE
Implement Sentry error reporting

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#317]
https://docs.sentry.io/platforms/javascript/guides/vue/?_ga=2.240938307.1548587100.1602747830-1799454226.1602747830&_gac=1.261767679.1602747830.CjwKCAjw5p_8BRBUEiwAPpJO67Bw6xj32mASTKHt2ASDs7AmIz8M3b-mo9P63dTfKthboQH5X5wVOhoCh1IQAvD_BwE

**Comment by Velua** [comment]
I've added Sentry to staging now, @ashachaf can we get the GitHub integration going?

**Comment by ashachaf** [comment]
github integration in place.
