### ISSUE TITLE
Data page mobile screen issues

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#320]
Bunch of issues there
![image](https://user-images.githubusercontent.com/1134236/96245855-7d8d3900-0fb0-11eb-8a9e-de8f2b63a674.png)

The pool column should be much narrower - if it can't accommodate a specific pool, it should be limited and use 3 dots to show the pool name is longer.

The liquidity column should be completely visible and the header should be changed to `Liquidity` on mobile only.

The numbers we show across the app should also be formatted in such a way that they show the correct precision based on the size of the number.
For example, no point showing cents for a 4+ digits number.

**Comment by ashachaf** [comment]
@pingustar - what is left in this task?

**Comment by pingustar** [comment]
- [ ] The pool column should be much narrower
- [ ] header should be changed to Liquidity on mobile only.
- [ ] show the correct precision based on the size of the USD amount


> .. it should be limited and use 3 dots to show the pool name is longer.

is adding 3 dots really a good idea? I made the column more narrow, lets see if that is sufficient.

> The liquidity column should be completely visible and the header should be changed to `Liquidity` on mobile only.

I dont think this is possible, especially with smaller phones and now that we have added the Protection Shield at the beginning it is even less space available.

> The numbers we show across the app should also be formatted in such a way that they show the correct precision based on the size of the number.
> For example, no point showing cents for a 4+ digits number.

**Comment by Velua** [comment]
@ashachaf can go over @pingustar 's feedback today if you like.

**Comment by ashachaf** [comment]
current solution works.
will add new task for quick navigation menu.
