### ISSUE TITLE
very small numbers cause like break in voting page

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#324]
we have display format we should follow.
if the number is >1,  2 decimals.
if the number is <1, 6 decimals

<img width="289" alt="Screenshot 2020-10-16 at 14 52 44" src="https://user-images.githubusercontent.com/13647606/96261859-42dfcc80-0fc1-11eb-8172-1196139f28de.png">

**Comment by Velua** [comment]
Still working on

**Comment by Velua** [comment]
@pingustar reviewing the token formatting with @ashachaf
