### ISSUE TITLE
Data - UI review

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#330]
Hi

- [x] Table - empty state text color - please change to 6B7C93

- [x] Table - empty state - please remove the line below the first row (in case it’s the last or the only one position - do not display the line below the row) 
<img width="802" alt="1" src="https://user-images.githubusercontent.com/69288176/96362507-7b54e700-1136-11eb-9082-a138f89ec77a.png">

- [x] Table - empty state - please let’s keep consistent spacing above and below the “empty state text” - 24 px. 
<img width="767" alt="3" src="https://user-images.githubusercontent.com/69288176/96362510-84de4f00-1136-11eb-8850-7f43ca8177a5.png">

- [ ] Search results - please change the color of the text to 0A2540 
<img width="405" alt="2" src="https://user-images.githubusercontent.com/69288176/96362516-932c6b00-1136-11eb-85d4-2c8aecc75968.png">

- [ ] Spacing on the right side - please make sure there is 16 px - between the last element in the row and between the edge of the card
<img width="110" alt="4" src="https://user-images.githubusercontent.com/69288176/96362524-9f182d00-1136-11eb-87cf-7ba3f3058ae4.png">

- [x] Please don’t display tabs in case there is no 2nd tab - let’s change its color to 0A2540 and remove the underline
<img width="432" alt="5" src="https://user-images.githubusercontent.com/69288176/96362528-a808fe80-1136-11eb-9700-6533196ecc24.png">

Mobile

- [ ] Please fix spacing inside “statistics” tab 

- [ ] Search bar is missing

- [ ] Cards in mobile version should be from the left edge of the screen to the right edge of the screen

<img width="1152" alt="15" src="https://user-images.githubusercontent.com/69288176/96362545-c2db7300-1136-11eb-927b-86f167398900.png">

Thanks!

**Comment by Ran73Cohen** [comment]
@ashachaf wanted to take it but it seems like changes were made
close?

**Comment by Velua** [comment]
Just compare this against the current mockups in Figma to confirm you're not making any out-dated changes.
