### ISSUE TITLE
Dark mode - UI review

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#331]
Hi, 

Here are a few general comments to the dark mode theme:

- [x] menu items on the top right - please match them dark mode theme. The example of dark mode is here: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f1d2dbfaf220c37fb5fa2b1/
![photo_2020-10-18 11 21 59](https://user-images.githubusercontent.com/69288176/96362856-2070bf00-1139-11eb-9354-bc701fed0ce8.jpeg)
 

- [x] please match text input fields in dark mode to dark mode theme (no white fields)

![photo_2020-10-18 12 03 37](https://user-images.githubusercontent.com/69288176/96362978-f966bd00-1139-11eb-9646-b6ba8addd290.jpeg)

- [x] please change accent blue color in dark mode to 156FFF

- [x] mobile menu - please change the line above the menu to 1F3A55
<img width="622" alt="23" src="https://user-images.githubusercontent.com/69288176/96362907-734a7680-1139-11eb-91ff-96f07edf7297.png">

Thanks

**Comment by Velua** [comment]
@Ran73Cohen make sure these issues are still present against the modern mockups we have before doing any work.
