### ISSUE TITLE
Voting page shows a scrollbar on it

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#334]
Happens on chrome desktop

![image](https://user-images.githubusercontent.com/1134236/96369071-7a38af80-1160-11eb-90e9-8570d2618a94.png)

**Comment by ashachaf** [comment]
@yudilevi is this still an issue?

**Comment by yudilevi** [comment]
no change was made as far as I can tell, so yes.

**Comment by H34D** [comment]
i will take a look at it

**Comment by H34D** [comment]
it must be a quirk in the deprecated data table implementation will migrate to the new component but this will take some time

**Comment by Velua** [comment]
@H34D let's discuss this one on the standup, we might have to re-do a component.

**Comment by H34D** [comment]
ok, will bench this for now

**Comment by H34D** [comment]
fixed with #677
