### ISSUE TITLE
Hardware wallets - allow selecting an address based on derivation path

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#341]
When using ledger for example, the app currently only allows using the first wallet in the derivation path.
It should allow users to choose which wallet to use.

**Comment by ashachaf** [comment]
we are using the onboard.js library.
https://www.blocknative.com/onboard

based on their demo, they support this functionality.

**Comment by ashachaf** [comment]
please update the code to support hardware wallets as indicated here:
https://docs.blocknative.com/onboard#wallet-check-modules

we should include this code in the page:
```walletCheck: [
  { checkName: 'derivationPath' },
  { checkName: 'connect' },
  { checkName: 'accounts' },
  { checkName: 'network' },
]```

**Comment by Velua** [comment]
Did we introduce a bug last time we tried this?

**Comment by ashachaf** [comment]
i'd like to try again.
this time test a bit more on known edge cases.

**Comment by ashachaf** [comment]
@Ran73Cohen can you have a look?
related to pr #1112
