### ISSUE TITLE
single token staking - update error messages

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#347]
TKN single staking:

current: 
Deposit breaches maximum liquidity
updated:
BNT cap reached. Protocol cannot mint additional BNTs at this stage. Additional BNT should be staked in order to allow {TokenSymbol} single side staking

**Comment by Velua** [comment]
Is that still the latest message? I've noticed the current message is

> BNT limit reached. Additional USDT liquidity should be staked to allow for BNT single-sided staking. Alternatively, provide dual-sided liquidity (BNT+USDT)

**Comment by pingustar** [comment]
fixed, and on staging for review.
