### ISSUE TITLE
Protection table - "Fully Protected Value" showing "NaN"

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#348]
![image](https://user-images.githubusercontent.com/53524917/96414078-4a87b700-11f5-11eb-93a3-65cecfab74c0.png)

**Comment by Velua** [comment]
@yudilevi who can we reach out too to check this out? Unable to replicate

**Comment by Velua** [comment]
@ashachaf do you see this or zeros on your end?

**Comment by ashachaf** [comment]
closing for now as we are unable to reproduce.
also, might be related to performance.
