### ISSUE TITLE
UI - Swap

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#35]
1. Tabs design  - tabs should be connected
2. Please remove separation line
3. Please fix input box design
4. Please change arrow/swap icons
5. Please change inactive button color/style

<img width="1182" alt="swap (1)" src="https://user-images.githubusercontent.com/69288176/89530671-92529100-d7f7-11ea-9298-3f011366d119.png">

**Comment by pingustar** [comment]
- [ ]     Tabs design - tabs should be connected
- [ ]     Please remove separation line
- [ ]     Please fix input box design
- [ ]     Please change arrow/swap icons
- [ ]     Please change inactive button color/style

**Comment by katyarozenfeld** [comment]
@pingustar Looks great

**Comment by ashachaf** [comment]
@pingustar i am checking staging and dont see any of these changes.

**Comment by pingustar** [comment]
What do you see?

**Comment by pingustar** [comment]
- [ ] add recipient @Velua  to provide logic

- [ ] USD value @pingustar

**Comment by pingustar** [comment]
@Ran73Cohen only task left here is:

- [ ] add USD value
