### ISSUE TITLE
dual side add liquidity - value you receive shows "NaN"

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#350]
in cases where the value of the pool token you are trying to stake for protection is very small in one of the reserves, the interface. shows "NaN".

current: small amounts show "NaN
updated: small amounts should be using the same number format we use on other balances.
indication should be: if amount is very small, show < 0.000001
for example: 0.00000001234 -> < 0.000001

![image](https://user-images.githubusercontent.com/40430285/96443699-b11ccd00-1215-11eb-8456-a61dc7c5494e.png)

**Comment by H34D** [comment]
fixed, deploying to staging
