### ISSUE TITLE
Transaction Error. Exception thrown in contract code. - trying to add single-sided JRT to JRT pool

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#354]
![image](https://user-images.githubusercontent.com/53524917/96447614-d52edd00-121a-11eb-95a1-5a435f0c43a6.png)

**Comment by yudilevi** [comment]
Fixed in the contract - @Velua can you also confirm on your end?

**Comment by Velua** [comment]
@yudilevi gas estimations are now a 10th of what they used to be.

**Comment by yudilevi** [comment]
Yup, that means it's good. Closing it then.
