### ISSUE TITLE
Liquidity limit reached message for TKN when there's actually lots of available room for it

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#359]
![image](https://user-images.githubusercontent.com/1134236/96501983-d6cbc580-1259-11eb-9773-11850ec6eb2e.png)

The USDT pool has plenty of liquidity that was provided by users, it should allow more than 200K of TKN to be deposited.

**Comment by Velua** [comment]
This no longer seems to be coming up since the formula update.
