### ISSUE TITLE
withdraw protected position - missing fully protected value

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#361]
fully protected value in the withdraw popup is missing and shows 0.

![image](https://user-images.githubusercontent.com/40430285/96546589-37d3b780-12b3-11eb-8ba7-045b3e36d7cc.png)

**Comment by Velua** [comment]
@ashachaf is this still a problem? Just failed to replicate on staging.

**Comment by ashachaf** [comment]
cannot reproduce.
