### ISSUE TITLE
withdraw stake position - insufficient vBNT balance error message

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#368]
when trying to withdraw a protected position (BNT positions only), we need to confirm that the user has sufficient vBNT balance.

vBNT balance needs to be equal to the BNT balance in the protected position.

current:
![image](https://user-images.githubusercontent.com/40430285/96583209-0bd12a00-12e5-11eb-9350-6623cbc642c1.png)

expected:
![image](https://user-images.githubusercontent.com/40430285/96583414-59e62d80-12e5-11eb-9f8f-329fda2e7a69.png)

**Comment by pingustar** [comment]
I tried moving over the logic from Withdraw Double Component.

I have hit a roadblock, the amount says undefined and error is always shown.

@Velua can you have a look at it please. Branch `fix/withdrawSingleVbntError` commit e17cf2a3a4b897ae51ffd51009410f82fa910d03

**Comment by Velua** [comment]
@pingustar would you like to see if that PR gets you out of trouble? Nurse it through to staging if so.

**Comment by pingustar** [comment]
thanks its fixed, its being deployed to staging now.

@ashachaf is it working correctly?

**Comment by pingustar** [comment]
done, deployed to production
