### ISSUE TITLE
UI - Transaction Settings Menu

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#37]
1. Please fix text colors
2. Slippage tolerance design - ready options + input design
3. Please fix dark/light mode toggle design
4. Blockchains filters - should be radiobuttons
5. Blockchains filter title should say "Blockchains Settings"

<img width="826" alt="transactions settings menu (2)" src="https://user-images.githubusercontent.com/69288176/89531148-6e437f80-d7f8-11ea-8171-e93a1942a63c.png">

**Comment by pingustar** [comment]
@katyarozenfeld I noticed you are using a version even before launch. Please use https://staging.swap.bancor.network going forward. Also something to keep in mind: the browser sometimes caches websites for hours/days, to get the most up to date verson make sure to use a private browser window.

**Comment by katyarozenfeld** [comment]
Great, thanks, will use a newer version.

**Comment by Velua** [comment]
@pingustar another stale one, please validate what we're doing with it and hand over to @Ran73Cohen if it makes sense.

**Comment by pingustar** [comment]
hading over to @Ran73Cohen
