### ISSUE TITLE
Unstake Button Text incorrect

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#373]
![image](https://user-images.githubusercontent.com/7262066/96622956-e820da80-130a-11eb-8cb4-42b23414e56e.png)

button text incorrect.

I have sufficient amount. Unstake works as expected so its just the text.

**Comment by H34D** [comment]
done

**Comment by ashachaf** [comment]
the input box still turns red to indicate an error while everything is fine.

input the number 7.
![image](https://user-images.githubusercontent.com/40430285/97855653-bdb81f80-1d03-11eb-9fb7-194a3b4d0c2d.png)
vs click the balance.
![image](https://user-images.githubusercontent.com/40430285/97855677-c7418780-1d03-11eb-9eed-fce0c506eae7.png)
