### ISSUE TITLE
Handling protected positions on a non-whitelisted pool

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#375]
The app is currently only displaying protected positions for pools that are whitelisted, in the case someone protects against a whitelisted pool, then the pool is then un-whitelisted for any reason how should the app respond to this? Or is this an event which won't happen?

**Comment by yudilevi** [comment]
removing a pool from the whitelist means there's something awfully wrong with the token and we'll probably need to handle it on a case by case basis.
the community will decide if/when it happens but from the frontend's perspective, it should probably just treat it similar to how it treats non whitelisted pools today, at least for now.
