### ISSUE TITLE
vBNT Logo not showing up

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#378]
<img width="551" alt="Screenshot 2020-10-21 at 11 09 40" src="https://user-images.githubusercontent.com/13647606/96698923-f532dd80-138d-11eb-9b1a-de151f65bc33.png">

the error message is vBNT.jpg:1 GET https://raw.githubusercontent.com/Velua/eth-tokens-registry/master/logos/vBNT.jpg 404 (Not Found)

the file is here: https://raw.githubusercontent.com/Velua/eth-tokens-registry/master/logos/vBNT.png

must be something with evaluating the filetype

**Comment by pingustar** [comment]
fixed.
