### ISSUE TITLE
token single side staking for protection - error message update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#379]
single side staking for protection error message update:

![image](https://user-images.githubusercontent.com/40430285/96699418-eb61a800-1396-11eb-903d-8676d84fad8e.png)

protection -> stake -> single side -> select token -> enter very large amount until you see this error.

current:
BNT limit reached. Additional BNT liquidity should be staked to allow for BNT single-sided staking. Alternatively, provide dual-sided liquidity (BNT+BNT)

updated:
{tokenSymbol} limit reached. Additional BNT liquidity should be staked to allow for {tokenSymbol} single-sided staking. Alternatively, provide dual-sided liquidity (BNT+{tokenSymbol})

**Comment by Velua** [comment]
Should this be continued in #347  ? 
Looks like a duplicate here.
