### ISSUE TITLE
Unstaked pool tokens from protection but they still appear on protection page

### ISSUE THREAD

**Issue by AdamOnChain** [bancorprotocol/webapp#383]
I unstaked CHERRYBNT and sold CHERRY for ETH, but CHERRYBNT still appears in the protection screen. 

![image](https://user-images.githubusercontent.com/39331256/96791418-197bd200-1401-11eb-8432-cff57056f6f7.png)

Same issue occurred when unstaking other pool tokens, such as BATBNT. 

Refreshing the page does not resolve the issue and liquidated pool tokens still linger in the protection screen.

**Comment by ashachaf** [comment]
user misunderstanding.
closing.
