### ISSUE TITLE
Changes to "Add Liquidity" Widget

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#385]
![image](https://user-images.githubusercontent.com/53524917/96837657-72725700-144f-11eb-9543-5c3e723518e9.png)

At top of widget change "Add Liquidity Protection" to "Add Single-Sided Liquidity"

this part was already changed ~~Change "Full coverage date" to "Coverage date" and show date 30 days from now instead of 100 days~~

**Comment by ashachaf** [comment]
@Ran73Cohen just changing the title of the popup when it is single side staking
