### ISSUE TITLE
Protection screen full coverage countdown

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#388]
Instead of "3 months left until full coverage" staying static for 3 months, let's do a countdown. 
eg. 87d 23h 4m 12s - where the seconds is constantly dropping

![image](https://user-images.githubusercontent.com/53524917/96838511-a8640b00-1450-11eb-9732-7a6cc460fb3c.png)

**Comment by yudilevi** [comment]
Maybe put the counter on the progress bar and write the protection % below it?

**Comment by Ran73Cohen** [comment]
already done
