### ISSUE TITLE
Move the sorted column arrow closer to the column name

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#390]
It looks like the table is sorted by fees and not by liquidity depth:

![image](https://user-images.githubusercontent.com/1134236/96849241-0c410080-145e-11eb-8703-e19309936931.png)

**Comment by Velua** [comment]
@pingustar Does this throw a spanner in the works given the ```b-table``` setup?

**Comment by pingustar** [comment]
@Velua yes, some more background info can be found here: #151

**Comment by pingustar** [comment]
new table component fixes this. Will be applied to all tables in the coming days. Closing this.
