### ISSUE TITLE
swap widget - conversion rates do not update fast enough and create invalid transaction

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#393]
go to swap
select any 2 tokens
click the 2 arrows to switch between the input/output direction twice fast.
expected: see the correct rate
actual: you now stuck on the rate of the opposite direction. this builds invalid transactions.

https://streamable.com/aafkzu

**Comment by yudilevi** [comment]
Should probably just reset it when clicking those arrows.
