### ISSUE TITLE
Default slippage tolerance (tested in incognito) is a custom 5%

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#394]
![image](https://user-images.githubusercontent.com/1134236/96884402-255fa680-148a-11eb-9b9f-134bd5ff7da5.png)

Should be set to the 0.5% option

**Comment by Ran73Cohen** [comment]
Fixed [here](https://github.com/bancorprotocol/webapp/commit/073687e69fec6a192f207cb5fdeda4b20b00dc6f)
