### ISSUE TITLE
protection table - add tool tip to APR title

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#398]
on the APR column in the protection table, please add tool tip. wiith this text:
Estimated annual rate of interest calculated based on activity. Each reserve might have different APR based on the accumulated fees and market trend

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=548%3A774

**Comment by pingustar** [comment]
updated apr tooltip

**Comment by pingustar** [comment]
merged
