### ISSUE TITLE
Data page search doesn't work on mobile

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#402]
No results returned:

![image](https://user-images.githubusercontent.com/1134236/97070372-72559100-15e0-11eb-9c33-9c39a1b4cc1f.png)

**Comment by Velua** [comment]
@yudilevi I imagine this is no longer the case?

**Comment by yudilevi** [comment]
Still the case.

**Comment by H34D** [comment]
it was not a bug on mobile, it was general bug with case sensitivity. Eth or ETH will lead to zero results on desktop as well. fixed
