### ISSUE TITLE
Data page occasionally shows completely off ETH price

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#403]
We've seen it in multiple occasions -

![image](https://user-images.githubusercontent.com/1134236/97070390-a466f300-15e0-11eb-9168-9a017828fa6b.png)

**Comment by Velua** [comment]
What number did you see when it was off?

**Comment by yudilevi** [comment]
ETH was around $414 when that screenshot was taken

**Comment by Velua** [comment]
Price is determined the same way the rest of the tokens are, which is slippageless cost of USD value of BNT. 
If we consider Binance to be "market price" then a discrepancy here should illustrate an arbitrage opportunity.

**Comment by Velua** [comment]
Discussion with Yudi, utilise CryptoCompare to sus out USD price of BNT **and** ETH.

**Comment by Velua** [comment]
- [ ] Sus out key requirement.

**Comment by Velua** [comment]
Now API sourced
