### ISSUE TITLE
unstake protected position - vBNT balance rounding issues

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#405]
it seems that when a user is trying to unstake protected position, we roundup the vBNT balance needs to have in order to proceed with the transaction and show "insufficient vBNT balance" error.

when checking vBNT balance, make sure you check the full number with no rounding against user balance (down to the last wei)

![image](https://user-images.githubusercontent.com/40430285/97100941-91682780-16a1-11eb-9877-1e035e23aa3a.png)

**Comment by Velua** [comment]
@ashachaf can see rounding wasn't quite right here. Now sorted.
