### ISSUE TITLE
stake vBNT tokens -  update balance display

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#406]
balance display should display 6 decimals as we use for balance indication on the swap interface.

![image](https://user-images.githubusercontent.com/40430285/97101220-38e65980-16a4-11eb-8537-417a355c1236.png)

**Comment by Velua** [comment]
![Screenshot at 2020-11-13 19:30:29](https://user-images.githubusercontent.com/8017434/99057104-0b2b6b00-25e7-11eb-94dd-0e8d1af3e289.png)

This is also reflective on unstake, I imagine it's just using the same component.

**Comment by pingustar** [comment]
fixed for both Stake and Unstake.
