### ISSUE TITLE
protection - add liquidity popup

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#407]
for the add liquidity popup, we have done the following:
1. updated the design and changed the order of the pool token and stake token
2. added indication of available single side staking.
this indication needs to display the available balance for single side staking in the given moment based on the limits calculations we have.
- when user change the staked token, this value should change to indicate the available balance in the selected token
- if for some reason, the calculated value is negative,  show 0

3. tool tip to "full coverage date"

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=624%3A239

**Comment by Velua** [comment]
@H34D Give this one a go, reach out if you need help.

**Comment by ashachaf** [comment]
another point on this:
- remove the alert message in the popup:
![image](https://user-images.githubusercontent.com/40430285/97155776-859e6300-177e-11eb-8459-802401515beb.png)
