### ISSUE TITLE
add liquidity protection - confirmation popup number rounding

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#408]
when a user stake tokens into protection, we should display the same number on the confirmation screen.

go to protection -> stake -> single side -> enter 9.999999 amount and click "stake"
current: confirmation popup shows 10.00000
expected: show the exact amount i am staking 9.999999 

![image](https://user-images.githubusercontent.com/40430285/97102720-81a40f80-16b0-11eb-90ea-d8a344136b5d.png)

**Comment by pingustar** [comment]
`prettifyNumber` function needs to be updated to round down (truncate)

@Ran73Cohen do you want to have a swing at that?
