### ISSUE TITLE
1y Fees/Liquidity isn't showing up on mobile

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#411]
Shows fine on desktop but on mobile the column is simply not there (waited for a while and still nothing).

**Comment by ashachaf** [comment]
when i disable metamask from my browser, we have lots of failed calls to infura and no APR data.

![image](https://user-images.githubusercontent.com/40430285/97113589-17ad5980-16f4-11eb-8e3c-6b32d0230ef0.png)

**Comment by Velua** [comment]
![Screenshot_2020-10-28-14-03-55-25.jpg](https://user-images.githubusercontent.com/8017434/97389685-aa353f00-1926-11eb-8804-998381c4f51f.jpg)

Looks alright on my mobile via staging. Can we confirm this is still a thing?

**Comment by yudilevi** [comment]
Yup, new columns look good on mobile as well.
