### ISSUE TITLE
Links to single-token staking in specific pools fail

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#416]
Examples:
1) https://app.bancor.network/eth/pool/0x8151E0Fbbc10Af5b0F16B413dB0747169e9687d9

2) https://app.bancor.network/eth/protection/stake/add/single/0x8151E0Fbbc10Af5b0F16B413dB0747169e9687d9

How do I link users to a specific pool for single-token staking? 

It is working for dual-sided liquidity. Example:
https://app.bancor.network/eth/pool/add/0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533

**Comment by ashachaf** [comment]
@nhindman23 
can you check this?
https://app.bancor.network/eth/protection/stake/add/single/0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533
same as link 2
