### ISSUE TITLE
Remove text from Add Liquidity Protection widget

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#417]
![image](https://user-images.githubusercontent.com/53524917/97149411-651ddb00-1775-11eb-9535-9e251aa7748f.png)

Remove: "If pool ratio is changed during the protection period - you’ll receive change value in BNT."
Remove: FULL COVERAGE DATE

**Comment by ashachaf** [comment]
we have task #407 on this popup.
@nhindman23 should we remove the "full coverage date"?

**Comment by ashachaf** [comment]
@pingustar please remove the "full coverage date"
![image](https://user-images.githubusercontent.com/40430285/97552020-6997fd00-19dc-11eb-9158-c01ac8de2d77.png)

**Comment by pingustar** [comment]
removed from single and double.
