### ISSUE TITLE
Add text so LPs know why they're "Joining a Pool"

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#418]
Add text:

By joining a pool, liquidity providers earn a percentage fee on all trades proportional to their share of the pool. Fees are added to the pool, accrue in real time and can be claimed by withdrawing your liquidity.

![image](https://user-images.githubusercontent.com/53524917/97150604-09545180-1777-11eb-85ee-58848f1be313.png)

**Comment by ashachaf** [comment]
@nhindman23 
do you want to add text on this screen?
clicking "join a pool" leads you to an intermediate screen with single or dual options to add liquidity.
maybe this text can fit there?
or maybe on the pool selection?
or maybe on the data page?

**Comment by nhindman23** [comment]
@ashachaf 
i think the text should go here above the "Join a Pool" button

it seems there is already a lot of text on the single or dual options screen but we can see how it looks

**Comment by ashachaf** [comment]
we would like to include a supporting text on both stake and add liquidity popup screens.
this supporting text should help people to better understand the benefits of adding liquidity into a pool.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=814%3A0
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=814%3A141

**Comment by pingustar** [comment]
info text added for both pages.
