### ISSUE TITLE
change tx link from bloks.io to eosx.io block explorer

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#42]
request from EOS Nation to change the block explorer from bloks.io to eosx.io

**Comment by Velua** [comment]
Let's update the response from transactions to give you more than a hash, instead of a string you'll get an object with 

```hash```, ```blockExplorerLink```, can discuss further on our next call.

**Comment by Velua** [comment]
Made the changes in that PR, do you wanna finish it off UI wise?
