### ISSUE TITLE
single side staking - indication of available limits intermediate popup

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#420]
related to task #407 

when staking liquidity using stake for protection interface we would like to add indications for the available single side staking.
1. protection -> stake ->
intermediate popup that allows single/dual staking

2. swap -> pool ->
intermediate popup that allows single/dual staking

3. data -> add liquidity ->
intermediate popup that allows single/dual staking

design update to indicate the "current available"
(do not change the text in the popups based on the design.)
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=664%3A3

**Comment by Velua** [comment]
@pingustar to discuss with @ashachaf

**Comment by Velua** [comment]
Me to  add the limits, ensure it's available from Vuex.
