### ISSUE TITLE
Update voting with BIP3 majority rule / quorum / whitelisting requirements

### ISSUE THREAD

**Issue by AdamOnChain** [bancorprotocol/webapp#422]
Update vote.bancor.network UI to reflect new majority and quorum rules passed in BIP3: https://gov.bancor.network/t/bip3-governance-changes-bip-documentation-requirements-and-new-majority-and-quorum-rules/97/2

**Majority Rule & Quorum**

![image](https://user-images.githubusercontent.com/39331256/97181983-982b9300-17a4-11eb-91fa-4c035cd1832c.png)

- Update so a standard BIP vote will show as PASSED if 66.7% majority achieved with a 20% quorum when voting closes.
- Add info bubble in vote window that says “Standard BIPs require a minimum two-thirds majority — defined as 66.7% — with a 20% quorum to pass.” 

**Whitelisting**

Make it so whitelisting proposals only show as PASSED if 66.7% majority and 40% quorum is achieved when voting closes.
![image](https://user-images.githubusercontent.com/39331256/97185810-2efa4e80-17a9-11eb-9837-26b2511795e8.png)

Consider creating separate buttons for initiating a "Whitelisting Proposal" and a "Governance Proposal" so these unique voting rules can be applied to each.

**Comment by ashachaf** [comment]
covered ini #455
