### ISSUE TITLE
formatting US dollar amounts

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#431]
The code 

     new Intl.NumberFormat("en-US", {
            style: "currency",
            currency: "USD"
          }).format(value)

Is starting to get repeated around the app.
 
Lets move this to a function called something like ```formatUSD``` accepting ```number | string``` and either using this behind it or numerals format feature.

**Comment by Velua** [comment]
@pingustar Does this make sense or do we already have a function for this that I'm missing?

**Comment by Velua** [comment]
@pingustar bump. 
@H34D you may be aware of one here too.

**Comment by pingustar** [comment]
@Velua 

we have an optional parameter for the `prettifyNumber` function. Second parameter is boolean defining USD yes or no. Default is false. It also strips decimals for large amounts.

`prettifyNumber(123456.98765, true)`

-> $123,456

`prettifyNumber(1.98765, true)`

-> $1.99

**Comment by Velua** [comment]
Alright, lets proceed with finding any 

```
 new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD"
      }).format(value)
```
and replacing with ```prettifyNumber``` for that consistency, whoever picks this up.

**Comment by pingustar** [comment]
on staging now.
