### ISSUE TITLE
data table - adding tool tips

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#440]
please add tool tips to the relevant columns:

- **Liquidity depth** - The value of tokens in the pool
- **Fee** - The % deducted from each swap and re-deposited into the pool
- **Fees** - The value of swap fees collected in the pool in the past 24h
- **1y fees** - 24h fees annualized divided by liquidity in the pool

**Comment by pingustar** [comment]
added tooltips.

We are running low on space, we have to many columns. How should we handle this @ashachaf
