### ISSUE TITLE
Wrong logos

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#447]
DAI logo is used for REN -
![image](https://user-images.githubusercontent.com/1134236/97453060-0ce60500-193e-11eb-8556-e0e7f0a065c8.png)

And for USDT -
![image](https://user-images.githubusercontent.com/1134236/97453086-12dbe600-193e-11eb-80ef-f93d3e055109.png)

**Comment by Velua** [comment]
Was able to replicate this on my end, couldn't after this update.
