### ISSUE TITLE
governance main view - text updates and list of voters

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#455]
1. vote tool tip - 
"According to <LINK>BIP3 </LINK>:
- Required quorum to pass proposals is 20% for standard BIPs & 40% for Token Whitelistings.
- A 2/3rd majority (66.7%) of votes is also required for all BIP approvals."

link to bip3 discussion: https://gov.bancor.network/t/bip3-governance-changes-bip-documentation-requirements-and-new-majority-and-quorum-rules/97/9

2. remove "20% to pass" indication
![image](https://user-images.githubusercontent.com/40430285/97540951-094d8f00-19cd-11eb-8b85-e5cb40aeb348.png)

3. new call to action button -> open a popup with list of wallets that voted.
- make sure in the popup, you can sort based on the different column titles
- preferred to have all rows in a single view (no pagination) with a scroll inside the popup view

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=779%3A1024
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=779%3A1504

**Comment by H34D** [comment]
> * Required quorum to pass proposals is 20% for standard BIPs & 40% for Token Whitelistings.

we need to change the contract to make this possible.

**Comment by H34D** [comment]
> * A 2/3rd majority (66.7%) of votes is also required for all BIP approvals."

this needs to be configured in the governance contract

**Comment by ashachaf** [comment]
@H34D 
this is the text for the tool tip, not a contract update request.
"According to BIP3 :
Required quorum to pass proposals is 20% for standard BIPs & 40% for Token Whitelistings.
A 2/3rd majority (66.7%) of votes is also required for all BIP approvals."

**Comment by H34D** [comment]
done
