### ISSUE TITLE
Bug | create pool in EOS

### ISSUE THREAD

**Issue by Kwaskoff** [bancorprotocol/webapp#459]
1. Choose EOS
2. Authorized by Scatter
3. Create a Pool
4. Can't find the token you're looking for? Add token
5. ERC20 address🤦‍♂️

![image](https://user-images.githubusercontent.com/15308024/97739992-a275c600-1af1-11eb-814d-1d314bbd520c.png)

**Comment by Velua** [comment]
@pingustar Can you add detection for the network if it's not on this component and have it navigate to https://github.com/eoscafe/eos-airdrops/ when trying to add a token on EOS.

**Comment by Velua** [comment]
Thanks for pointing this out @Kwaskoff 

If you would like to add a token on EOS please make a PR to https://github.com/eoscafe/eos-airdrops/ for now.

**Comment by Kwaskoff** [comment]
> Thanks for pointing this out @Kwaskoff
> 
> If you would like to add a token on EOS please make a PR to https://github.com/eoscafe/eos-airdrops/ for now.
Done
https://github.com/eoscafe/eos-airdrops/pull/263

**Comment by pingustar** [comment]
changed link behaviour for eos.
