### ISSUE TITLE
Compilation Error on yarn start

### ISSUE THREAD

**Issue by JhonnyJason** [bancorprotocol/webapp#460]
Hello, 

I was just checking out the code and tried to test it locally where I encountered following issue:

```
 ERROR  Failed to compile with 2 errors                                                                   11:30:16 AM

These relative modules were not found:

* ./abi in ./node_modules/eth-multicall/dist/index.js
* ./helpers in ./node_modules/eth-multicall/dist/index.js
ERROR in /home/lenny/gits/webapp/src/api/eth/contractTypes.ts(3,28):
3:28 Could not find a declaration file for module 'eth-multicall'. '/home/lenny/gits/webapp/node_modules/eth-multicall/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/eth-multicall` if it exists or add a new declaration (.d.ts) file containing `declare module 'eth-multicall';`
    1 | import { ContractSendMethod } from "web3-eth-contract";
    2 | import { ContractMethods } from "@/types/bancor.d.ts";
  > 3 | import { CallReturn } from "eth-multicall";
      |                            ^
    4 | import {
    5 |   ABIConverter,
    6 |   ABISmartToken,
```

Anyone having an Idea where `eth-multicall` should come from?

Cheers!

**Comment by Velua** [comment]
Hmm... is this the ```master``` or ```staging``` branch? The library should be available [here](https://www.npmjs.com/package/eth-multicall)

I'll review it's build output soon, do a ```yarn add eth-multicall``` just in case.

**Comment by JhonnyJason** [comment]
Thank you, for checking it out - It is the current master branch

**Comment by JhonnyJason** [comment]
Okay, the issue appears to be with eth-multicall I could not add it...
```
[lenny@nova webapp]$ yarn add eth-multicall
yarn add v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @firebase/analytics@0.4.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "@firebase/analytics > @firebase/installations@0.4.15" has unmet peer dependency "@firebase/app-types@0.x".
warning "@firebase/analytics > @firebase/installations > @firebase/installations-types@0.3.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "bnc-onboard > @toruslabs/torus-embed@1.8.3" has unmet peer dependency "@babel/runtime@7.x".
warning "bnc-onboard > @toruslabs/torus-embed > @toruslabs/fetch-node-details@2.3.0" has unmet peer dependency "@babel/runtime@7.x".
warning "bnc-onboard > @toruslabs/torus-embed > @toruslabs/http-helpers@1.3.4" has unmet peer dependency "@babel/runtime@7.x".
warning "bnc-onboard > @toruslabs/torus-embed > @toruslabs/torus.js@2.2.5" has unmet peer dependency "@babel/runtime@7.x".
warning "bnc-onboard > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime@7.11.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning "bootstrap-vue > bootstrap@4.5.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning "eos-transit-ledger-provider > webpack-cli@3.3.9" has unmet peer dependency "webpack@4.x.x".
warning " > vue-chartjs-typescript@3.3.3" has incorrect peer dependency "chart.js@2.7.x".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > ts-jest@26.3.0" has unmet peer dependency "jest@>=26 <27".
[4/4] Building fresh packages...
[-/20] ��� waiting...
[14/20] ��� node-sass
[13/20] ��� deasync
[15/20] ��� eth-multicall
error /home/lenny/gits/webapp/node_modules/eth-multicall: Command failed.
Exit code: 127
Command: tsc
Arguments: 



```

**Comment by Velua** [comment]
Cheers, can recognise a fault here. Sorting it out shortly.

**Comment by Velua** [comment]
@JhonnyJason can you give that a crack now? Just updated the package. Try another pull of this repo then ```yarn``` again perhaps.

**Comment by JhonnyJason** [comment]
@Velua Super awesome, that fixed the eth-multicall Problem ;-)

Now I can basicly complile and test the webapp - thank you very much!

However there are still some "confusing" things about the compilation - as there appears to be errors - also without telling me the specific line where it occurs^^

```
Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Parsing error: Cannot read property 'map' of undefined at src/api/eos/eosBancorCalc.ts:



1 error found.

Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Parsing error: Cannot read property 'map' of undefined at src/api/eth/knownConverterVersions.ts:



1 error found.

Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Parsing error: Cannot read property 'map' of undefined at src/api/helpers.ts:



1 error found.

Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/network/index.ts:



1 error found.

Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/swap/eosBancor.ts:



1 error found.

Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/swap/ethBancor.ts:



1 error found.

Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/swap/index.ts:



1 error found.

Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
warning: Parsing error: Expression expected (prettier/prettier) at src/store/modules/network/eosNetwork.ts:217:28:
  215 |     if (!this.isAuthenticated) throw new Error("Not logged in.");
  216 | 
> 217 |     if (!params || params?.tokens?.length == 0) {
      |                            ^
  218 |       const tokensToFetch = this.balances;
  219 | 
  220 |       const fetchedTokens = await this.fetchBulkBalances(tokensToFetch);


1 warning found.

You may use special comments to disable some warnings.

```

For now I would just ignore it and close the issue

**Comment by Velua** [comment]
> @Velua Super awesome, that fixed the eth-multicall Problem ;-)
> 
> Now I can basicly complile and test the webapp - thank you very much!
> 
> However there are still some "confusing" things about the compilation - as there appears to be errors - also without telling me the specific line where it occurs^^
> 
> ```
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> error: Parsing error: Cannot read property 'map' of undefined at src/api/eos/eosBancorCalc.ts:
> 
> 
> 
> 1 error found.
> 
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> error: Parsing error: Cannot read property 'map' of undefined at src/api/eth/knownConverterVersions.ts:
> 
> 
> 
> 1 error found.
> 
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> error: Parsing error: Cannot read property 'map' of undefined at src/api/helpers.ts:
> 
> 
> 
> 1 error found.
> 
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/network/index.ts:
> 
> 
> 
> 1 error found.
> 
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/swap/eosBancor.ts:
> 
> 
> 
> 1 error found.
> 
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/swap/ethBancor.ts:
> 
> 
> 
> 1 error found.
> 
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> error: Parsing error: Cannot read property 'map' of undefined at src/store/modules/swap/index.ts:
> 
> 
> 
> 1 error found.
> 
> Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> warning: Parsing error: Expression expected (prettier/prettier) at src/store/modules/network/eosNetwork.ts:217:28:
>   215 |     if (!this.isAuthenticated) throw new Error("Not logged in.");
>   216 | 
> > 217 |     if (!params || params?.tokens?.length == 0) {
>       |                            ^
>   218 |       const tokensToFetch = this.balances;
>   219 | 
>   220 |       const fetchedTokens = await this.fetchBulkBalances(tokensToFetch);
> 
> 
> 1 warning found.
> 
> You may use special comments to disable some warnings.
> ```
> 
> For now I would just ignore it and close the issue

Yeah cheers, some weird and wacky things raised for no immediately obvious reason. Will review soon.
Thanks!

**Comment by JhonnyJason** [comment]
Cool, as it works now it's not a priority anyway ;-) Cheers!
