### ISSUE TITLE
Refreshing the swap page results in seeing the same token as the source/target

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#462]
I selected LRC as the source token and BNT as the target token, then refreshed.

This is what I saw next -

![image](https://user-images.githubusercontent.com/1134236/97806648-75e2bb00-1c65-11eb-8d62-06afc186154b.png)

While the URL seems to be the correct one -
https://app.bancor.network/eth/swap?from=0xBBbbCA6A901c926F240b89EacB641d8Aec7AEafD&to=0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c

I did it multiple times and it was consistent.

**Comment by Velua** [comment]
@pingustar Will the view layer still select based on params?

**Comment by pingustar** [comment]
I have updated the routing for the swap and fixed a few edge cases.

Should work now. Closing this.
