### ISSUE TITLE
input field should only accept valid number format

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#47]
please restrict the input fields to accept valid number format.

![image](https://user-images.githubusercontent.com/40430285/89620925-1f99f200-d899-11ea-8db0-3b08d5dd3766.png)

**Comment by pingustar** [comment]
@ashachaf this should work now. This is just a workaround for now until John and I have reworked the calculations to match all the same type. It is working now I think but needs some further polishing.
