### ISSUE TITLE
prevent insecure content

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#478]
when creating a new voting proposal, we save all the information on ipfs.
the ipfs request can be hiject and used to plant malicious links.
when we display the proposal, we need to verify the links are using the correct domain and if not, disable hyper links.

check out proposal 20 on staging+ropsten for reference..

discussion forum link: check, if the URL starts with "https://gov.bancor.network/" set it as hyperlink. otherwise, disable the hyperlink.

github link: check, if the URL starts with "https://github.com/" set it as hyperlink. otherwise, disable the hyperlink.

![image](https://user-images.githubusercontent.com/40430285/97990395-853e4180-1de8-11eb-9b72-828f71ce0c8e.png)

**Comment by ashachaf** [comment]
@H34D 
is it possible to disable the link?
currently it seems to open the vote interface on a new tab.

**Comment by Velua** [comment]
@H34D I'm not over this process well, can you give me and the team a run down on how this works in our next standup, the threat that @ashachaf has raised and what we're doing/done to patch this?

**Comment by H34D** [comment]
fixed
