### ISSUE TITLE
approve 0 if there is previous approve

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#48]
when building a transaction, you need to check if there is previous approve.

if existing approve > conversion amount, trigger only the convert transaction.
else, if approve = 0, trigger 
1. approve for amount
2. convert for amount
else, meaning previous approve is >0 but smaller than amount, trigger
1. set approve to 0
2. set approve amount.
3. convert amount

**Comment by Velua** [comment]
This is the expected logic, is this not what you're experiencing?

**Comment by ashachaf** [comment]
cannot reproduce.
