### ISSUE TITLE
prevent "stake to protect" if price deviation is too high

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#480]
When a user stakes for protection, we check the pool spot price vs average price.

If the price deviation is greater than the defined value, we will not allow it to proceed on the contract level.
this is designed to protect the user and system from price manipulation.

we need to address this on the frontend and stop the user from sending the transaction to the blockchain with the relevant explanation.

Process:
1. protection -> stake -> single side staking
2. calculation flow
on the pool converter:
- calculate the average rate
  - call function recentAverageRate() with the (reserve token address) the user is staking for protection
  - response include 2 values, numerator and denominator
   - average rate = numerator/denominator
- calculate pool spot rate
  - user's protected reserve will be indicated as "primary reserve"
  - spot rate = secondary reserve balance / primary reserve balance
on liquidity protection contract
- identify what is the allowed max deviation
  - call function AverageRateMaxDeviation()
  - response is percentage in ppm. meaning, if the result is 10000 -> 1%
check if the transaction can be executed:

**IF**
`(1000000 - AverageRateMaxDeviation) / 1000000 < avg / spot < 1000000 / (1000000 - AverageRateMaxDeviation)`
 
proceed normally.
**Else**, 
display warning to user and prevent from proceeding as the transaction will fail on the blockchain.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=872%3A5

**Comment by Velua** [comment]
```recentAverageRate``` is found on the latest converters by the looks of it, @ashachaf do we know what version ```recentAverageRate``` was introduced? 

- [ ] Update ```buildV28ConverterContract``` to include this method. 
- [ ] Find where to place this call, I'm guessing it will be the one the UI calls when the user is hanging around that area. 
- [ ] Depending on what the UI expects, should the ```Else``` condition as described Asaf occur, throw with that message or return with the ```error``` prop.

**Comment by Velua** [comment]
Make sure we don't end up calling this method for versions < than whatever this was introduced in.

**Comment by H34D** [comment]
ABI updated, its very different but i have tested it. The rest works and also i can get recentAverageRate

**Comment by ashachaf** [comment]
version 42.

**Comment by ashachaf** [comment]
example using ropsten data:
https://ropsten.etherscan.io/address/0xe289d3bdcfd3a9c6d08428c8bf213988370eb738#readContract
BNT reserve address: 0xf35ccfbce1228014f66809edafcdb836bfe388f5
xxx reserve address: 0x34748f3e5cddbbb7c2a7bec888fef3873a462de7

call function for BNT
[ recentAverageRate method Response ]
    uint256 :  1852751787227484151863
    uint256 :  2102158801567418598785
average rate = 1852751787227484151863/2102158801567418598785

on the same pool contract, call "reserves" function with each reserve address
bnt: 2102158801567418598785
xxx: 1852751787227484151863
spot rate = 1852751787227484151863/2102158801567418598785 = 

(1000000 - AverageRateMaxDeviation) / 1000000 < avg / spot < 1000000 / (1000000 - AverageRateMaxDeviation) 
with data:
(1000000 - 5000) / 1000000 < 0.88135672045 / 0.88135672045 < 1000000 / (1000000 - 5000) =
0.995 <1 <1.005 -> true, no error is needed.

**Comment by ashachaf** [comment]
did a large swap.
checking the numbers agains.

example using ropsten data:
https://ropsten.etherscan.io/address/0xe289d3bdcfd3a9c6d08428c8bf213988370eb738#readContract
BNT reserve address: 0xf35ccfbce1228014f66809edafcdb836bfe388f5
xxx reserve address: 0x34748f3e5cddbbb7c2a7bec888fef3873a462de7

call function for BNT
[ recentAverageRate method Response ]
uint256 : 667846830199023568299961991561
uint256 : 332153169800976431700038008439
average rate = 667846830199023568299961991561/332153169800976431700038008439 = 2.01065921063

on the same pool contract, call "reserves" function with each reserve address
bnt: 1372226728883507693672
xxx: 2853115261857163894625
spot rate = 2853115261857163894625/1372226728883507693672 = 2.07918647976

(1000000 - AverageRateMaxDeviation) / 1000000 < avg / spot < 1000000 / (1000000 - AverageRateMaxDeviation)
with data:
(1000000 - 5000) / 1000000 < 2.01065921063 / 2.07918647976 < 1000000 / (1000000 - 5000) =
0.995 < 0.96704130687 <1.005 -> false, error for high deviation

**Comment by H34D** [comment]
done
