### ISSUE TITLE
Adapt mobile design on vote page

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#481]
<img width="224" alt="Screenshot 2020-11-05 at 12 43 13" src="https://user-images.githubusercontent.com/13647606/98237006-86947900-1f64-11eb-95ba-420481d9c14f.png">
<img width="238" alt="Screenshot 2020-11-05 at 12 43 09" src="https://user-images.githubusercontent.com/13647606/98237014-885e3c80-1f64-11eb-859b-7ca0db54a57f.png">

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=76%3A0

**Comment by sirius651** [comment]
@H34D I can't find the vote graph on the mobile page. Is this the issue?

**Comment by H34D** [comment]
in figma there is a mobile design where the table splits into two rows once the viewport is too small

**Comment by H34D** [comment]
fixed with #677
