### ISSUE TITLE
token balance refresh and update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#486]
swap bnt->ocean
navigate to pool -> join a pool -> ocean/bnt -> single side staking -> ocean
expected: see my new balance without refreshing the page.

![image](https://user-images.githubusercontent.com/40430285/98516833-b221a700-2275-11eb-89e0-4bbc8fb4b6de.png)
after refresh:
![image](https://user-images.githubusercontent.com/40430285/98516914-cfef0c00-2275-11eb-9ac0-1700c3b4abad.png)

**Comment by Velua** [comment]
Saw a bug where balances were being fetched but failing to get set. 
Conversions and add liquidity protection will now trigger multiple balance fetches over several seconds to make sure the latest is received.
