### ISSUE TITLE
data table update columns to include protected APR

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#492]
in our efforts to show protected APR, we would like to update the data table and include 2 new columns.
protected apr
unprotected apr
~~removing "fees" column as all pools should have the same fee setup (as of bip 4).~~

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1072%3A0

tool tips: (@nhindman23 )
- protected apr
- unprotected apr

**Comment by Velua** [comment]
Let's discuss this one @ashachaf

**Comment by ashachaf** [comment]
please note, we would like to keep the "fee" column.

**Comment by Velua** [comment]
What is Protected APR and Unprotected APR and how do we calculate that? 

Is @nhindman23 going to post the tooltips then?

**Comment by ashachaf** [comment]
protected APR (we will calculate it based on 7days)
https://docs.google.com/document/d/1sE1AMPD7wfz1_kgb3jxEabNOUheTB2TfG1VCdid7teo/edit#heading=h.70bpehp3em80
(we have already done this for the data table and hide it, average of both reserves)

unprotected APR:
1. calculate the worth of pool token in primary and secondary reserve token today
2. calculate the worth of pool token in primary and secondary reserve token today-7days
3. take average {(primary value 1/primary value2 -1)*100*52} and {(secondary value 1/secondary value2 -1)*100*52}

how to calculate pool token to reserve amount?
pool token amount * ((primary reserve balance at the time of check)/(pool token supply at the time of check)) = primary reserve amount that is worth the pool token you are checking.

**Comment by ashachaf** [comment]
tool tips:
protected APR: 7d fees/liquidity annualized with Bancor’s impermanent loss protection
unprotected APR: 7d fees/liquidity annualized without Bancor’s impermanent loss protection

**Comment by ashachaf** [comment]
related to #558

**Comment by ashachaf** [comment]
this task is on hold for now

**Comment by ashachaf** [comment]
doing other design updates to the table.
will revisit when relevant.
