### ISSUE TITLE
Funky tooltip behaviour

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#497]
In this video - https://streamable.com/51q0y1

We can see that when I mouse over the tooltip for the other item comes up instead, I've seen this happen when there isn't a unique key set per tooltip component.

**Comment by pingustar** [comment]
This is most likley because the table is restricting the space to display the tooltips. I had a similar problems on another project with dropdowns inside a table.

Looking into it.

**Comment by pingustar** [comment]
Only solution I was able to find is adding a `minHeight` to the table. Not the best but will fix this issue.

What do you think about that @Velua ?

**Comment by Velua** [comment]
Is this really the issue then? 
It's definitely not occurring due to a duplicate ID being used for the tooltip or anything?

**Comment by pingustar** [comment]
Yes I am pretty sure about it.

`:id="'popover-cliff-' + item.id"` is how the ID is set. And the funky behaviour seems to only happens if there are just a few positions in the table. I'll test this out and we'll see.

I'll ping you for review.

**Comment by pingustar** [comment]
fixed by adding min-height and display block css to the table.

**Comment by pingustar** [comment]
reopening this as I just noticed that the implemented fix messes with the table

![image](https://user-images.githubusercontent.com/7262066/100607308-12eb4f00-330b-11eb-8bac-f7bc973dbdba.png)

**Comment by ashachaf** [comment]
@pingustar 
i am unable to reproduce. please close if not needed.
