### ISSUE TITLE
Change wallet library

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#5]
Change wallet library

**Comment by Velua** [comment]
Our current motivations for changing from the current one are supporting more wallets? And perhaps one that allows us to style a bit easier. 

Is there a particular wallet we want to support? @yudilevi

**Comment by yudilevi** [comment]
https://github.com/ashachaf ?

**Comment by zhangzhongnan928** [comment]
You should allow users to inject web3 from whatever wallet, instead of limiting users with a wallet list. Checkout how uniswap works.

**Comment by ashachaf** [comment]
this wallet library is the most extensive and active at the moment.
https://github.com/NoahZinsmeister/web3-react

**Comment by yudilevi** [comment]
@ashachaf it's a react component while the app is a vue app

**Comment by Velua** [comment]
> You should allow users to inject web3 from whatever wallet, instead of limiting users with a wallet list. Checkout how uniswap works.

![Screenshot at 2020-08-18 14:33:41](https://user-images.githubusercontent.com/8017434/90470822-d3d02e00-e15f-11ea-95fc-995a86be0886.png)

@zhangzhongnan928 How does this inject web3 option work? I see a wallet list on Uniswap?

**Comment by zhangzhongnan928** [comment]
> > You should allow users to inject web3 from whatever wallet, instead of limiting users with a wallet list. Checkout how uniswap works.
> 
> ![Screenshot at 2020-08-18 14:33:41](https://user-images.githubusercontent.com/8017434/90470822-d3d02e00-e15f-11ea-95fc-995a86be0886.png)
> 
> @zhangzhongnan928 How does this inject web3 option work? I see a wallet list on Uniswap?

@Velua 
The difference is, Uniswap inject first, not asking you to choose a provider first. That makes Uniswap works with any named or unnamed web3 browser. 

swap.bancor.network ask you to choose a provider first. That makes bancor only works with the listed providers. 

Try it in Imtoken or AlphaWallet, you will get what I mean.
![IMG_4318](https://user-images.githubusercontent.com/33795543/90472318-8f469180-e163-11ea-8566-4bb74819d2b1.jpg)

**Comment by Velua** [comment]
Yeah that turns my world upside down, that makes sense, cheers @zhangzhongnan928

**Comment by Velua** [comment]
@ashachaf Like Yudi said that's for React, we could look into https://github.com/web3modal/web3modal  but I imagine we should take on @zhangzhongnan928 's recommendation of first querying/accepting any injected Web3 wallet before forcing the user to authenticate with some pre-defined list of wallets we're supporting.

**Comment by ashachaf** [comment]
yes. if you can identify the user's wallet that would be the best option.

**Comment by Velua** [comment]
Closing as we'll migrate to React
