### ISSUE TITLE
UI rounding errors generate the wrong transactions

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#50]
When adding liquidity, the UI might round balances up which in turn generates a transaction that will revert.
Balances should generally be rounded down for input/output.

**Comment by Velua** [comment]
From @yudilevi 
approval was for: 11405184306090230000000
amount in wallet: 11405184306090229330019

**Comment by Velua** [comment]
Confirmed balance fetcher can drop remaining decimals before reaching UI layer
E.g. ```11405.184306090229330019``` converted into a number becomes ```11405.18430609023```

Creating new branch ```rounding``` to remove all cases where balances are stored in numbers and preferring strings instead.

**Comment by Velua** [comment]
Mocked my account having the same balance of ```11405184306090229330019```, confirmed it was available and displayed on the UI level, then confirmed the same number hit Web3 for transaction processing.
