### ISSUE TITLE
Report removeLiquidityReturn failures to sentry

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#501]
Not sure this is the case but since the contract has to deal with a very wide range of values/precisions in the various calculations, we want to know if users experience failures due to overflows/underflows.
So it's critical that we can track these kind of issues in case there's an issue in the contract.

**Comment by Velua** [comment]
Are we still looking out for this? We're essentially sending all errors to Sentry atm.

**Comment by pingustar** [comment]
all errors are tracked by sentry, closing this and reference can be found in EPIC Sentry Issue #999 .
