### ISSUE TITLE
1year fee / liquidity data pull update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#502]
in order to calculate the 1y fees/liquidity correctly, we need to make sure we follow this process:

current (incorrect flow):
- calculate 24h volume from BancorNetwork
- multiply the above with current fee on the pool
this is incorrect as when the fee is changed in the pool, it will also change the "history" as we calculate it.

updated flow:
- pull all conversion events from the pool converter contract
- sum them up to calculate volume (optional)
- sum fee events to calculate 24h fees
use this value.

**Comment by Velua** [comment]
So we do want to add another 30+ requests for all conversion events for all whitelisted pools on the initial page load?

**Comment by yudilevi** [comment]
I would only do that per page but I imagine this is also a pretty significant overhead.
This will soon move to an API call but until then - how much overhead are we talking about here?

**Comment by Velua** [comment]
I can further investigate how flexible the alchemy API is, perhaps it would support pulling from several contract sources so we don't have to do a individual request for every whitelisted converter there is. 

However, if we did, we could possibly get all the liquidity events that go along with it, render that on the home page too. 

How much time do we want to commit to this if we're also working on having the server track it? And knowing that this flaw is only exposed to pools who've changed their fees less than 24 hours ago.

**Comment by ashachaf** [comment]
duplicated with #522

**Comment by Velua** [comment]
This issue outlines the current approach and a suggested solution, can't just end it's discussion and jump the gun onto a solution from nowhere. 

When and who decided this was the best approach? Was it discussed and approved by a dev team member?

I can't tell the difference between the original request on this post compared to #522 has. Was @H34D aware of this context and this discussion?

**Comment by Velua** [comment]
And in the case of duplicates this one being older should be regarded as the parent, #522 as the child, therefore #522 closed instead of this one.

**Comment by Velua** [comment]
@ashachaf We're ready to accommodate hardcoded historical pool fees.

**Comment by Velua** [comment]
@ashachaf we're now set at 1% fees for trades before block number ```11248429```

**Comment by Velua** [comment]
Given @H34D has already made his work in #522 I'll conclude this one now we've implemented the hardcoded pool fees and consider #522 as the long term solution.
