### ISSUE TITLE
when creating a transaction - use higher gas settings for the user

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#503]
currently, when we build a transaction it defaults to "slow" gas price settings on metamask. this can cause transactions to take 10+ min to. execute.
we should aim to set it for medium at least as a default value.

how to get the gas price from web3:
web3.eth.getGasPrice

what value to pass to metamask:
Medium - getGasPrice ÷ 2

**Comment by Velua** [comment]
I can see [getGasPrice](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getgasprice), but what is ```Medium - getGacePrice ÷ 2```?

Where is ```Medium``` coming from? Where's the 2 number come from?

**Comment by ashachaf** [comment]
please use this default value when creating a transaction.
1. it seems that getGasPrice returns the "standard" speed cost.
2. we've noticed that standard speed tend to be 5+. min long
3. for this, we would like to suggest a higher gas price for the user/transaction.

gasPrice value = getGasPrice*1.3
(indicating 30% increase on "standard" speed)
