### ISSUE TITLE
stake for protection error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#504]
following a protection contract update (might be the reason)
stake for protection:
1. approve
2. stake for protect. this is what i see. extremely high transaction
![image](https://user-images.githubusercontent.com/40430285/98693335-d4501d80-2378-11eb-8aa6-ac07c2daf67e.png)
3. reject
4. stake again -> now the transaction is fine.

**Comment by pingustar** [comment]
I was not able to reproducing this. 

Do we have more info? Does it happen always?

**Comment by ashachaf** [comment]
@pingustar it might happen when we upgrade the protection contract.
can it be that there is some cache on this address?
how can you check this?

refresh tends to solve this issue.

**Comment by pingustar** [comment]
no idea about the cache.

@Velua @H34D any idea?

**Comment by Velua** [comment]
No caching, there's always the chance of a different config after a page refresh though not sure why. 
One would have to re-produce the error to get a better idea.

**Comment by pingustar** [comment]
I am closing this for now. Please reopen if issue persists @ashachaf
