### ISSUE TITLE
n/a indication in data and protection tables

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#509]
we have reports of n/a and NaN indication on both data and protection tables.
we are trying to debug this and would like to better understand what might be the process that UI follow to show these values.

data table - what values are triggering n/a (or what flows are not supported and result in this value)
protection table - what triggers NaN value

![image](https://user-images.githubusercontent.com/40430285/98781255-baf1b480-23fe-11eb-9930-b7545925dbf4.png)
![image](https://user-images.githubusercontent.com/40430285/98781293-c5ac4980-23fe-11eb-8f78-986bf8e7d412.png)

**Comment by ashachaf** [comment]
on staging+mainnet
![image](https://user-images.githubusercontent.com/40430285/98784854-63564780-2404-11eb-845a-e12d56314c9b.png)

**Comment by ashachaf** [comment]
on production
![image](https://user-images.githubusercontent.com/40430285/98785025-a6b0b600-2404-11eb-980e-6843b5d38ac3.png)

**Comment by Velua** [comment]
Deploying hotfix to prod now

**Comment by ashachaf** [comment]
staging+mainnet

![image](https://user-images.githubusercontent.com/40430285/98791969-78d06f00-240e-11eb-9d59-4be09a155964.png)

![image](https://user-images.githubusercontent.com/40430285/98792002-838b0400-240e-11eb-9a99-b8c77a6fb811.png)
![image](https://user-images.githubusercontent.com/40430285/98792026-8be33f00-240e-11eb-9922-6dbef4a605b8.png)

**Comment by Velua** [comment]
You're seeing those $0 and N/A on prod? I don't care about the staging status for now

**Comment by Velua** [comment]
I'm an idiot, ignore my last comment. 

Hotfix now sent to staging, will be reflective in the staging build soon.

**Comment by ashachaf** [comment]
production+mainnet
![image](https://user-images.githubusercontent.com/40430285/98910050-53ee0180-24cb-11eb-9e1a-9037cb9bda61.png)

**Comment by H34D** [comment]
fixed it was caused by request limits on alchemy: #523
