### ISSUE TITLE
Give Infura the pillow

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#512]
Infura has failed us. 

Kill all reference and dependencies on it's service and go all in on Alchemy. 

[Status page](https://status.infura.io/) for Infura for reference

**Comment by H34D** [comment]
done, killed where ever i can kill it. Still metamask uses underneath but we can strangle this out to only use it for transactions and not loading of data

**Comment by Velua** [comment]
I don't think we have to go that far, if Infura is used by MetaMask then that's fine. Just wanted to get rid of our dependency on it, only so much we can do if users wallets are using certain endpoints. Infura is expected to be operational now.
