### ISSUE TITLE
Hung load on production

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#513]
## Problem
Experiencing a hung load or really long load time on production

#512 was recently requested as Infura is experiencing outages, possible dependency on the API causing this fault.

**Comment by Velua** [comment]
I'm expecting these two to resolve the issue when building has finished. 

@H34D after your efforts to re-sync ```staging``` and ```master``` can you ensure these two branches / PR's are included?
I wanna go home.

**Comment by Velua** [comment]
Now using Alchemy for all requests and this is working OK.

Remaining issue seems to be positions failing to get fetched or calculated therefore not being presented on the screen. 
Please investigate, top priority.

**Comment by H34D** [comment]
should be done #515
