### ISSUE TITLE
External menu links are disfunctional

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#520]
<img width="214" alt="Screenshot 2020-11-11 at 16 22 54" src="https://user-images.githubusercontent.com/13647606/98830019-33299b80-243a-11eb-9408-a9d5e6930743.png">

When clicking on governance or bancor x nothing happens

**Comment by yudilevi** [comment]
Once the governance item is clicked, other menu items also stop functioning

**Comment by pingustar** [comment]
fixed, deploying to staging now.
