### ISSUE TITLE
Log response size exceeded. Please reduce query block range.

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#523]
When fetching logs with `eth_getLogs` and the amount of data is too big alchemy will return `Log response size exceeded. Please reduce query block range.`

Url: https://eth-mainnet.alchemyapi.io/v2/_gHhOgCqAFaa8f35R1PeHmpHx1E-zVcN 

Request:
```json
{
    "jsonrpc":"2.0",
    "method":"eth_getLogs",
    "params": [{
          "fromBlock":"0xab7149",
          "toBlock":"latest",
          "address":"0x2F9EC37d6CcFFf1caB21733BdaDEdE11c823cCB0"
    }],
    "id":1
}
```

**Comment by H34D** [comment]
They have hard limits on blocks:

```
We actually have an eth_getLogs limit in place for requests up to a 2k block range or any block range with a cap of 10k logs in the response (https://docs.alchemyapi.io/documentation/alchemy-api-reference/json-rpc#eth_getlogs).  So it looks like your request is from block 0xab7671=11236977 to latest which was ~11242937 around the time you sent off the request. This is a difference of 5,960 blocks, which is why you're seeing that error response
```

**Comment by H34D** [comment]
we should try batching request in 2k blocks batches @Velua

**Comment by Velua** [comment]
Yeah that's annoying, will have to chunk in block sizes of 2,000, given we want about 6,000 ish then we'll need 3 concurrent requests, think our limit is 30 API key wide. 

We'll be able to make this smoother with any failures going in as retries on an Observable.

**Comment by Velua** [comment]
Now pulling from API, this is redundant.
