### ISSUE TITLE
When removing single sided BNT liquidity, add vBNT approval

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#524]
We are changing the token permission system and the protection contract will not be able to burn vBNT anymore without specific permissions.
This means that when removing vBNT, the frontend needs to also generate an approve tx for it, based on the staked BNT amount in that specific position.

**Comment by Velua** [comment]
So new strategy is when removing a protection position against the **liquidity protection** contract, check to see if the position was made against the network token **BNT** if so, trigger an approval against the **vBNT** token contract allowing the same ** liquidity protection** contract to act as spender, for the amount of the position with adjustments based on the % the user has specified they'd like to remove.

**Comment by Velua** [comment]
Now pushing to prod in #543

**Comment by ashachaf** [comment]
@Velua can we close this one?
