### ISSUE TITLE
withdraw popup text update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#525]
on the withdraw popup, please update the following texts (and logic on how to display them):

1. warning text (orange text).
- check, IF user withdraw BNT position:
current text:
**Important**
You still haven’t reached full coverage. There is a risk for impermanent loss.
updated text:
**Important**
You still haven’t reached full protection. There is a risk for impermanent loss and you might receive less than your original stake amount as a result.
- check, IF user withdraw TKN position:
current text:
**Important**
You still haven’t reached full coverage. There is a risk for impermanent loss.
updated text:
**Important**
You still haven’t reached full protection. There is a risk for impermanent loss and you might receive less than your original stake amount as a result.

2. new gray text
IF withdraw BNT: BNT withdrawals are subject to a 24h lock period before they can be claimed
IF withdraw TKN and breakdown includes BNT: Part of your output is in BNT.  This amount will be locked for 24h before it can be claimed
IF withdraw TNN and breakdown DOES NOT include BNT: no text.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1044%3A858

**Comment by pingustar** [comment]
updated text. On staging for review @ashachaf
