### ISSUE TITLE
Protected Table - Fees column

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#531]
- [x] update formula
- [x] add formula test
- [x] add fee to getter `protectedLiquidity` in `ethBancor` / find out why its not displayed
- [x] investigate calculated value for correctness and edge cases (decimal precision)
- [x] update table design to accommodate new column "Fees" - table width to little with current design

### Formula

Sqrt((opposingDepositedReserveCurrentBalance / depositedReserveCurrentBalance) / reserveRate) * depositedReserveCurrentBalance / currentPoolTokenSupply * originalPoolTokenAmount - depositedAmount

**Calculation Example:**
Sqrt((6847120160277936759163837 / 10932903826342227802656) / 290.61911993101308091657) * 10932903826342227802656 / 11338379267323634752139485 * 1370909146698872748 - 3874264344838181
= -1933747839780032 wei  (-0.0019337478 units in reserveToken)

(parent issue for reference: #426)

**Comment by ashachaf** [comment]
@pingustar 
is this task stuck waiting for more information?

**Comment by pingustar** [comment]
I will pick this up again today.

**Comment by pingustar** [comment]
@ashachaf with the tested positions, I always get a negative value. I have multiplied the result by `-1` now and added the fee column to staging. Can you have a look and check if the numbers make sense?

**Comment by Velua** [comment]
Ensure a test is written for the formula.

**Comment by pingustar** [comment]
@Velua there is a test available, this is also mentioned in the issue as a checkbox in the top.

@ashachaf do we have more info how to proceed from here?

**Comment by ashachaf** [comment]
checking the calculation again with the mathematician, seems we need to rework it.
will update once we have the new calculation

**Comment by ashachaf** [comment]
current calculation:
Sqrt((opposingDepositedReserveCurrentBalance / depositedReserveCurrentBalance) / reserveRate) * depositedReserveCurrentBalance / currentPoolTokenSupply * originalPoolTokenAmount - depositedAmount

updated calculation:
Sqrt((opposingDepositedReserveCurrentBalance/depositedReserveCurrentBalance)/ reserveRate) * depositedReserveCurrentBalance / currentPoolTokenSupply * 2*originalPoolTokenAmount - depositedAmount


sample data:
id: 1
currentPoolTokenSupply: "15576682305422710575136560"
depositedAmount: "1340922988163890"
depositedReserveCurrentBalance: "15225916667665690655887"
opposingDepositedReserveCurrentBalance: "9337353089824759522590240"
originalPoolTokenAmount: "500000000000000000"
reserveRate: "322.22513507007347536179"

calculating using old formula:
Sqrt((9337353089824759522590240 / 15225916667665690655887) / 322.22513507007347536179) * 15225916667665690655887 / 15576682305422710575136560 * 500000000000000000 - 1340922988163890 = -6.666761e+14

calculating using updated formula:
Sqrt((9337353089824759522590240/15225916667665690655887)/ 322.22513507007347536179) * 15225916667665690655887 / 15576682305422710575136560 * 2*500000000000000000 - 1340922988163890 = 7.5707859e+12

if the value is smaller than 0, set fees to 0.

**Comment by pingustar** [comment]
I have updated the formula, going to staging now. please have a look @ashachaf

**Comment by ashachaf** [comment]
@pingustar looks right.

**Comment by pingustar** [comment]
what should we do about the horizontal scroll issue?

@ashachaf I noticed that this position has 0 TKN in fees, is that correct?

![image](https://user-images.githubusercontent.com/7262066/100996838-d8c3bc80-3559-11eb-8cba-8bbdaf32043f.png)

**Comment by ashachaf** [comment]
after yet another call with our mathematical advisor, we realized that decimals of the token were not part of the calculation.

## updated calculation:
`Sqrt((opposingDepositedReserveCurrentBalance/depositedReserveCurrentBalance)/ reserveRate*10**(opposingDepositReserveDecimals-depositedReserveDecimals)) * depositedReserveCurrentBalance / currentPoolTokenSupply * 2*originalPoolTokenAmount - depositedAmount`

### example:
#### initial protected position data:
user wallet:  0x82A9825ebd642A88385F122Be7a8BCB64C828c22
pool token: 0x5365B5BC56493F08A38E5Eb08E36cBbe6fcC8306
reserve token: 0xdAC17F958D2ee523a2206206994597C13D831ec7
pool token amount :  7760448251583
reserve token amount :  98480254
numerator :  999999999999072987219066747471
denominator :  927012780933252529
timestamp :  1603281239

#### current data:
pool token supply: 789263641772319924
pool token decimals: 18
bnt reserve: 5,174,192.476790071639531461
bnt decimals: 18
usdt reserve: 5,362,069.303210
usdt decimals: 6

#### calculation using the example numbers: (user deposit was made in USDT)
`Sqrt((5174192476790071639531461/5362069303210)/ reserveRate*10**(18-6)) * 5362069303210 / 789263641772319924 * 2*7760448251583 - 98480254`

**Comment by Velua** [comment]
What's the result of 
> Sqrt((5174192476790071639531461/5362069303210)/ reserveRate*10**(18-6)) * 5362069303210 / 789263641772319924 * 2*38764610763779 - 494997687 

on your end? We'll include this in the written tests.

**Comment by ashachaf** [comment]
@Velua i've updated the calculation above.

**Comment by pingustar** [comment]
I think this can be closed. Please reopen if further work required.
