### ISSUE TITLE
Less or no concurrent requests for positions

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#533]
Currently in ```ethBancor.ts```  on lines...

      const ids = await contract.methods.protectedLiquidityIds(owner).call();
      const allPositions = await Promise.all(
        ids.map(id => protectionById(liquidityStore, id, this.currentNetwork))
      );

We are fetching all positions concurrently, this isn't a big deal with 2 or 3 positions but anyone with 10 in either main-net or ropsten can blow API limit...

> Failed fetching protection positions Returned error: Your app has exceeded its concurrent requests capacity.  If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemyapi.io/documentation/rate-limits. Feel free to ask further questions in the community discord channel: https://discord.com/invite/A39JVCM. Have a great day! 

Lets refactor by using the ```eth-multicall``` library to help so we can get the bulk of these in one single request.

------- 
In the event of needing a quicker fix could potentially use [mapLimit](https://blend.github.io/promise-utils/latest/index.html#maplimit) but this is a last resort given it will slow down the time it takes to finally get all positions.

**Comment by Velua** [comment]
@H34D I feel like this would be a good exercise for you as you might have to create a "shape" for it unless I've already done so somewhere. 

Feel free to suggest something better than "shape" too, schema might be better...

**Comment by ashachaf** [comment]
this might be causing users not to see their positions on production.
this is how i see my protection table on staging+ropsten.
![image](https://user-images.githubusercontent.com/40430285/99250918-2976ae00-2815-11eb-8969-e8754f55e23a.png)

**Comment by Velua** [comment]
@H34D let's up priority on this. Do what you can in the remaining time you have. Leave me even a drafted PR to pick up from if you dont finish.

**Comment by Velua** [comment]
I have now added a ```eth-multicall``` based solution so more efficient on requests.
