### ISSUE TITLE
Perform base tests

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#534]
Given the recent updates it's not entirely certain how reliable testing **Ropsten** is on the app at the moment. 

Please attempt 
- [x] Swap from one token to another.
- [x] Creating a protection position. 

Advise @yudilevi upon completion.

**Comment by yudilevi** [comment]
The app doesn't seem to show any pools in the main data page for me

**Comment by yudilevi** [comment]
potentially the alchemy whitelist

**Comment by sirius651** [comment]
It seems working well in my side. 
And also I need adding this ip `115.144.128.216 `, which is static public ip for whitelisting

**Comment by Velua** [comment]
IP address now added.

**Comment by Velua** [comment]
@yudilevi Passing tests on our end, re-open if you're experiencing issues after confirming you're whitelisted.
