### ISSUE TITLE
Create issues template

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#536]
Issue templates will be helpful for getting relevant information for the team to take on and action

**Comment by Velua** [comment]
I'm currently awaiting further permissions on the repo to configure this. 

@sirius651 @pingustar @H34D lets discuss.

**Comment by sirius651** [comment]
There was time when I contributed to `status-react`, and it looked useful for suggesting issue.
[https://github.com/status-im/status-react/issues/new/choose](https://github.com/status-im/status-react/issues/new/choose)

# Problem

An overview of the background required to understand the problem.
A problem description.

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by Velua** [comment]
This example looks nice, lets add it now and modify is we want something changed or polished off.

**Comment by pingustar** [comment]
I guess this can be closed?
