### ISSUE TITLE
Define release cycle

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#537]
Our current release cycle / strategy is ambiguous. 

-------
From @H34D
Define and implement a release process. This can be a release cycle (every x days staging gets deployed to prod) or a continuous deployment (requires feature specific environments) strategy.
Decision to make: Which release process to use? Once this is decided we can define steps to reach the goal.
1.  Use release cycle based deployment strategy (testing is harder, more risky because of potential big packages being deployed)
1. Use continuous deployment strategy (requirements have to be really on point, need very good tooling and code quality to not deploy rubbish to production)
-----

**Comment by Velua** [comment]
I like the idea of release cycles as they can let us define a release time say on a Wednesday where we can carry extensive tests prior to launching to production. 

What would the ```git``` workflow look like in continuous deployment? Would we still have ```staging``` or spin up mini ```staging``` branches before deploying straight to ```master``` @H34D

**Comment by sirius651** [comment]
1. Branch off of `dev` branch.
2. Once `feature` branch is ready for testing, open a PR into the `staging` branch and merge it. That will trigger an automated build and you will be able to test your changes in Staging environment like (http://staging.bancor.network)
3. Once we’re ready to deploy, someone who is responsible for deployment will open a PR from `dev` into `master` and will approve it to trigger an automated build and deployment.
4. The release version should be managed with tags and versions (eg:  v1.0.1). Referred from [https://github.com/marketplace/actions/create-a-release](https://github.com/marketplace/actions/create-a-release). So stakeholders can figure out what’s going on in current.

I don't know if it's a good scenario for this, but just sketch for idea

**Comment by pingustar** [comment]
I also like the idea of release cycles. Specially as the team grows and more commits/changes are made. With defined days for releases, each dev can make sure that their changes are solid and ready for production.

With continuous deployment we have more flexibility but also a higher risk of deploying code that hasnt passed testing/review.

The release cycles can be fairly short. So we dont accumulate to many changes. I think something like Mondays and Thursdays for example.

**Comment by Velua** [comment]
I feel like there's a fair few on-chain interactions that need to be tested to confidently declare the app fit for service. Given the state of the development environment and lack of ease in running a local chain we don't have the luxury of running these tests quickly. Therefore I feel like be too much overhead in a continuous deployment environment. 

Monday and Thursday releases sound pretty good, then we can spend the extra time testing conversions, fetching of X, Y, Z and checking every functionality manually before putting it out in the wild.
