### ISSUE TITLE
Rename isAuthenticated variable

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#538]
The variable ```isAuthenticated``` has to be one of the most popularly used however traditionally **"is"** in variable names is a ```boolean``` whereas this variable is either a ```string``` or ```false```. 

Rename to something more fitting and easier to understand to new devs.

**Comment by Velua** [comment]
Current proposal is ```currentUser```

**Comment by pingustar** [comment]
@H34D suggested to create a base class that gets extended by all or required classes.

We could add `darkMode` and `isAuthenticated` ?!

**Comment by Velua** [comment]
> @H34D suggested to create a base class that gets extended by all or required classes.
> 
> We could add `darkMode` and `isAuthenticated` ?!

Out of scope for this issue, make a new one if @H34D hasn't already made one with this suggestion. Thought I saw a PR for it. 

We'll lock in ```currentUser``` then. 

This issue can remain open till we've made this change. 
@sirius651 Wanna have a crack?

**Comment by sirius651** [comment]
> > @H34D suggested to create a base class that gets extended by all or required classes.
> > We could add `darkMode` and `isAuthenticated` ?!
> 
> Out of scope for this issue, make a new one if @H34D hasn't already made one with this suggestion. Thought I saw a PR for it.
> 
> We'll lock in `currentUser` then.
> 
> This issue can remain open till we've made this change.
> @sirius651 Wanna have a crack?

Sure, let me see
