### ISSUE TITLE
add liquidity popup text updated

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#540]
protection->stake->dual sided stake and protect -> eth/bnt
when opening the add liquidity popou in this flow, we should update the "warning" text.
current:
If pool ratio will be changed during protection period - you’ll receive change value in BNT.

updated: remove the entire text with its box.

![image](https://user-images.githubusercontent.com/40430285/99179953-d0325000-272a-11eb-985b-165d9b8c805b.png)

**Comment by pingustar** [comment]
PR merged and deploying to production now.

I have made a small adjustment @sirius651 

the margin between input field and button is to small. I have added a margin to fix this.

![image](https://user-images.githubusercontent.com/7262066/99258842-70ff3900-2819-11eb-9991-d34b62c0bb08.png)
