### ISSUE TITLE
"back" functionality on stake liquidity flow

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#546]
when a user opens the "stake liquidity" from the data screen, we should allow going back to the data screen.

current:
https://streamable.com/33wwsb

updated:
IF user clicked "stake" from the data screen AND then clicked "back" on the "add liquidity" popup -> open the data page.
(if this is too difficult, we can consider solving it with a new link, which will require design, that will allow the user to go back to data screen)

**Comment by pingustar** [comment]
I have updated the routing to go back to the previous page. This should now work for all pages independant from what page you are on.
