### ISSUE TITLE
space available limit calculation

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#547]
we are about to increase the limits and also create a tier system in place.

limits increase - need to confirm you are using the value from the contract and not hard coded amount.
maxSystemNetworkTokenAmount

tier system -
tokens that are part of the top tier, would be exempt from the maxSystemNetworkTokenRatio check.

how to identify if a token is in a tier:
in the PROTECTION (not STORE) contract,
function isHighTierPool(IConverterAnchor _poolAnchor) public view returns (bool) {

IF the pool is in the top tier, 

update this part in the calculation:

// select the smaller of the two allowed BNTs
  IF (isHighTierPool(IConverterAnchor _poolAnchor)) = true, const lowestAmount = maxLimitBnt;
  ELSE, const lowestAmount = Decimal.min(maxLimitBnt, maxRatioBnt);

this is the only place i can find this calculation in the code:
https://github.com/bancorprotocol/webapp/blob/c41a1e0be64968521c3156708c7c9c864772e74d/src/api/helpers.ts

**Comment by Velua** [comment]
@yudilevi Is this method in the contracts code? Can't seem to find it, wanted to compile in order to generate the latest ABI.

**Comment by Velua** [comment]
I'm guessing this contract change is not in production, when do we expect this to happen? Almost midnight my time and 2:30pm for the Germans so running out of work hours.

**Comment by yudilevi** [comment]
@Velua it's in a branch -
https://github.com/bancorprotocol/contracts-solidity/blob/f8b2376f5a7a82e4723f70547102caf7952a55fd/solidity/contracts/liquidity-protection/LiquidityProtection.sol#L448

Gonna be merged in the next hour.

**Comment by Velua** [comment]
Handing over to @H34D 

From what I can tell my PR is 95% of the work, the only remaining tasks are..

- [ ] Update the ABI to reflect the interfaces of the new liquidity protection contract. Sourced from [here](https://github.com/bancorprotocol/webapp/issues/547#issuecomment-728009719)
- [ ] In line... ```contract.methods.isHighTierPool(anchor).call();``` I've made an assumption that a boolean will come back, this may not be the case, ```console.log``` it or whatever and check, it could be ```"0"``` or ```"1"``` or something so double check this.

**Comment by Velua** [comment]
From Telegram, we're expecting this to be in prod in the next hour. 

Either perform an update of the app containing this work at the same time as the contract push. 
**Else**, write a bit more code where should the request of ```contract.methods.isHighTierPool(anchor).call();``` fail (which is will given it doesn't exist on the contract yet) just catch it and return ```false```, that way the app will be ready and waiting for the contract change. However, will come at the cost of a few failed requests at the mean time.

**Comment by H34D** [comment]
i changed the logic of fetching slightly because the call will fail if the contract does not support the new property, it is a little bit more passive now
