### ISSUE TITLE
Menu in Responsive view has some strange background

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#552]
There is some strange background when in responsive view. See red circle:

<img width="1008" alt="Screenshot 2020-11-16 at 15 49 24" src="https://user-images.githubusercontent.com/13647606/99266745-6649a180-2823-11eb-9311-13dea254a11c.png">
<img width="626" alt="Screenshot 2020-11-16 at 15 42 36" src="https://user-images.githubusercontent.com/13647606/99266749-68136500-2823-11eb-8124-0fe6dd2ea884.png">

**Comment by pingustar** [comment]
seems to be darkmode and desktop browser related. Cannot reproduce on mobile device or light mode.

**Comment by pingustar** [comment]
![image](https://user-images.githubusercontent.com/7262066/101519880-fe9af800-3983-11eb-8cad-ca2fec75c3cf.png)

darkmode is missing the rounded corner now.

**Comment by sirius651** [comment]
> ![image](https://user-images.githubusercontent.com/7262066/101519880-fe9af800-3983-11eb-8cad-ca2fec75c3cf.png)
> 
> darkmode is missing the rounded corner now.

The issue is because css in `SideBarBottom.vue` is not scoped, which is being affected to `SideBarLeft.vue` . Fixed commit is include `fix/timer-css-578-new`
