### ISSUE TITLE
ERR_INVALID_RATE on poolRoi breaks Display of Protected Positions

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#555]
In some time cases the function poolRoi returns: ERR_INVALID_RATE which will lead to an empty list of positions:

<img width="708" alt="Screenshot 2020-11-16 at 21 08 09" src="https://user-images.githubusercontent.com/13647606/99302678-fc93bc80-284f-11eb-86d4-63ea07173abf.png">

steps to reproduce:

address: "0x00f4104195c36FA48e423296D937bAa65eE06E90"
poolRateD: "131089916167290465531"
poolRateN: "3860859610665021812520"
poolToken: "0x1aCE5DD13Ba14CA42695A905526f2ec366720b13"
reserveAmount: "5000000000000000000"
reserveRateD: "1930429805332510906260"
reserveRateN: "57895063028114469806"
reserveToken: "0xF35cCfbcE1228014F66809EDaFCDB836BFE388f5"

on ropsten

https://ropsten.etherscan.io/address/0x00f4104195c36FA48e423296D937bAa65eE06E90#readContract

<img width="728" alt="Screenshot 2020-11-16 at 21 05 16" src="https://user-images.githubusercontent.com/13647606/99302727-0f0df600-2850-11eb-8a85-1453606437ce.png">

**Comment by yudilevi** [comment]
this might actually be a contract issue. it happens when the deviation between the spot rate and the recent average rate in the pool exceeds the max deviation that the protection allows.
we should probably handle that check in write functions only and allow read only functions to skip that check

**Comment by yudilevi** [comment]
yeah, we'll fix it in the contract level - it's a temporary state that should get sorted out after a few mins but in this case N/A should be good enough until we fix it.

**Comment by H34D** [comment]
temporary solved with: https://github.com/bancorprotocol/webapp/commit/723a4efcbc85209eb21c7db324c673fec576ecaf

**Comment by H34D** [comment]
now showing calculation errors

<img width="1168" alt="Screenshot 2020-11-19 at 16 57 49" src="https://user-images.githubusercontent.com/13647606/99690935-f2a8ce00-2a88-11eb-818c-66279eec4c5f.png">

**Comment by H34D** [comment]
fixed

**Comment by pingustar** [comment]
> yeah, we'll fix it in the contract level - it's a temporary state that should get sorted out after a few mins but in this case N/A should be good enough until we fix it.

any update on this? Another priority issue about this has been rased: #602

**Comment by pingustar** [comment]
I think this can be closed.
