### ISSUE TITLE
data table - add indication of liquidity mining rewards APR

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#558]
for these pools:
- Large Cap
ETH/BNT, WBTC/BNT, USDT/BNT, USDC/BNT, DAI/BNT, LINK/BNT
weekly rewards. are planned to be 100,000-200,000 bnt

- Mid Cap
OCEAN/BNT, renBTC/BNT
weekly rewards. are planned to be 10,000-20,000 bnt

how to calculate the APR from rewards:
1. identify how much protected positions exist in a pool for a given token or BNT
on the protection store contract, execute this function:
totalProtectedReserveAmount(pool token, reserve token)
result is the total protected amount in the reserve token (in wei).

2. 
IF LARGE CAP:
- IF BNT: (70000000000000000000000*52/total protected BNT in the pool)*100 
- IF TKN: (30000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100

IF SMALL CAP:
- IF BNT: (7000000000000000000000*52/total protected BNT in the pool)*100 
- IF TKN: (3000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100

tool tip:
Estimated APR based on weekly BNT Liquidity Mining rewards (pending governance vote). Counter indicates time until 12-week rewards cycle concludes. [Learn more](https://blog.bancor.network/announcing-bnt-liquidity-mining-b30be90a008d)
(if we can add url, good. otherwise, remove the "learn more" part)

column title - when clicking the title, sort all pools with rewards first based on liquidity depth

mockup
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1080%3A708

**Comment by pingustar** [comment]
What does the countdown reflect?

And the font size of 7px is pretty small - we should increase that. We shouldnt go below 12 maybe 10 in some cases.

![image](https://user-images.githubusercontent.com/7262066/99376250-fbe93d80-28c4-11eb-9c6a-dddd224eaed4.png)

**Comment by ashachaf** [comment]
updated the. counter text to 10.

**Comment by ashachaf** [comment]
counter - indicates the time left until the liquidity mining plan is over for these pools
until the contract is done, this should be counting downwards towards this time:

start time (novermber 16 2020 00:00GMT)
end time february 8 2021. 23:59 GMT

**Comment by H34D** [comment]
from what i understand: we need to query the totalProtectedReserveAmount for the TKN and BNT for each pool. Right now we have 280 pool which would make it an additional sum of approx 560 rpc calls additionally. This will make the application way slower again

is this correct or can we exclude some pools beforehand? @ashachaf

**Comment by ashachaf** [comment]
to reduce the call, you can only check. for the pools that are in. the arrey returned from this function.
contract: liquidityProtection
https://etherscan.io/address/0x135742E6C5d70FC960090EdDBd9f3C6D0D494E99#readContract
function: highTierPools
return: array of pool anchors

https://github.com/bancorprotocol/contracts-solidity/blob/99e2db2a7378cef7a2844d98f1f681af5d50ccee/solidity/contracts/liquidity-protection/LiquidityProtection.sol#L438

**Comment by pingustar** [comment]
@ashachaf as requested a data dump of the current Liq Mining Aprs: 

```
[
  {
    "poolId": "0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "3388925920355454041207471",
        "reward": 0.00010740866237696372
      },
      {
        "symbol": "ETH",
        "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
        "amount": "11223687693254390671019",
        "reward": 8.688784317895e-8
      }
    ]
  },
  {
    "poolId": "0x5365B5BC56493F08A38E5Eb08E36cBbe6fcC8306",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "227164257436069786721787",
        "reward": 0.001602364756270865
      },
      {
        "symbol": "USDT",
        "address": "0xdac17f958d2ee523a2206206994597c13d831ec7",
        "amount": "572970792307",
        "reward": 6.1229e-16
      }
    ]
  },
  {
    "poolId": "0xE5Df055773Bf9710053923599504831c7DBdD697",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "64430055314674460082076",
        "reward": 0.005649537288494242
      },
      {
        "symbol": "DAI",
        "address": "0x6b175474e89094c44da98b954eedeac495271d0f",
        "amount": "341384944833913037549455",
        "reward": 0.0021848837307749135
      }
    ]
  },
  {
    "poolId": "0x874d8dE5b26c9D9f6aA8d7bab283F9A9c6f777f4",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "248521538070152800962926",
        "reward": 0.00146466178676735
      },
      {
        "symbol": "USDC",
        "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
        "amount": "528428065894",
        "reward": 5.6524e-16
      }
    ]
  },
  {
    "poolId": "0x04D0231162b4784b706908c787CE32bD075db9b7",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "839105269522782128858718",
        "reward": 0.0004337953928081216
      },
      {
        "symbol": "LINK",
        "address": "0x514910771af9ca656af840dff83e8264ecf986ca",
        "amount": "154071666439574645182775",
        "reward": 0.00001295093782718285
      }
    ]
  },
  {
    "poolId": "0xCDfF066eDf8a770E9b6A7aE12F7CFD3DbA0011B5",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "1358421399445960022427488"
      },
      {
        "symbol": "OCEAN",
        "address": "0x967da4048cD07aB37855c090aAF366e4ce1b9F48",
        "amount": "4040139764676935300143764"
      }
    ]
  },
  {
    "poolId": "0xb479b102bF135bdC666d6916172422CbaD9E977f",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "37410315393302944044125"
      },
      {
        "symbol": "renBTC",
        "address": "0xEB4C2781e4ebA804CE9a9803C67d0893436bB27D",
        "amount": "345204111"
      }
    ]
  },
  {
    "poolId": "0xFEE7EeaA0c2f3F7C7e6301751a8dE55cE4D059Ec",
    "rewards": [
      {
        "symbol": "BNT",
        "address": "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c",
        "amount": "352552642271765341390619",
        "reward": 0.0010324699246457795
      },
      {
        "symbol": "WBTC",
        "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
        "amount": "2992701423",
        "reward": 2.3e-18
      }
    ]
  }
]
```

**Comment by pingustar** [comment]
@Velua @H34D 

**I gave my best to continue this, I hope its not all bad:**

- added the `aprMiningRewards` to the `relays` getter.
- moved the interfaces to `bancor.d.ts` file
- added the rewards data to the table in `TablePools.vue`

**Still missing:**
- aprMining data is loaded after table is rendered
- display rewards value as percentage
- Time remaining until reward cycle ends, timestamp missing
- small cap rewards not yet implemented

my changes can be reviewed at commit fe6a5dd47ce86a8300de1f0ab62934cb7ab35dfa and f99c124d0e9b0752468936555ffb26c99745361b

**Comment by ashachaf** [comment]
checking the calculation for ethbnt pool for bnt reserve:
totalProtectedReserveAmount(0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533, 0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c)
return:
3390211026483950866776662

IF BNT: 
(70000000000000000000000*52/3390211026483950866776662)*100= 107.367947646%


checking the calculation for ethbnt pool for eth reserve:
totalProtectedReserveAmount(0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533, 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee)
return:
11221593721149874107090

IF ETH: 
(30000000000000000000000*(15800503317283360679542)/(8101409855370277274285454))*52/11221593721149874107090)*100= 27.1131748522%

if needed, to pull the total reserve:
on the pool converter, call function connectors(reserve) -> return reserve balance

**Comment by Velua** [comment]
> for these pools:
> 
> * Large Cap
>   ETH/BNT, WBTC/BNT, USDT/BNT, USDC/BNT, DAI/BNT, LINK/BNT
>   weekly rewards. are planned to be 100,000-200,000 bnt
> * Mid Cap
>   OCEAN/BNT, renBTC/BNT
>   weekly rewards. are planned to be 10,000-20,000 bnt
> 
> how to calculate the APR from rewards:
> 
> 1. identify how much protected positions exist in a pool for a given token or BNT
>    on the protection store contract, execute this function:
>    totalProtectedReserveAmount(pool token, reserve token)
>    result is the total protected amount in the reserve token (in wei).
> 
> IF LARGE CAP:
> 
> * IF BNT: (70000000000000000000000*52/total protected BNT in the pool)*100
> * IF TKN: (30000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100
> 
> IF SMALL CAP:
> 
> * IF BNT: (7000000000000000000000*52/total protected BNT in the pool)*100
> * IF TKN: (3000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100
> 
> tool tip:
> Estimated APR based on weekly BNT Liquidity Mining rewards (pending governance vote). Counter indicates time until 12-week rewards cycle concludes. [Learn more](https://blog.bancor.network/announcing-bnt-liquidity-mining-b30be90a008d)
> (if we can add url, good. otherwise, remove the "learn more" part)
> 
> column title - when clicking the title, sort all pools with rewards first based on liquidity depth
> 
> mockup
> https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1080%3A708

Is the only difference between High cap and low cap calculations just the extra 0 on the end of 70000... and 3000...?

**Comment by ashachaf** [comment]
yes.
large caps give out 100,000 
small caps give out 10,000

**Comment by Velua** [comment]
> counter - indicates the time left until the liquidity mining plan is over for these pools
> until the contract is done, this should be counting downwards towards this time:
> 
> start time (novermber 16 2020 20:15GMT)
> end time february 8 2021. 20:15 GMT

Where does this time come from? Is this the same across all pools?

**Comment by ashachaf** [comment]
yes, this is for all 8 pools.
for the counter. they all should count down towards this time.

**Comment by Velua** [comment]
@ashachaf 
Awesome, we're almost there, @pingustar is just polishing off a few things looks wise. 

I've made two tests out of your example calculations.

**Comment by pingustar** [comment]
@ashachaf this is what we have right now.

![image](https://user-images.githubusercontent.com/7262066/99509034-8db87f80-2985-11eb-8041-9ddd328cb6bc.png)

table has a horizontal scrollbar. Maybe we can shorten "1y Fees / Liquidity" somehow?

**Comment by ashachaf** [comment]
we can update the title back to APR.
same tool tips.

**Comment by H34D** [comment]
fixed
