### ISSUE TITLE
data page - bring back the wallet login

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#559]
given that we are building the entire app as a single app, it make sense to bring back the wallet connect option on the data page as well.

when i land on the data page,  you should have the same wallet connect option as other pages.
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1072%3A0

**Comment by pingustar** [comment]
done. On staging in about 5 min.
