### ISSUE TITLE
withdrawing 100% liquidity protection will leave some fragments of tokens behind

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#560]
**Describe the bug**
When withdrawing 100% of liquidity protection some fragments of tokens will left behind on the contract

<img width="1160" alt="Screenshot 2020-11-17 at 11 32 18" src="https://user-images.githubusercontent.com/13647606/99379405-ec6bf380-28c8-11eb-800d-460c312499b5.png">

**To Reproduce**
1. have open liq protection positions that can be withdrawn
2. click withdraw
3. withdraw 100%
<img width="482" alt="Screenshot 2020-11-17 at 11 33 17" src="https://user-images.githubusercontent.com/13647606/99379376-e118c800-28c8-11eb-99f6-db12f7255815.png">

**Expected behavior**
It will withdraw 100%

**Comment by Velua** [comment]
@H34D I just tried this and it seemed to work okay, can you confirm my assertions made in commit hash bdc59709977156cebd3fac75b39f42337ee8407c just in the console logs?

**Comment by pingustar** [comment]
I have withdrawn a bunch of positions yesterday on ropsten. Worked fine.

**Comment by Velua** [comment]
Bump @H34D

**Comment by H34D** [comment]
you can reproduce this when staking a crude amount like 0.334343478349374234 and then try to unstake all, there must be rounding / conversion issue somewhere also related to #640
