### ISSUE TITLE
APR not sortable in the Protection screen

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#566]
**Describe the solution you'd like**
All other columns are sortable when you click the header. The APR column however is not clickable or sortable.

**Comment by pingustar** [comment]
@nhindman23 I have updated the sorting, we should discuss how the sorting behaves.

For APR, right now it is sorting by `1 day`, is that correct or should it be `1 week`?

What about the other columns, `Inital Stake`, and `Protected/Claimable Value` should those sort by TKN value or USD value?

thanks.

**Comment by pingustar** [comment]
I have updated the sorting:

- Initial Stake: by time of stake
- Protected Value: by USD value
- ROI: by percentage
- APR: by 1 day
- Current Coverage: by percentage
