### ISSUE TITLE
Table sorted alphabetical but should be numerical

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#571]
![photo_2020-11-18 18 52 56](https://user-images.githubusercontent.com/13647606/99568096-4ce55880-29cf-11eb-9fa2-b217543349a4.jpeg)

**Comment by Velua** [comment]
@pingustar is this something you recognise?

**Comment by pingustar** [comment]
yes, taking this on.

**Comment by pingustar** [comment]
I have a fix for most columns in the table in commit d92e2fb using a check for `isBigNumber` but for more complex table we probably need a similar approach to the custom filter prop.

When the selected column has an object with multiple properties, we need to pass a custom sorting function into the data table component.

**Comment by pingustar** [comment]
this particular issue is fixed. There are more edgecases that I might not be aware of, please reopen if you find anything else not working as it should.
