### ISSUE TITLE
Concurrency issue fetching historic fees

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#576]
It appears checkFees is not very concurrent as it's getting called several times after every chunk finishes which in turn will start firing several requests.

**Comment by Velua** [comment]
Implemented a RXJS based solution in f09d3c5e238acbd7d6a7d1170fe0c24d14ccf0fc @H34D check it out. 

- [ ] Use only one concurrent requests when fetching fee history
- [ ] Sort by liquidity depth

**Comment by H34D** [comment]
but it should be sorted by liq depth already. no?

https://github.com/bancorprotocol/webapp/blob/staging/src/store/modules/swap/ethBancor.ts#L6529-L6539

**Comment by Velua** [comment]
Only within this function which is only handling around 30 at a time, which means high priority pools could be pushed back to the 3rd batch and take forever to get loaded. 

My recent changes have introduced a smart buffering system which allows you to add as many converterAndAnchor sets to the observable and it will sort the queue each request.
