### ISSUE TITLE
rewards calculation - use max rewards numbers

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#582]
in the calculation used here:
https://github.com/bancorprotocol/webapp/issues/558

please update the following from 100k->200k and 10k->20k
this is the max rewards we can give out.

current:
IF LARGE CAP:

IF BNT: (70000000000000000000000*52/total protected BNT in the pool)*100
IF TKN: (30000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100
IF SMALL CAP:

IF BNT: (7000000000000000000000*52/total protected BNT in the pool)*100
IF TKN: (3000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100

updated:
IF LARGE CAP:

IF BNT: (140000000000000000000000*52/total protected BNT in the pool)*100
IF TKN: (60000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100
IF SMALL CAP:

IF BNT: (14000000000000000000000*52/total protected BNT in the pool)*100
IF TKN: (6000000000000000000000*((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100

tool tip update:
Estimated APR based on the maximum (2x multiplier) weekly BNT Liquidity Mining rewards. Counter indicates time until 12-week rewards cycle concludes. Rewards are pending governance.

**Comment by pingustar** [comment]
- [x] update rewards calculation
- [ ] update tooltip - waiting for text

**Comment by pingustar** [comment]
changes reverted as per @ashachaf request.

**Comment by Velua** [comment]
What's the go here?

**Comment by pingustar** [comment]
> What's the go here?

Feature on hold. No action required. @Velua

**Comment by pingustar** [comment]
updated formula and tooltip, https://github.com/bancorprotocol/webapp/pull/584/files
