### ISSUE TITLE
Data page - sorting by APR puts "N/A" first

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#587]
When sorting by high APR, N/A shows first.

- Open the app
- Sort the data page by APR

Notice N/A shows first.
Expected: N/A should always appear last.

**Screenshots**
![image](https://user-images.githubusercontent.com/1134236/99918740-94e2e300-2d21-11eb-8e23-792281649477.png)

**Comment by pingustar** [comment]
@yudilevi please check this again, as I have optimized the sorting algorithm this should not happen anymore.
Also Zero values will be at the end, so we dont have to paginate thru 20 pages with zero values.

Please reopen if need be.
