### ISSUE TITLE
Potential invalid price calculation

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#593]
User reported:
Im referring to the "price impact" calculation. Bancor should use an external price feed for each pair to know the fair price in the market so users like me don't get rekt on a small exchange. I exchanged 4000 REN for BNT on the Bancor U/I, my slippage selection was at the default 1%, and the price impact was around 0.025%. I obviously did the trade thinking that I'm getting a fair market value. The price impact ended up being about 35%.

That delta between the app and the tx seems too big for a pool that's relatively large.
Requires some investigation.

**Comment by Velua** [comment]
What's the transaction hash for this one? Need more info.

**Comment by yudilevi** [comment]
I know we received that report on November 19 at 8:56pm UTC, you can find the tx around that time.

**Comment by ashachaf** [comment]
@Velua 
https://etherscan.io/tx/0x5be5194605e6538f185152fa46f9fd344dfb883f97163100d68ebabb1f1f0295

**Comment by Velua** [comment]
Converter: https://etherscan.io/address/0xd5aa38c6df168741839f9e1e9c51e6d24b986970

Market value of pairs in USD
- REN $0.307
- BNT $0.73

**Comment by Velua** [comment]
Looking at the trade it looks like it was 3.98 REN for 1 BNT, however, at pure market price one would expect 2.377 REN for 1 BNT. 

Given the size of the pool is this amount of slippage expected to have been returned from the converter on a smart contract level? Seems quite high. 

Client calculates the slippage by ```getReturnByPath``` , does this remain accurate despite the magic happening in a V2 pool compared to traditional calculations done for V1 pools?

**Comment by yudilevi** [comment]
@Velua yup, these pools are basically v1 pools so there's no change to the calculations

**Comment by Velua** [comment]
In that case why did the trade encounter so much slippage given the converters liquidity depth?

**Comment by yudilevi** [comment]
pull all the stats so we can analyze it

**Comment by Velua** [comment]
Stale
