### ISSUE TITLE
Can't create a new pool

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#606]
Error when trying to create a new pool for a token that doesn't exist in the network yet.

1. Go to "swap"
2. Click on "pool"
3. Click on "Create pool"
4. Enter any token that doesn't exist
5. Select "add token"
6. Put in any address
7. See error

Tested on desktop.

![image](https://user-images.githubusercontent.com/1134236/100247605-2aa98880-2f43-11eb-8684-6b0284c3b0a7.png)

**Comment by H34D** [comment]
no repro on the original issue but optimized the token loading and select flow when adding a new token
