### ISSUE TITLE
text change - add liquidity popup

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#609]
on these screens:
data->add liquidity
protect -> stake

update the text.
current text:
By joining a pool, liquidity providers earn a percentage fee on all trades proportional to their share of the pool. Fees are added to the pool, accrue in real time and can be claimed by withdrawing your liquidity.

updated text:

Learn what it means to add liquidity to a pool:
1. [How do I make money by providing liquidity?](https://blog.bancor.network/how-to-stake-liquidity-earn-fees-on-bancor-bff8369274a1)
2. [What is impermanent loss?](https://blog.bancor.network/beginners-guide-to-getting-rekt-by-impermanent-loss-7c9510cb2f22)
3. [How does Bancor protect me from impermanent loss?](https://bankless.substack.com/p/how-to-protect-yourself-from-impermanent)

open links in a new tab.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1204%3A0
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1204%3A152

**Comment by pingustar** [comment]
text updated. Going to staging now.
