### ISSUE TITLE
Pools search popup 

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#61]
There are a few changes to pools search popup:

1. Please move user balance to the left (under token name)
2. Please move V1/V2 tags to the right
3. Please add “V1/V2/All” tabs (filter)
4. Please add “cap reached” message to the right for pools which cap has been reached.

Please check here: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f17d10a2e7a98770fa68bb3/

Thanks!

<img width="442" alt="Screenshot at Aug 09 09-25-57" src="https://user-images.githubusercontent.com/69288176/89726418-fd33e000-da22-11ea-950d-38de6f863958.png">

**Comment by Velua** [comment]
Will have to look into calculating fiat valuation of pool tokens

**Comment by Velua** [comment]
@pingustar Utilise my new b-form-radio-group I've drafted, maybe split into it's on SFC.

**Comment by Velua** [comment]
@pingustar How's this one? Given we're not all too hot on V2 pools atm maybe this is something that can be closed?

**Comment by Velua** [comment]
@pingustar bump
