### ISSUE TITLE
transaction value - rounding numbers

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#611]
when stake into protection (was tested on this flow), it seems that the frontend rounds the number.
as it sometimes rounds up, the transaction can be for 1wei greater than my balance which will cause it to throw error and fail (and cost the user a lot of money if they execute it)

flow:
stake->add liquidity
1. input amount - we should restrict the input amount based on the token decimals.
![image](https://user-images.githubusercontent.com/40430285/100325719-ab16ca80-2fd1-11eb-9c0e-2e313cba631b.png)

2. confirmation popup - rounding the amount. this is not ideal but not critical issue.
![image](https://user-images.githubusercontent.com/40430285/100325815-ca155c80-2fd1-11eb-8cdf-2fda9d9c4d0f.png)

3. confirming the approval transaction, the approved amount is: 1123456789012345679
expected: 1123456789012345678
actual: 1123456789012345679
https://ropsten.etherscan.io/tx/0xbe8e4d81a23c302a2d5b0ab45bfe8957aa738fbba9773411ccabb56c781a384b

4. executing the stake, amount is 1 wei higher than input
expected: 1123456789012345678
actual: 1123456789012345679
https://ropsten.etherscan.io/tx/0x8fd974a7e5cfc3e8ea0cf20de0c3e8ac24af00d300ca8605f8c050261df2cec5

**Comment by pingustar** [comment]
- changed `expandToken` method to trim decimals to given precision and round down.
- moved `expandToken` method to `pureHelper` file
- added testing for `expandToken` method

currently waiting to be reviewed.

**Comment by pingustar** [comment]
going to production now
