### ISSUE TITLE
Protection Table - Group Positions

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#615]
as a user, i would like to be able to view my summary in a glance and know my entire portfolio performance, group by specific tokens in a pool and to be able to filter out different views.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1145%3A2

### Protected table grouping
1. grouping logic:
- by pool and then by token. 
examples:
- if i have 3 eth positions on ethbnt pool, i will see them as a single row.  
- if i have 2 bnt positions on ethbnt pool and 3 bnt positions on linkbnt pool, i will see then grouped by pool. 1 row for all ethbnt bnt positions and 1 row for all linkbnt bnt positions.
2. table updates: 
- when user has more than 0 protected positions, change the name of the table to "My Protected Positions" to indicate this is a personal view.
3. columns logics
#### initial stake:
- remove the stake date and make it visible on "mouse over"
- sort by date. If a row represents a group, use the date of the "newest" position in the group. default should show newest positions first.
- add + next to pool name for rows that indicate group of items
- identify all reserve token positions in a specific pool, and group them together. display the sum of all relevant rows. 
examples: 2 positions for 100tkn worth $10 and 200tkn worth $20 will be displayed as 300tkn (~$30)
#### protected value:
- sum of all relevant protected positions
- percentage change = (1-(sum protected positions)/(sum initial stake)). this value needs to be normalized into percentages.
#### claimable value:
- sum of all relevant claimable positions
#### fees:
- sum of all fees from the relevant positions.
#### ROI:
- sum ROI = (1-(sum protected positions)/(sum initial stake)).  this value needs to be normalized into percentages.
#### current coverage:
- show the vesting time of the "oldest" position in the group
#### call to action:
- IF group -> show "Open Group". when clicked, it will open the rows that are part of this group sorted by date. each row will serve as individual row with a "withdraw" call to action.
- IF single position -> show "Withdraw". when clicked, follow the existing process.

**Comment by ashachaf** [comment]
@Velua tried to be as detailed as possible with this task.
as discussed, this is open for feedback.

**Comment by pingustar** [comment]
@ashachaf I have split this into 3 separate issue for easier handling.

- Summary View https://github.com/bancorprotocol/webapp/issues/629
- FIltering https://github.com/bancorprotocol/webapp/issues/630

**Comment by pingustar** [comment]
@ashachaf do we have mockups for mobile?

**Comment by ashachaf** [comment]
@pingustar i recall a question on the ARP value for the grouped position, the APR is on the pool level over the last x days. it is not related to the user's current position or performance. as such, it stays the same calculation for both grouped or individual rows.

**Comment by pingustar** [comment]
@ashachaf great, thanks!

**Comment by pingustar** [comment]
>     * show the vesting time of the "oldest" position in the group

would that not be misleading if it says 100% covered for the group but actually the group has only 1 positions that is at 100%?

@ashachaf

**Comment by pingustar** [comment]
getting closer. @ashachaf please check staging and let me know what you think so far.

**Comment by Velua** [comment]
@pingustar Found a bug where hitting the withdraw button doesn't work, looks like you're re-doing the positions listing according to the id + symbol rather than it's ID + index which is causing the look up to fail. 

I've made a commit which makes a clean error illustrating this so you'll see. 

I've also exported your grouping function to ```pureHelper.ts```, lets write a unit test for this one, it's an interesting piece of code.

**Comment by pingustar** [comment]
thanks @Velua will fix that.

**Comment by pingustar** [comment]
I have finished this and added a test for the `groupPositionsArray` function.

@ashachaf please review.

**Comment by ashachaf** [comment]
@pingustar 
few feedbacks on the implementation:
![image](https://user-images.githubusercontent.com/40430285/101600077-78be9180-3a03-11eb-8745-d7c3952f07a8.png)
- plus sign is not correct.
- group indication should be "open group" (due to space, you can use "un-group") and it needs to be in a button format and "close" when the group is open.

![image](https://user-images.githubusercontent.com/40430285/101600493-0ac69a00-3a04-11eb-872f-91d8dbedd453.png)
- "withdraw" font should not be bold

**notice**
as part of the design work we are doing on the claim rewards task, we have considered updating the "un-group" and "withdraw" buttons with icons.
perhaps you can already implement the icons (only icons) from this mockup:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1406%3A40

**Comment by pingustar** [comment]
@ashachaf I have updated the group and withdraw buttons.

Can you share some more details about the required changes to the plus sign please.

**Comment by ashachaf** [comment]
@pingustar 
plus sign:
frame should be 14x14
plus should be 6x6

**Comment by pingustar** [comment]
fixed.
