### ISSUE TITLE
Adding "search" to "your liquidity" section

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#62]
1. Please add "search" bar next to "your liquidity" section in "pool" view of the widget.
2. Please add V1/V2 tags to pool tokens

Zeplin: 
v1: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f2f8b6d22e95f21fe4c39b9/
v2: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f2001b6c436a6364994b829/

Thanks

<img width="974" alt="Screenshot at Aug 09 09-32-24" src="https://user-images.githubusercontent.com/69288176/89726460-877c4400-da23-11ea-9bcb-1ff0de2b6d21.png">

**Comment by pingustar** [comment]
added search functionality and version badge, please review.
