### ISSUE TITLE
space available calculation mistake

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#621]
when we calculated the space available for single side staking, we have a mistake in the calculation.
this mistake is on the frontend only.

we currently calculate the available BNT as maxSystemNetworkTokenRatio * bntReserveBalance.
current calculation:
  // allowed BNT based on ratio cap
  const maxRatioBnt = zeroIfNegative(
    new BigNumber(maxSystemNetworkTokenRatioDec)
      .times(bntReserveBalance)
      .minus(systemBNT)
  );

in fact, this should be slightly different.

updated calculation:
maxRatioBnt = ((bntReserveBalance * maxSystemNetworkTokenRatioDec) - systemBNT)/(1-maxSystemNetworkTokenRatioDec)

example:
values:
- bnt reserve balance = 200
- system bnt = 100
- max sys ratio = 50%
calculation:
maxRatio = ((200*0.5)-100)/(1-0.5) = 0
which means, pool has minted the max allowed based on this ratio.
**IF maxRatio<0, set it to 0**

example using yfi numbers:
pool token: https://etherscan.io/address/0xaeb3a1aed77b5d6e3feba0055d79176532e5ceb8
converter: https://etherscan.io/address/0x9258af079065857c01466cebdcfa2cfb6aa4983c#readContract
YFI reserve balance: 22.823617377346322429 YFI
BNT reserve balance: 549,542.316191026070027217 BNT
pool token supply: 2,988.7630212873065
sys balance: 1430.881844360983306284
sys balance to bnt: 

existing calculation:
// calculating the systemBNT  from system pool tokens
  const rate = bntReserveBalance.div(poolTokenSupply);
  const systemBNT = poolTokenSystemBalance.times(rate);
using the above numbers:
const rate = 549542316191026070027217.div(2988763021287306579185);
  const systemBNT = 1430.881844360983306284.times(183.869484558); = 263095.507186 BNT
using new calculation:
maxRatioBnt = ((bntReserveBalance * maxSystemNetworkTokenRatioDec) - systemBNT)/(1-maxSystemNetworkTokenRatioDec)
maxRatioBnt =  ((549,542.316191026070027217 * 0.5) - 263095.507186)/(1-0.5) = 23351.301819 
converting maxRatioBnt to YFI = maxRatioBnt * 22.823617377346322429/549,542.316191026070027217 = 23351.301819* 0.00004153204 = 0.96982720119 YFI

compared with the current calculation:
  // allowed BNT based on ratio cap
  const maxRatioBnt = zeroIfNegative(
    new BigNumber(maxSystemNetworkTokenRatioDec)
      .times(bntReserveBalance)
      .minus(systemBNT)
  );
= 0.5 * 549,542.316191026070027217 - 263095.507186 = 11675.6509095 BNT (which is half the amount it should be based on the new calculation)

**Comment by Velua** [comment]
In this new test I've created... 

```
  test("results are as expected from #621", () => {
    const yfiReserve = expandToken("22.823617377346322429", 18);
    const bntReserve = expandToken("549542.316191026070027217", 18);
    const poolTokenSupply = expandToken("2988.7630212873065", 18);
    const systemBalance = expandToken("1430.881844360983306284", 18);

    const { maxAllowedTknWei } = calculateMaxStakes(
      yfiReserve,
      bntReserve,
      poolTokenSupply,
      systemBalance,
      expandToken(5000000, 18),
      "500000",
      false
    );

    const numberRes = Number(shrinkToken(maxAllowedTknWei, 18));
    expect(numberRes).toBeCloseTo(0.96982720119);
  });
```
We're expecting the result to max allowed TKN to be 0.96982720119, what can we expect the max allowed BNT to be using the same params?

**Comment by Velua** [comment]
Now pushed to staging, awaiting test for prod.

**Comment by ashachaf** [comment]
testing on staging:
few possible issues:
1. data you use on the frontend might be different from what i was pulling from thee blockchaini
2. calculation is not the same as below
3. frontend indication is not aligned with the calculation
4. when you display a limit and a user add the full amount, how is it that the following transaction can add about 50% of the previous limit again?

### 1st run
xxxbnt pool.
bnt reserve: 502,457.906853178719914057
xxx reserve: 232,703.305995522538513417
pool token supply: 263383.686800822047190139
sys balance in pool token: 131181.180381192441640069

sysBNT = (bnt reserve / token supply) * sys balance
**sysBNT = (502,457.906853178719914057/263383.686800822047190139)*131181.180381192441640069 = 250254.759942**

maxRatioBnt = ((bntReserveBalance * maxSystemNetworkTokenRatioDec) - systemBNT)/(1-maxSystemNetworkTokenRatioDec)
**maxRatioBnt = ((502,457.906853178719914057 * 0.5) - 250254.759942)/(1-0.5) = 1948.38696918 BNT**

maxRatioTKN = maxRatioBnt * (tkn reserve balance / bnt reserve balance)
**maxRatioTKN = 1948.38696918 * (232,703.305995522538513417 / 502,457.906853178719914057) = 902.356362399 XXX**

#### frontend showed me that there was space for 115,000 XXX,  while this calculation shows iit can only support 902 XXX
#### i was able to add 115,000 XXX to the pool single sided.
#### at this stage, UI shows me there is space for additional 55,000 XXX

### 2nd run
xxxbnt pool.
bnt reserve: 752,202.065362831708305057
xxx reserve: 348,367.305995522538513417
pool token supply: 394297.214736331659355271
sys balance: 196637.944348947247722635

sysBNT = (bnt reserve / token supply) * sys balance
**sysBNT = (752,202.065362831708305057/394297.214736331659355271)*196637.944348947247722635 = 375126.839196**

maxRatioBnt = ((bntReserveBalance * maxSystemNetworkTokenRatioDec) - systemBNT)/(1-maxSystemNetworkTokenRatioDec)
**maxRatioBnt = ((752,202.065362831708305057 * 0.5) - 375126.839196)/(1-0.5) = 1948.38697083 BNT**

maxRatioTKN = maxRatioBnt * (tkn reserve balance / bnt reserve balance)
**maxRatioTKN = 1948.38697083 * (348,367.305995522538513417 / 752,202.065362831708305057) = 902.356363163 XXX**

**Comment by ashachaf** [comment]
@Velua 
after long debugging, this is the updated calculation which will show you the amount of **TKN** the pool can accept (single side staking).

if you use percentage as a value between 0-1:
(tknBalance * p - sysBalance * tknBalance / totalSupply) / (1 - p)

if you use ppm:
(tknBalance * p - 1000000 * sysBalance * tknBalance / totalSupply) / (1000000 - p)

actual code using ppm:
tknBalance.mul(p).sub(sysBalance.mul(tknBalance).mul(1000000).div(totalSupply)).div(1000000 - p)

example using xxxbnt pool data:
pool token supply: 459753.978704086465437837
XXX reserve: 406,199.305995522538513417
BNT reserve: 877,074.144617658202500557
sys pool balance: 229366.326332824650763918
maxRatio = 500,000 in ppm = 50% = 0.5

(tknBalance * p - sysBalance * tknBalance / totalSupply) / (1 - p)
=> **((406,199.305995522538513417 * 0.5) - (229366.326332824650763918 * 406,199.305995522538513417)) / 459753.978704086465437837) / (1 - 0.5) = -405296.066118 TKN**
** IF result <0, set to 0**

example using yfibnt (production):
YFI reserve: 25.23247380420303708
BNT reserve: 647,758.396109747717331815
pool token supply: 3411.112092474850883773
sys pool balance: 1641.951046786342390985
maxRatio = 500,000 = 50% = 0.5

(tknBalance * p - sysBalance * tknBalance / totalSupply) / (1 - p)
**(25.23247380420303708 * 0.5 - 1641.951046786342390985 * 25.23247380420303708 / 3411.112092474850883773) / (1 - 0.5) = 0.94099017502 YFI**

keep in mind, this value still needs to be checked against the limits and tiers.

**Comment by ashachaf** [comment]
if you want to extract the **BNT** amount (you might need this for limit check), do the following:

if you use percentage as a value between 0-1:
(bntBalance * p - sysBalance * bntBalance / totalSupply) / (1 - p)

if you use ppm:
(bntBalance * p - 1000000 * sysBalance * bntBalance / totalSupply) / (1000000 - p)

actual code using ppm:
bntBalance.mul(p).sub(sysBalance.mul(bntBalance).mul(1000000).div(totalSupply)).div(1000000 - p)

example using xxxbnt pool data (ropsten):
pool token supply: 459753.978704086465437837
XXX reserve: 406,199.305995522538513417
BNT reserve: 877,074.144617658202500557
sys pool balance: 229366.326332824650763918
maxRatio = 500,000 in ppm = 50% = 0.5

(bntBalance * p - sysBalance * bntBalance / totalSupply) / (1 - p)
=> ((877,074.144617658202500557 * 0.5) - (229366.326332824650763918 * 877,074.144617658202500557)) / 459753.978704086465437837) / (1 - 0.5) = -875123.849944 BNT
IF result <0, set to 0

example using yfibnt (production):
YFI reserve: 25.23247380420303708
BNT reserve: 647,758.396109747717331815
pool token supply: 3411.112092474850883773
sys pool balance: 1641.951046786342390985
maxRatio = 500,000 = 50% = 0.5

(bntBalance * p - sysBalance * bntBalance / totalSupply) / (1 - p)
=> ((647,758.396109747717331815 * 0.5) - (1641.951046786342390985 * 647,758.396109747717331815 / 3411.112092474850883773)) / (1 - 0.5) = 24156.7390998 BNT

keep in mind, this value still needs to be checked against the limits and tiers.

**Comment by H34D** [comment]
I opened PR: https://github.com/bancorprotocol/webapp/pull/643 which is inconclusive as off now. The plan was to create two methods that can be tested more easily. In the end i think i struggled with the implementation of the high tier pool logic.

**Comment by ashachaf** [comment]
@H34D - what is the status of this?

**Comment by H34D** [comment]
> @H34D - what is the status of this?

working on it

**Comment by ashachaf** [comment]
@H34D please do what you can to close this issue today.

**Comment by H34D** [comment]
> @H34D please do what you can to close this issue today.

will do

**Comment by H34D** [comment]
given up for #669
