### ISSUE TITLE
Update PoolLogosOverlapped.vue

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#623]
The component ```PoolLogosOverlapped.vue``` is dependent on the getter...

```
  get pool() {
    return vxm.bancor.relay(this.poolId);
  }
```

And will break if a pool is not returned, lets update this so that if the relay failed to be looked up, it will render two question mark images or something else instead.

**Comment by pingustar** [comment]
optimized the error handling, fallback logo added and if the pool lookup fails I also updated the pool name to fallback to 'N/A' since this would otherwise cause the same error.

@Velua please review PR #627
