### ISSUE TITLE
stake liquidity gives error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#628]
when trying to stake liquidity, seems there is some issue with decimals.
testing on staging+ropsten
click the available space to stake the full possible amount:
![image](https://user-images.githubusercontent.com/40430285/100596111-758d1c80-3304-11eb-9b5b-ee9dab06f749.png)

metamask error
![image](https://user-images.githubusercontent.com/40430285/100596253-9fdeda00-3304-11eb-9125-e50a21b51cec.png)

try again,  without the decimals
![image](https://user-images.githubusercontent.com/40430285/100596325-b422d700-3304-11eb-8c71-43c783126a4b.png)
metamask with no error
![image](https://user-images.githubusercontent.com/40430285/100596377-c7ce3d80-3304-11eb-870c-949bf812fd35.png)

**Comment by ashachaf** [comment]
@pingustar might be rounding related?

**Comment by pingustar** [comment]
@ashachaf I dont think it is a rounding issue because your balance is higher than the amount to stake. So even if it would round up, there is enough balance to cover for this rounding error.

@Velua any thoughts?

**Comment by Velua** [comment]
I've seen a recent change to how we're approaching rounding @ashachaf can you try this out again now? 
I've just tried it out myself on staging on ropsten and failed to replicate.

**Comment by ashachaf** [comment]
unable to reproduce.
