### ISSUE TITLE
Protected Table - Add Summary view

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#629]
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1216%3A0

### Summary view (5 items): a view that allows users to view their entire portfolio in a glance.

1. summary initial stake = sum of all initial stakes displayed in USD
2. protected value =
- sum protected value = sum of all protected values displayed in USD.
- percentage change = (1 - (sum protected value) / (sum initial stake)). this value needs to be converted into percentages.

3. sum claimable value = sum of all claimable values displayed in USD.
4. sum ROI = (1 - (sum protected value) / (sum initial stake)). this value needs to be converted into percentages.
5. move the "stake" call to action into this row

**Comment by pingustar** [comment]
going to staging now. @ashachaf please review.

**Comment by ashachaf** [comment]
i was debating to remove the ROI.
what is our number formatting?
i thought it is:
less than 1 -> 0.123456
1 to 1,000 -> 123.12
over 1000 -> 1,234

**Comment by pingustar** [comment]
> i was debating to remove the ROI.
> what is our number formatting?
> i thought it is:
> less than 1 -> 0.123456
> 1 to 1,000 -> 123.12
> over 1000 -> 1,234

@ashachaf that is for TKN amounts.

for USD it is:

less than 100 -> 99.12
over 100 -> 1,234
