### ISSUE TITLE
“Max” button in swap / add liquidity

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#63]
Please add "max" button to swap/add liquidity screens. 

Swap: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f16eaa1da69cc7911299103/
Add Liquidity: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f17d10111633f69276b5bcc/

Thanks!

<img width="616" alt="Screenshot at Aug 09 09-36-40" src="https://user-images.githubusercontent.com/69288176/89726517-05404f80-da24-11ea-8165-00edfc35d8d0.png">

**Comment by Velua** [comment]
@yudilevi @ashachaf Are we sure we want ```MAX``` ? This happens already when the user clicks the Balance. Feel like this clutters things too much.

**Comment by yudilevi** [comment]
I tend to agree... @katyarozenfeld maybe something more subtle?

**Comment by katyarozenfeld** [comment]
Yes, thanks for your comments, will try to make it look more subtle.

**Comment by pingustar** [comment]
@yudi
I think even a subtle might be to much since the same functionality exists already.

For example on mobile phone with smaller screens, the user won't see much of their amount entered anymore.

**Comment by yudilevi** [comment]
Let's see what Katya can come up with and then decide.

**Comment by katyarozenfeld** [comment]
We did a few experiments with Guy and we think we should leave "MAX" button, but slightly redesign it (attached). 

<img width="1251" alt="Screenshot at Aug 10 15-48-08" src="https://user-images.githubusercontent.com/69288176/89784648-afea6800-db21-11ea-9ba5-fb5e6042ed4d.png">

**Comment by pingustar** [comment]
@katyarozenfeld 

please provide colors for max button dark mode

**Comment by katyarozenfeld** [comment]
@pingustar https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f3cd63d2b6ae231d674608d/

**Comment by Velua** [comment]
@ashachaf is this still something we're after?
