### ISSUE TITLE
Protected Table - New filter logic and UI

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#630]
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2196%3A71

#### introducing 3 new filters:
1. positions: (all positions, only fully protected, only not fully protected).
2. group by pool token: (All pools, ETHBNT, LINKBNT,etc). should allow a selection of pools that the user has positions for.
3. time selection: when selected show pre determine timerane, indicate it by name (for example, "Yesterday"), for custom range show dd-mmm-yy - dd-mmm-yy (example: "23-OCT-20 - 12-NOV-20")
examples:
https://github.com/bliblidotcom/vue-rangedate-picker
#### filter logic:
1. trim the list based on the filters selected
2. color the filter bold to indicate it is active.

**Comment by Ran73Cohen** [comment]
Continue [here](https://github.com/bancorprotocol/webapp/issues/1165)
