### ISSUE TITLE
statistics update on data page

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#635]
as a user, i would like to have a visibility into the total volume in the network over the last 24h timeframe.

24h total volume = sum of all pools 24h volume.
BNT price = indication of the current bnt price in usd.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1072%3A0

**Comment by ashachaf** [comment]
also, we would like to include the percentage of locked bnt from circulating supply.

locked bnt percentage = (total locked bnt) / (total bnt supply). normalize this value into percentage.
example:
locked bnt = 42105473.915841584158416
circulating supply bnt = 87868811.011974018147889204
locked bnt = 42105473.915841584158416/87868811.011974018147889204 = 0.47918565678 => 47.91%

**Comment by pingustar** [comment]
I have added volume 24h and reactivated the swap 24h count.

@Velua to take over for part two

**Comment by ashachaf** [comment]
@Velua please see if the required data exist for this % locked.

**Comment by Velua** [comment]
Locked BNT as part of protection? Or are we talking about staked BNT liquidity?

**Comment by ashachaf** [comment]
bnt in pool.

**Comment by Velua** [comment]
@pingustar I've recently added the percentages in https://github.com/bancorprotocol/webapp/commit/53290721b2812d2e44a6476a51c4d2a69d1d3659 

You'll find ```stakedBntSupplyPercent?: number``` on ```ViewRelay``` now.

**Comment by ashachaf** [comment]
seems that now staging shows half the value for total liquidity.

staging:
![image](https://user-images.githubusercontent.com/40430285/101001149-6b1e8d00-3567-11eb-80a9-e18c0554c119.png)

production:
![image](https://user-images.githubusercontent.com/40430285/101001174-7376c800-3567-11eb-8678-37e558e4f90a.png)

**Comment by Velua** [comment]
@pingustar new commit c03956c03c8effdd4ecc366ed978dbb3e03bd298

**Comment by pingustar** [comment]
staging issue comes along when cherry picking 5329072 and c03956c

on hold until fixed.

**Comment by pingustar** [comment]
@ashachaf 

@H34D and @pingustar are looking into this now

**Comment by pingustar** [comment]
added to staging @ashachaf
