### ISSUE TITLE
support direct swap URL

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#641]
as a user, when i visit swap.bancor.network (redirects to app.bancor.network/eth/swap), i would like for it to load and be available for me in the fastest possible time.

can we:
1. reduce the calls needed when loading the swap page
2. use the price api which returns real time prices instantly

**Comment by Velua** [comment]
Which price API? 
Rest of this is being addressed in #346

**Comment by ashachaf** [comment]
Yariv's mentioned there is a price api we might be able to use.
