### ISSUE TITLE
support the option for fiat onboarding/offboarding

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#642]
as a user, i would like to have the option to buy crypto with fiat or swap my crypto back to fiat.
note, we are NOT associated with the solution, just listing few selected options to make it available for our users.

side menu item:

page layout:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=548%3A7980

moonpay implementation URL:
buy: https://buy.moonpay.com?apiKey=pk_live_qiJRayRj9iKRUWCfaWX5Vo6Sn0rnNsj&defaultCurrencyCode=ETH
sell: https://sell.moonpay.com?apiKey=pk_live_qiJRayRj9iKRUWCfaWX5Vo6Sn0rnNsj&defaultCurrencyCode=ETH

test key:
pk_test_UQrsGSrVtsrfN5O5IZUPJCDW5kXrrapO

**Comment by ashachaf** [comment]
ive updated the url slightly.
check the option for test key

**Comment by Velua** [comment]
When would we use the test key?

**Comment by ashachaf** [comment]
to test deposit flow end to end and make sure it register correctly (without using a valid cc)
