### ISSUE TITLE
not showing vote area in voting page on mobile

### ISSUE THREAD

**Issue by sirius651** [bancorprotocol/webapp#644]
**Describe the bug**
not showing vote area in voting page on mobile

Related #481 

**To Reproduce**
go to vote page on mobile

**Expected behavior**
should show vote are in voting page on mobile

**Screenshots**
![스크린샷 2020-12-03 오전 11 14 11](https://user-images.githubusercontent.com/1606820/100954828-b67d6f00-3558-11eb-9af2-f476993cc6de.png)

**Smartphone or Desktop/Laptop?**
phone

**Additional context**

**Comment by sirius651** [comment]
Because there was issues with css stuff from @H34D mentioned, should improve it more. we should resolve it by not using the current table components at all. I'm currently looking it.

**Comment by H34D** [comment]
fixed with #677
