### ISSUE TITLE
new pools with liquidity rewards

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#647]
in preparation for the vote to end later today, we would like to confirm that our system will be able to indicate rewards APR for these new pools.

current pools that are possible to be voted in (2 will be selected):
- yfi converter: 0x9258af079065857c01466cebdcfa2cfb6aa4983c. pool token: 0xaeb3a1aed77b5d6e3feba0055d79176532e5ceb8. anchor address: 0xaeb3a1aed77b5d6e3feba0055d79176532e5ceb8
- ren converter: 0xAcba46e8654Bc8c55dd0CBDaF22b5e30036fAced. pool token: 0x6b181c478b315be3f9e99c57ce926436c32e17a7. anchor address: 0x6b181c478b315be3f9e99c57ce926436c32e17a7

rewards that are allocated for these pools are 10,000-20,000 bnt per week. this is similar to mid cap pools we have.

once these pools are voted (pending final vote), they will be included in the "high tier" list and we should display rewards for them on the data table.

calculating rewards (reminder as this code exists):
IF SMALL CAP:
IF BNT: (14000000000000000000000*52/total protected BNT in the pool)100
IF TKN: (6000000000000000000000((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100

**Comment by pingustar** [comment]
I have added REN and FYI to the `highCapPools` array
