### ISSUE TITLE
Rewards counter and apr errors

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#649]
### counter to unique end date for each pool
Every time a new pool is added to the liquidity mining rewards plan, it will count down to 12 weeks time stamp. 

The newly added pools, will need to count down to this destination time:

destination date for these two pools is: 
February 25, 2021 6:05pm GMT

Currently, new pools use the same destination as the older ones which is incorrect.

**to confirm:**
YFI and REN rewards counter should count down to feb 25 2021 6:05pm GMT.
all other pools, should count to their current destination time.

### rewards amount for mid cap pools
the newly added pools are mid cap pools and should receive. rewards of 10,000 - 20,000 bnt per week.
- current calculation seems to use the "high cap" pools rewards (which is 10x the rewards per week).
- update the calculation and make sure these pools are using the correct mid level  pool rewards.

**Comment by ashachaf** [comment]
### update
we have removed the anchors of the new pools from the `export const highCapPools` list.

**Comment by Velua** [comment]
> Every time a new pool is added to the liquidity mining rewards plan, it will count down to 12 weeks time stamp.

Where can the app source the timestamp of when this happens? Will it always be 12 weeks? Is there a resource the app can fetch to confirm it's 12 weeks as well? 

Looking at our current formula and tests written around it, the app is only supporting low and high tier pools, do you know what issue # this mid allowance was raised? Or is this being raised now? 

How can we determine by a network resource (traditionally Ethereum contract) 
- When a pool gets added to a liquidity mining reward plan, to determine when to start the timer.
- What cap tier is it? Low, mid or high cap, to determine the correct cap to give it.

I'll start with hard coding the new destination times as per.

> destination date for these two pools is:
February 25, 2021 6:05pm GMT

Will need to revise the current function for calculating mid return if this hasn't been raised in an issue already and need a test or two written.

**Comment by ashachaf** [comment]
All this data should exist in the rewards contract but this is eta in few weeks. 
Which means we need a solution for this before the contract exist on the blockchain.

**Comment by Velua** [comment]
Is there such thing as a low tier reward? 
If the current numbers are correct then Mid rewards are current known as low rewards in the code. 

We'll continue with the hard coding solution til we get a long term one implemented then.
