### ISSUE TITLE
UI - Data - Tokens/Pools Table

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#65]
There are a few corrections to a tokens/pools table

1. Please fix shadows for the cards except search bar at the top
2. Please add a separation line under the title
3. Please replace "pairs" with "pools"
4. Please change "pools/tokens" buttons to tabs
5. Please reduce the search bar inside the table and move it to the right
6. Please change the style of "trade" button
7. Left alignment of data inside the table
8. Please change body text font color
9. Please remove grey/white shifting of rows, just white with grey separation line.

Thanks!

<img width="1604" alt="Screenshot at Aug 09 18-08-05" src="https://user-images.githubusercontent.com/69288176/89735461-51fb4900-da6b-11ea-9327-87141ef2fdff.png">

**Comment by Velua** [comment]
New message from @katyarozenfeld 

Hi, I just reviewed data - exciting, looks great! But still there are a few deltas between design and live app. Here is a list:

1. Title "Statistics" text style isn’t correct
2. Please add a separation line below the title
3. Body text color doesn't fit the design - main body text color is 0A2540
4. Is is possible to change card's shadows exactly as it is in Zeplin? As this page is full of information, shadows look slightly distractive, so the if you can make shadow more gentle would be great.
5. Please change arrow icons in the header of the table
6. Please add icon to a search box
7. Please change the color of "search" to D0D7DF
8. Please add shadow to token images - tokens with white backgrounds are problematic
9. Separation lines inside the table (and grey header box) should reach the edges
10. Please change the style of V1/V2 tags - relevant to all pages
11. Is it possible to fix alignment in the table? Titles and numbers should be aligned left. 

Thanks a lot

<img width="1746" alt="Screenshot at Aug 12 08-38-39" src="https://user-images.githubusercontent.com/69288176/89979735-22ba2700-dc79-11ea-9d87-30b3e62822f1.png">

**Comment by Velua** [comment]
From @nhindman23 https://user-images.githubusercontent.com/53524917/90064660-cea05880-dcf3-11ea-8ee4-fcfff8b7ac40.png

**Comment by Velua** [comment]
@pingustar Kill the ratio column for now, it's not quite the same thing between V1 and V2, so I probably shouldn't have added that.

**Comment by pingustar** [comment]
All done, please review.

**Comment by katyarozenfeld** [comment]
Hi, I 've just reviewed https://staging.swap.bancor.network/eth/data

Here are a few comments:
1. Tabs - "token"/"pool" text color  - please fix
2. Search - "search" text color - please fix (should be lighter). Also relevant to typing mode - need to be 0A2540. 
3. Tabs - blue line looks broken - "trapeze" shape
4. Please align tabs with table content. No need to make blue line wider than tab name. 
5. Can we fix the width of the buttons? Just as it is in Zeplin? 132 px & 132 px
6. Pagination - Please replace icons to what we have in Zeplin
7. Pagination - Please change text color

Mobile 
1. Please move "search" box to top right (screenshot attached)
2. Please fix spacing in statistics card (screenshot attached)

Dark mode
1. I'm sorry, it feels too late - but I've prepared design only for one page in dark mode to be as a guide for you, but now I feel it wasn't enough. Therefore, I've added dark mode version of pool page here, and there are a few points that need to be changed: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f3668ef86e30c68d2f09039/

Please let me know if you need a detailed guide for the dark mode in addition to what we have in Zeplin or do you prefer to receive the list of changes per each page?

Thanks!

<img width="1519" alt="Screenshot at Aug 14 13-18-02" src="https://user-images.githubusercontent.com/69288176/90241623-20e89300-de34-11ea-84ca-a2ca2605173d.png">

![photo_2020-08-14 13 23 08](https://user-images.githubusercontent.com/69288176/90241641-280fa100-de34-11ea-8b73-10e0051ca591.jpeg)
![photo_2020-08-14 13 23 03](https://user-images.githubusercontent.com/69288176/90241643-28a83780-de34-11ea-8e95-18f360ce58a6.jpeg)

**Comment by katyarozenfeld** [comment]
@pingustar Just wanted to check whether you see my comment above. Please let me know if I should open new issue for these comments. Thanks!

**Comment by pingustar** [comment]
I am seeing it @katyarozenfeld 

If you can add a new issue and add checkboxes for each bullet point that would be great. Will help me a lot. Thanks!

**Comment by katyarozenfeld** [comment]
Added #91.

Thanks!

**Comment by Velua** [comment]
Message from @katyarozenfeld 

> Hi, here are a few comments for data pool/token table:
> 
>     * [ ]  Tabs - "token"/"pool" text color - please fix
> 
>     * [ ]  Search - "search" text color - please fix (should be lighter). Also relevant to typing mode - need to be 0A2540.
> 
>     * [ ]  Tabs - blue line looks broken - "trapeze" shape
> 
>     * [ ]  Please align tabs with table content. No need to make blue line wider than tab name.
> 
>     * [ ]  Can we fix the width of the buttons? Just as it is in Zeplin? 132 px & 132 px
> 
>     * [ ]  Pagination - Please replace icons to what we have in Zeplin
> 
>     * [ ]  Pagination - Please change text color
> 
> 
> Mobile
> 
>     * [ ]  Please move "search" box to top right (screenshot attached)
> 
>     * [ ]  Please fix spacing in statistics card (screenshot attached)
> 
> 
> Dark mode
> 
> I'm sorry, it feels too late - but I've prepared design only for one page in dark mode to be as a guide for you, but now I feel it wasn't enough. Therefore, I've added dark mode version of pool page here, and there are a few points that need to be changed: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f3668ef86e30c68d2f09039/
> Please let me know if you need a detailed guide for the dark mode in addition to what we have in Zeplin or do you prefer to receive the list of changes per each page?
> 
> Thanks!
> 
> ![photo_2020-08-14 13 23 08](https://user-images.githubusercontent.com/69288176/90340407-a882fd00-e000-11ea-81d0-433e074bf9d6.jpeg)
> ![photo_2020-08-14 13 23 03](https://user-images.githubusercontent.com/69288176/90340408-aae55700-e000-11ea-881a-af5dbc63d46a.jpeg)
> <img alt="Screenshot at Aug 14 13-18-02" width="1519" src="https://user-images.githubusercontent.com/69288176/90340421-c05a8100-e000-11ea-90fd-40d9b5cd4428.png">

**Comment by Velua** [comment]
Sorry @katyarozenfeld we got our wires crossed and mislead you, because this is related to your original request it should remain in the original issue. I've closed #91 now and moved your feedback back in here.

Creating a new issue in this case would only been warranted if 
- We already fulfilled all requests made in the original issue. 
- Issue had been closed and passed it's review phase (Everyone was happy with it at the time including you)
- You have brand new changes/designs to make, outside of the original scope that was drawn in the original issue. 

Because we didn't fully achieve your original request and you've got further feedback on it, it should remain in this issue and be re-opened if necessary until we've fully completed it.

Thanks again for your rich and consistent feedback, we'll further work on our strategy to ensure we don't give you any mixed signals going forward.

**Comment by katyarozenfeld** [comment]
@Velua Thanks for making things clear!

**Comment by pingustar** [comment]
* [ ]  Tabs - "token"/"pool" text color - please fix

* [ ]  Search - "search" text color - please fix (should be lighter). Also relevant to typing mode - need to be 0A2540.

* [ ]  Tabs - blue line looks broken - "trapeze" shape

* [ ]  Please align tabs with table content. No need to make blue line wider than tab name.

* [ ]  Can we fix the width of the buttons? Just as it is in Zeplin? 132 px & 132 px

* [ ]  Pagination - Please replace icons to what we have in Zeplin

* [ ]  Pagination - Please change text color

Mobile

* [ ]  Please move "search" box to top right (screenshot attached)

* [ ]  Please fix spacing in statistics card (screenshot attached)

**Comment by pingustar** [comment]
@katyarozenfeld 

the v2/1 badge for darkmode is missing.

Any feedback to the latest changes.

Please disrecard the icons for now. I'll do them all at once. Might have a few questions soon about that.

**Comment by katyarozenfeld** [comment]
Bagde - https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f3cd63d2b6ae231d674608d/.

Re feedback - will check it right now.

**Comment by katyarozenfeld** [comment]
Just checked - everything looks great, except this one

- [ ] Please align tabs with table content. No need to make blue line wider than tab name.

**Comment by Velua** [comment]
Thanks @katyarozenfeld we've aligned the tabs with the content, now active in production and staging, still working on the badges.

**Comment by katyarozenfeld** [comment]
Thanks!

**Comment by katyarozenfeld** [comment]
@pingustar I'm still seeing this. Can you please fix?

Thanks!

<img width="816" alt="Screenshot at Sep 02 08-36-00" src="https://user-images.githubusercontent.com/69288176/91935988-a060d800-ecf7-11ea-8fbc-3f76cceadb76.png">

**Comment by pingustar** [comment]
fixed table alignment.
