### ISSUE TITLE
statistics data doesnt load the full amounts

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#657]
stats section, sometimes, show less amount of locked liquidity.
there is no error in console.

![image](https://user-images.githubusercontent.com/40430285/101277861-0ca01b80-37c0-11eb-9f62-bbe30511f6f5.png)
![image](https://user-images.githubusercontent.com/40430285/101277869-1cb7fb00-37c0-11eb-8ef6-f8e8694f17b6.png)

**Comment by ashachaf** [comment]
@Velua this is now a critical bug. 
Please prioritize it.

**Comment by Velua** [comment]
While I couldn't replicate this on prod I was able to find a glitch that caused this when I was messing with racing and made a patch. 
Let me know if you can continue to replicate.

**Comment by ashachaf** [comment]
Will try to reproduce on production.

**Comment by Velua** [comment]
@ashachaf has said this can be more easily replicated by throttling ones internet connection.

**Comment by Velua** [comment]
No update on this one? I'm still unable to replicate despite throttling.

**Comment by H34D** [comment]
> No update on this one? I'm still unable to replicate despite throttling.

yesterday is was looking into the timeout behaviour of the web3 provider but i had no luck reproducing or fixing this locally

**Comment by pingustar** [comment]
hotfix is deployed:
