### ISSUE TITLE
column selector for data/protect table

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#658]
as a user, i would like to manage the columns i see and make my view adjustable based on my needs.

1. when a user change the column view, save this data in a cookie or storage and use it on load.
2. when loading the table, check cookie/storage data and display only columns that are selected.
3. these columns are not part of the option to hide: protected, symbol and name, actions
3. default view if there is no cookie/storage data:
#### data table, pools view
- mobile and tablet: protected, symbol and name, liquidity depth, rewards, ~~fee~~, volume 24, fees 24h, apr, actions
- desktop: protected, symbol and name, liquidity depth, rewards, fee, volume 24, fees 24h, apr, actions
#### data table, token view
- mobile and tablet: protected, symbol and name, 24h change, price USD, liquidity depth, action
- desktop: protected, symbol and name, 24h change, price USD, liquidity depth, action
#### protection table
- mobile and tablet: initial stake, protected value, claimable value, ~~fees~~, ~~roi~~, apr, current coverage, action
- desktop: initial stake, protected value, claimable value, fees, roi, apr, current coverage, action

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1332%3A854
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1072%3A0
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=859%3A5
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1332%3A2192

**Comment by Velua** [comment]
@ashachaf closing as stale, let me know if it's not.
