### ISSUE TITLE
Metamask app not supported

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#659]
Multiple users reported that the metamask app (not browser extension) isn't supported in the app.
Reports were sent re. chrome OS and iphone.

**Comment by pingustar** [comment]
![image](https://user-images.githubusercontent.com/7262066/101338310-176cb600-387d-11eb-8bf4-daf11f538bde.jpeg)

**Comment by pingustar** [comment]
@yudilevi the user has to use the MetaMask App -> build-in browser in order to login and transact.

I have tested this on iPhone + Ropsten and it works fine.

**Comment by ashachaf** [comment]
confirm tests, you have to use metamask app browser to interact with dapps in mobile.
and once you do so, it works as expected.
