### ISSUE TITLE
deploy feature branches to individual firebase instance

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#665]
**Is your feature request related to a problem? Please describe.**
Right now we only have the staging environment to test features on a close to production environment. It would be easier to have different environments for each feature so we can test them individually and only use the staging environment for consolidation.

**Describe the solution you'd like**
Deploy a firebase instance per feature branch

**Describe alternatives you've considered**
Have more developer individual instances of firebase

**Comment by Velua** [comment]
How would this look technically? Could we have GitHub actions make one on the fly somehow? Then log the new Firebase address? Then when a branch is deleted a firebase instance is destroyed? 

No idea how this works billing wise.

**Comment by H34D** [comment]
> How would this look technically? Could we have GitHub actions make one on the fly somehow? Then log the new Firebase address? Then when a branch is deleted a firebase instance is destroyed?

yes this is what i was thinking of, maybe the name of the branch can be the name of the firebase instance as well

**Comment by Velua** [comment]
@pingustar Do you think this would be possible with GitHub actions?

**Comment by H34D** [comment]
details can be found here: https://firebase.google.com/docs/hosting/github-integration

**Comment by pingustar** [comment]
this would be pretty cool to have. But I feel like that it might be out of scope for the moment.

A compromise would be that we all have our own testing branch connected to a firebase instance.

**Comment by Velua** [comment]
All good, can wait till the new year.

**Comment by Ran73Cohen** [comment]
Implemented
