### ISSUE TITLE
dual sided protection freezes

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#668]
When selecting "stake and protect", once the pool drop down list is populated, the app freezes.

This doesn't seem to happen all the time and might be related to performance but it's consistent for some users.

Video of the issue -
https://gyazo.com/62aa7532edacfbf263b18fb58aab65d6

**Comment by sirius651** [comment]
Since the interface has changed, it is necessary to check again whether the issue is reoccurring. @yudilevi

**Comment by yudilevi** [comment]
Yup, still does. I think something we did caused the search option to be very very slow, probably the same issue.

**Comment by sirius651** [comment]
when I checked again, it seems to have been resolved along with #721

**Comment by H34D** [comment]
seems to be fixed, i cannot recreate it anymore
