### ISSUE TITLE
API3 token update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#672]
API3 token has incorrect icon on our system
please update to use this one
![Token Image_api3](https://user-images.githubusercontent.com/40430285/101606981-b542bb00-3a0c-11eb-80a7-5c99ff2834d8.png)

**Comment by pingustar** [comment]
@ashachaf 

cannot find "API3" in the token registry.

Following info is needed to add it:

```
{
    "image": "https://storage.googleapis.com/bancor-prod-file-store/images/communities/aea83e97-13a3-4fe7-b682-b2a82299cdf2.png",
    "contract": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
    "symbol": "ETH",
    "name": "Ether",
    "precision": 18
  }
```

**Comment by Velua** [comment]
Updated ```eth-tokens-registry```
