### ISSUE TITLE
add support for walletconnect wallet (part of onboard.js library)

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#674]
we would like to add support for walletconnect which is supported by onboard and requires us to enable it on load.

### current list (this is our code)
const wallets = [
  { walletName: "metamask", preferred: true },
  { walletName: "lattice", rpcUrl: RPC_URL, appName: APP_NAME },
  { walletName: "imToken", rpcUrl: RPC_URL, preferred: true },
  { walletName: "coinbase" },
  { walletName: "trust", rpcUrl: RPC_URL, preferred: true },
  { walletName: "dapper" },
  { walletName: "ledger", rpcUrl: RPC_URL },
  { walletName: "authereum" },
  { walletName: "opera", preferred: true },
  { walletName: "operaTouch" },
  { walletName: "torus" },
  { walletName: "status" },
  { walletName: "unilogin" },
  { walletName: "walletLink", rpcUrl: RPC_URL, appName: APP_NAME },
  { walletName: "meetone", preferred: true },
  { walletName: "mykey", rpcUrl: RPC_URL },
  { walletName: "huobiwallet", rpcUrl: RPC_URL },
  { walletName: "hyperpay" }
];

### updated code (based on their documnetation, please confirm)
https://docs.blocknative.com/onboard#wallet-modules

const wallets = [
  { walletName: "coinbase", preferred: true },
  { walletName: "trust", preferred: true, rpcUrl: RPC_URL },
  { walletName: "metamask", preferred: true },
  { walletName: "dapper", preferred: true }, 
  {
    walletName: 'trezor',
    appUrl: 'https://www.bancor.network',
    email: 'services@bancor.network',
    rpcUrl: RPC_URL
  },
  {
    walletName: 'ledger',
    rpcUrl: RPC_URL
  },
  {
    walletName: 'lattice',
    rpcUrl: RPC_URL,
    appName: APP_NAME
  }
  {
    walletName: "fortmatic",
    apiKey: pk_test_33B44C157E00E183, **//will send production key separately**
    preferred: true
  },
  {
    walletName: "portis",
    apiKey: PORTIS_KEY, **//will send production key separately**
    preferred: true,
    label: 'Login with Email'
  },
  {
    walletName: "squarelink",
    apiKey: SQUARELINK_KEY **//will send production key separately**
  },
  { walletName: "authereum" },
  {
    walletName: "walletConnect",
    infuraKey: INFURA_KEY **//optional**
  },
  { walletName: "opera" },
  { walletName: "operaTouch" },
  { walletName: "torus" },
  { walletName: "status" },
  { walletName: "unilogin" },
  { walletName: "walletLink" rpcUrl: RPC_URL, appName: APP_NAME }
  { walletName: "imToken", rpcUrl: RPC_URL },
  { walletName: "meetone" },
  { walletName: "mykey", rpcUrl: RPC_URL },
  { walletName: "huobiwallet", rpcUrl: RPC_URL },
  { walletName: "hyperpay" },
  { walletName: "wallet.io", rpcUrl: RPC_URL }
]

**Comment by pingustar** [comment]
@ashachaf please send me the keys and I'll update it.

**Comment by pingustar** [comment]
updated and going to staging now.
