### ISSUE TITLE
Incorrect decimals used in the add protection popup

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#675]
When showing the value you receive, it appears that 18 decimals are always used instead of the correct token decimals.

1. Go to liquidity protection page
2. Click the "stake and protect" button
3. Select the USDC pool
4. Put in a stake amount
5. Watch USDC in the "Value you receive" section, the value is much smaller than it should be

See example:
![image](https://user-images.githubusercontent.com/1134236/101690733-93295700-3a65-11eb-8dce-abac19e55f86.png)

**Comment by pingustar** [comment]
@yudilevi is this still happening? I am unable to reproduce.
