### ISSUE TITLE
liquidityProtection contract split

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#681]
due to byte size, we have split the liquidityProtection contract into two new contracts.
current contract: production contract
0x135742E6C5d70FC960090EdDBd9f3C6D0D494E99

updated contract structure:
1. liquidityProtection
ropsten contract: https://ropsten.etherscan.io/address/0xfe961fd7293bd5102357382cde0b6e4dd75d7338#code
2. LiquidityProtectionSettings
ropsten contract: https://ropsten.etherscan.io/address/0xff3ddf48b6ba7773e19b635b3bf0d339525a71cf#code

please make sure you know to use the correct contract to get the information you need.

**Comment by H34D** [comment]
will be done with #673 related to or duplicate of #669

**Comment by Velua** [comment]
Yeah looks like this is just a duplicate of #669 , closing.
