### ISSUE TITLE
Add support for type 3 converter

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#684]
Type 3 converter is a gas optimized version of the type 1 converter, specifically for standard pools (2 reserves and 50%/50% weights).
The interface is identical (except some legacy functions - see below) but since the type is different, some references might need to be adjusted.
Setting a fee queries the type today so that's one example the code needs to be updated, after pool creation.
There might be more references to the type as well so it requires checking those areas.

The only interface change (other than the actual type) is the `fund`/`liquidate` functions that were removed. `addLiquidity`/`removeLiquidity` should be used instead.
Note that the converter also supports dedicated simplified add/remove liquidity functions but no need to integrate that right away.

The converter registry is updated such as that when a caller requests to create a standard type 1 pool, type 3 is actually created, so no code change requires there. Same goes for the upgrader - standard type 1 pools will be upgraded to type 3 pools.

Ropsten is updated with the changes.

**Comment by H34D** [comment]
done https://github.com/bancorprotocol/webapp/commit/71be6e7dd8b0c39b63a42e1d319fb1da1d962fc0
