### ISSUE TITLE
Tech Depth Proposal - Move prettifyNumber function to BaseComponent

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#686]
As we use the helper function 'prettifyNumber' in a high number of components I have refactored all components to align the usage of this component and no more import is needed going forward.

**Comment by pingustar** [comment]
Currently blocked because moving the 'prettifyNumber' function to the base component class breaks the testing of 'LabelContentSplit.spec.ts`

I talked to @sirius651 about this and it is because we rely on 'BigNumber' and 'Numeral' dependencies. As it will be easy to get rid of the 'numeral' library it wont be as easy to remove the 'BigNumber' dependency.

@sirius651 is looking into options of mocking the required data.

I have started to rewrite the 'prettifyNumber' function as a pure helper. Also I started writing a test for this pure helper function. It is WIP as we experience rounding issues since I tried to do it without 'BigNumber'

**Comment by Velua** [comment]
Is there a reason we don't want to utilise ```BigNumber``` ?

**Comment by Velua** [comment]
@pingustar

**Comment by pingustar** [comment]
Misunderstanding between Will and I. He said that testing functions that utilise other libraries won't work. But he was referring to vuex not some random third party libraries. So we can keep using `BigNumber`.

Closing this.
