### ISSUE TITLE
stats - missing total volume data

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#690]
no error in console.
we see volume on the pool level.
it is only missing on the stats summary.

![image](https://user-images.githubusercontent.com/40430285/102008308-28636e80-3d38-11eb-8306-a60b55fcabe5.png)

**Comment by ashachaf** [comment]
@Velua this might be something with the multicall?

**Comment by pingustar** [comment]
It looks like we are getting faulty data for some pools. One example is ANT/BNT pool.

I have added another check to the calculation to skip the faulty pools. But we need to get to the bottom of this issue of receiving faulty data. It keeps breaking stuff.
