### ISSUE TITLE
adding data refresh indication

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#692]
@Velua 
this is first a question on possabilities.
IF we have a process that pulls fresh data every few seconds, can this be indicated on the data table (and later on protection table as well)?
see example:
![image](https://user-images.githubusercontent.com/40430285/102010206-4a172280-3d45-11eb-9a68-c24de963aecf.png)

**Comment by Velua** [comment]
Yes it's possible, though how frequently would we want it to update? The more frequent the more concurrent request seats we're going to be utilising over time.

**Comment by ashachaf** [comment]
**as a way to show and indicate to the user that data is updating on the main data table, we would like to implement the same logic as the protection tab rewards animation.**

on load - numbers should run up 
every 15 seconds, numbers should run the diff between current and new value
this should **ONLY** be done on the **statistics** section on the data page.

#### the specifics from the claim rewards task:
**Data movement**
in order to show movement, we would like to use some type of increasing number effect.
on refresh/load: start all values at 0 and grow them to the number they should be. Claimable should take 3sec while total rewards should take 5sec to load.
total rewards: if we automatically refresh the data every 15 seconds, break the delta increase and increase the value over a 15sec time span.
claimable rewards: 
when user claims rewards, count down to 0 in a span of 3 seconds. 
if we automatically refresh the data every 15 seconds, break the delta increase and increase the value over a 15sec time span.
code sample to the effect: https://codepen.io/duvander/pen/KXOpXw

**Comment by ashachaf** [comment]
@Ran73Cohen is this still open?

**Comment by Ran73Cohen** [comment]
> 
> 
> @Ran73Cohen is this still open?

We can merge [this](https://github.com/bancorprotocol/webapp/pull/1096) but do we want the 15 seconds refresh or not?
