### ISSUE TITLE
Remove Liquid V2 - Wrong Output displayed

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#7]
Should not be 0 WBTC

<img width="404" alt="image" src="https://user-images.githubusercontent.com/7262066/89395820-1892a880-d70e-11ea-9ed1-f13f3d440af8.png">

**Comment by Velua** [comment]
<img width="1024" alt="89395684-f436cc00-d70d-11ea-8fee-e5dd55b210b2" src="https://user-images.githubusercontent.com/8017434/89477227-14c75a80-d7d0-11ea-9df7-27ef8c89aa74.png">
