### ISSUE TITLE
self service pool creation. (v1 pools)

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#70]
since that v1 pool creation is a simplified process, we would like to enable the option for users to create a bancor v1 pool.

https://zpl.io/bLzRA0B

disable the option to select v2 pools until we have the bancor v2 pool creation ready.

**Comment by Velua** [comment]
This step process/wizard would take a fair bit of dev time to deliver, xNation creates ETH v1 pools by hardcoding 50 50 CW and token symbol names, precision, etc. 

Would you like us to put in a xNation experience for v1 creation now then work on these extra features later? Or not support v1 creation at all unless the steps are delivered as in the mockups?

**Comment by yudilevi** [comment]
@Velua do you have a rough estimation for the full solution?

**Comment by Velua** [comment]
2 days of UI, 2 days of logic at least, probably another dev day of testing/flattening out bugs.

**Comment by Velua** [comment]
@yudilevi

**Comment by Velua** [comment]
Also from a UX experience, do we want to allow the user to determine CW? My thoughts previously was that a custom CW was so niche it would serve only the 1% and bother the 99%.

**Comment by Velua** [comment]
![Screenshot at 2020-08-10 20:47:07](https://user-images.githubusercontent.com/8017434/89775226-ba6d2780-db4a-11ea-99fc-27c191b5145c.png)

Same sort of idea, how many pools do we think would deviate from the traditional pool name and token symbol? Don't think the UI displays them either after this.

**Comment by Velua** [comment]
@pingustar currently create pool is looking at the vxm.bancor.tokens but should instead go for ```primaryReserveChoices``` passed  the ID of the secondary reserve token, which would just be the ID of the BNT token for now.

**Comment by Velua** [comment]
@pingustar Done a base example in branch ```createPoolEth```

- [ ] Add a component which allows adjusting of percentages, current example has a token field which is redundant. 
- [ ] Upon closing the modal used to create a pool lets just have it forward to the add liquidity page of this pool 
- [ ] I've half done a getter which warns the user if a pool already exists, this needs to be further configured to check the reserve weights. 
- [ ] Should not use ```vxm.bancor.tokens``` at all here, should be using only primary and secondary reserve token choices. Ensure the percentage component is minimal, shouldn't be so opionated as to expected a ```ViewToken``` just the essential ```logo```, ```symbol``` should suffice.
