### ISSUE TITLE
Update OMG token logo & project name

### ISSUE THREAD

**Issue by AdamOnChain** [bancorprotocol/webapp#700]
Rename OmiseGo to "OMG Network" and change OMG token logo to the image posted here: https://github.com/omgnetwork/omg-childchain-v2/blob/master/docs/assets/logo.png

**Comment by jet86** [comment]
Official OMG Network brand guidelines and assets are available here: [https://omg.network/press/](https://omg.network/press/)
The brand assets zip file contains the logo in a range of formats and options so that you can use the option that works best in various contexts.

**Comment by Velua** [comment]
@sirius651 can update the ```eth-tokens-registry``` gave you permissions at https://github.com/Velua/eth-tokens-registry/invitations

**Comment by sirius651** [comment]
Updated
