### ISSUE TITLE
withdraw alert on price deviation

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#701]
as a user, when i try to withdraw my protected position, i would like to be informed if there is anything that can cause it to fail.
in this case, we check spot price vs averageRate and if the deviation is greater than 0.5%, the transaction will fail.

### in the withdraw window, check price deviation:
from task #480 

> calculate the average rate
> call function recentAverageRate() with the (reserve token address) the user is staking for protection
> response include 2 values, numerator and denominator
> average rate = numerator/denominator
> calculate pool spot rate
> user's protected reserve will be indicated as "primary reserve"
> spot rate = secondary reserve balance / primary reserve balance
> on liquidity protection contract
> identify what is the allowed max deviation
> call function AverageRateMaxDeviation()
> response is percentage in ppm. meaning, if the result is 10000 -> 1%
> check if the transaction can be executed:
> IF
> `(1000000 - AverageRateMaxDeviation) / 1000000 < avg / spot < 1000000 / (1000000 - AverageRateMaxDeviation)`
> 

#### error message:
Due to price volatility, withdrawing your tokens is currently not available. Please try again in a few seconds.

#### CTA functionality:
disable the call to action button

#### mockcup:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1506%3A2

**Comment by pingustar** [comment]
updated the code. @ashachaf how can I trigger the price deviation to test this error?

**Comment by pingustar** [comment]
Fixed an error with vbnt balance fetching. And the price deviation shows up for one of my positions, so I assume it works. Closing this, please review and reopen if need be @ashachaf
