### ISSUE TITLE
LiquidityProtectionSettings contract address should be retrieved from the LiquidityProtection contract

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#703]
LiquidityProtectionSettings contract address is taken from the contract registry. However, the registry isn't supposed to include that contract and we'd like to reduce dependencies on the registry.

The LiquidityProtectionSettings contract address should instead be retrieved from the LiquidityProtection contract (`settings` property).

Once this is deployed, please let us know so we remove the protection settings address from the contract registry.

**Comment by Velua** [comment]
Done
