### ISSUE TITLE
price deviation error - process update needed

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#704]
half way in the process of staking liquidity, the message on the site changed leaving me with an over priced transaction that will fail.

process i did:
swap bnt to ant
data -> stake -> single side
stake ant
trigger approve transaction -> sign it
while waiting for the stake transaction, the error appeared on the site
metamask transaction showed up with error indication and extreme gas price.

![image](https://user-images.githubusercontent.com/40430285/102106170-eb32d580-3e38-11eb-9150-bf6d0d03c33f.png)

how to fix:
need to understand what data you have half way in the process

**Comment by Velua** [comment]
So you're saying you never received the error on the left until after you hit approve?

**Comment by H34D** [comment]
i think this has been discussed on telegram some time ago where someone on twitter mentioned something like this. It seems a bug in the contract that triggers when numbers with lots of decimals is used leading to extreme gas usage / gas estimations. maybe @yudilevi still has the link to the tweet?

**Comment by H34D** [comment]
found it https://twitter.com/ChainlinkShill/status/1331659103006044162

**Comment by ashachaf** [comment]
> So you're saying you never received the error on the left until after you hit approve?

between the time i start the process to the point i get the actual "stake" transaction to sign, price can change and cause this to no longer be valid.

https://streamable.com/qpa1j3

**Comment by pingustar** [comment]
@ashachaf is this still happening?

**Comment by ashachaf** [comment]
potentially, yes.
if a large trade is confirmed on the blockchain while my approve is being processed, i would have this issue as a result.

we should check the deviation again after approve / before the stake liquidity and:
1. IF no issue -> proceed as normal
2. IF deviation is above defined limit -> show popup with indication on the price deviation issue.
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2358%3A0

**Comment by Velua** [comment]
@ashachaf treating this as stale, let me know if it's not.

**Comment by ashachaf** [comment]
we should add a check after "approve" and before we trigger the "stake" transaction to make sure the transaction is not set to fail due to price deviation issue.
