### ISSUE TITLE
Left menu - move the swap above the data page and have it be the default

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#706]
Since we want to create a better experience for traders (vs LPs), we'd like the swap page to be the default page when loading the app.
So it should be the default as well as the first item on the left menu.

**Comment by pingustar** [comment]
I will move swap to the top.

@yudilevi can you check the dns zone records. I believe https://app.bancor.network forwards to the data page. If thats the case we would need that to point to the root of the website. I can then take it from there.

**Comment by pingustar** [comment]
going straight to production. Will be live in 5 min.
