### ISSUE TITLE
Statistics do not load

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#713]
**Describe the bug**
Loading the page is missing the statistics 

![image](https://user-images.githubusercontent.com/40430285/102180075-f590b600-3eb0-11eb-9ddd-550e04305814.png)

**To Reproduce**
On mobile this is what I see every time I refresh

**Comment by pingustar** [comment]
cannot reproduce. @ashachaf did this resolve itself or are you still experiencing this issue?

**Comment by Velua** [comment]
![Screenshot_2020-12-16-11-20-36-09.jpg](https://user-images.githubusercontent.com/8017434/102292478-f3058d80-3f90-11eb-9f12-a7e0737ed6f5.jpg)

Can't reproduce either.

**Comment by ashachaf** [comment]
i cannot reproduce.
might be related to slow wifi or something.
