### ISSUE TITLE
app is extremely slow to move

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#721]
**Describe the bug**
every interaction with the app takes 3-5 seconds to actually happen. clicking a button takes 3-5 sec to execute the action.

**To Reproduce**
go to bancor.network
click data
click stake "+"
(but pretty much any click result in the same thing)

go to bancor.network
click data
click the search and type "dai"

https://streamable.com/2styt3

**Comment by Velua** [comment]
@H34D I've expanded on your branch on mine, what part is remaining as a draft? Just so I don't merge something only half done on your end. 

Looking at the performance tab on Chrome I'm finding a lot of time being spent destroying the Vnodes in what looks like in one of the table components, even when I just limit relays to 5 it still takes longer than what it should to move on.

**Comment by Velua** [comment]
@H34D 
Please review my changes and compare staging to prod, see if it's worth making the shift over. 

Just gonna drive home now, will check in with you after that before retiring, handing over to you.

**Comment by H34D** [comment]
> @H34D
> Please review my changes and compare staging to prod, see if it's worth making the shift over.
> 
> Just gonna drive home now, will check in with you after that before retiring, handing over to you.

ok, i can take it from here again.

**Comment by H34D** [comment]
fixed, please reopen if still happening
