### ISSUE TITLE
gas estimation is too high on the transactions

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#726]
as a user, i would like to receive a cost estimation that is close to the actual cost.
currently, it seems we average 35%-45% over estimate the gas required for every transaction and the result is "scaring" people off by perceived higher prices (eventually, the user will pay 35%-45% less on the transaction).

#### example:
go to swap
attempt to execute eth->link swap
estimation: 462,636 gas units
actually used: 294,403 (63.64%)
https://etherscan.io/tx/0x577edaad990a2db84b02f52d3267ab413b2a30cc2e3d7d1d20b82805f51f7ace

#### approve transaction:
go to swap -> convert link->eth and the first transaction is approve.
estimation: 70,000 gas units
actually used: 14,628 (20.9%) **(this is an extreme buffer!)**
https://etherscan.io/tx/0x5dce29176ecdb2a7410e659bde806568cdca0bed43cedeb45d6c3e37c03bff75

### we would like to aim for 10%-15% gas units buffer on the transactions we build.

**Comment by Velua** [comment]
@yudilevi Can we reliably hard code the gas cost of the transactions were performing? Atm it's just Web3 estimate based.

**Comment by yudilevi** [comment]
@Velua not really, that can lead to all sorts of problems. check what others are doing and find out why our code produces different limits.

**Comment by Velua** [comment]
@H34D I'm having issues getting the ```estimateGas``` function to work, can you attempt it on your machine in case there's some Web3 issue?

**Comment by H34D** [comment]
i will take a look at it

**Comment by Velua** [comment]
Awesome, let me know how you go @H34D

**Comment by H34D** [comment]
i wrote some code but got stuck when testing it against ropsten

**Comment by Velua** [comment]
Can do this on mainnet, such promise should resolve before you have to accept signing any transactions.

**Comment by H34D** [comment]
i don't have funds so the frontend wont let me through at all

**Comment by H34D** [comment]
Right now we hardcore the estimated gas to 70k here

```
        return this.resolveTxOnConfirmation({
          tx: tokenContract.methods.approve(
            approval.approvedAddress,
            approval.amount
          ),
          gas: 70000
        });
```

A better solution would be to use the estimate gas method. This requires the ABIs to be precise otherwise web3 will not be able to estimate properly and created failed txs. For the approve method it is mostly likely that the ABI is precise.

```
        const tx = tokenContract.methods.approve(
          approval.approvedAddress,
          approval.amount
        )

        return this.resolveTxOnConfirmation({
          tx,
          gas: await tx.estimateGas()
        });
```

the best solution would be to not supply a gas limit and let web3 decide what to put.

**Comment by ashachaf** [comment]
can you deploy to staging so we can check the estimations it gives?

**Comment by Velua** [comment]
Yes and does the ```estimateGas``` method actually work though? Or does it throw?

**Comment by H34D** [comment]
i was not able to test it because ropsten is not available

**Comment by Velua** [comment]
Use mainnet, write whatever dodgy code you need to skip the frontend warnings or roadblocks. I'm trying to determine if such a function throws on your environment compared to mine.

**Comment by H34D** [comment]
> Use mainnet, write whatever dodgy code you need to skip the frontend warnings or roadblocks. I'm trying to determine if such a function throws on your environment compared to mine.

i did that, i will give it another check against ropsten when its back

**Comment by Velua** [comment]
So it worked on mainnet? You got a estimate number back?

**Comment by ashachaf** [comment]
@H34D 
lets try to put this on staging

**Comment by H34D** [comment]
> @H34D
> lets try to put this on staging

ok

**Comment by H34D** [comment]
finally tested against ropsten, it sits in a feature branch because staging is not functional right now

**Comment by H34D** [comment]
i gave it another test and brought down the gas limit by more than 100k on the convertByPath operation.

before:
<img width="455" alt="Screenshot 2021-01-21 at 10 22 42" src="https://user-images.githubusercontent.com/13647606/105330676-dc2b0a00-5bd2-11eb-804d-b1a561d54d2c.png">

after:
<img width="452" alt="Screenshot 2021-01-21 at 10 22 47" src="https://user-images.githubusercontent.com/13647606/105330672-db927380-5bd2-11eb-916c-5a70e0954a33.png">

**Comment by yudilevi** [comment]
great!

**Comment by H34D** [comment]
given up for #866

**Comment by H34D** [comment]
done
