### ISSUE TITLE
protection table - unable to load protected positions

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#728]
go to protection tab

![image](https://user-images.githubusercontent.com/40430285/102279669-75ac2f80-3f34-11eb-8e7e-678681b2a826.png)

**Comment by H34D** [comment]
i think this was fixed by the change of the block limit with alchemy? https://github.com/bancorprotocol/webapp/pull/729

does this still happen for you @ashachaf ?

**Comment by pingustar** [comment]
I noticed that APR is showing 0.00% for all my positions:

![image](https://user-images.githubusercontent.com/7262066/102365608-0710b580-3fb8-11eb-8b9f-a55a2203d31e.png)


No error logged.

**Comment by H34D** [comment]
> I noticed that APR is showing 0.00% for all my positions:
> 
> ![image](https://user-images.githubusercontent.com/7262066/102365608-0710b580-3fb8-11eb-8b9f-a55a2203d31e.png)

i cannot reproduce that, works flawless on ropsten. any more details?

**Comment by ashachaf** [comment]
also noted in #750 
no errors in console

**Comment by H34D** [comment]
> go to protection tab
> 
> ![image](https://user-images.githubusercontent.com/40430285/102279669-75ac2f80-3f34-11eb-8e7e-678681b2a826.png)

it has been fixed by alchemy updating their limits
