### ISSUE TITLE
Support 0 effective reserve weights

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#73]
App fails to support V2 pools with no reserve weights, expecting data to be there that won't be and throwing.

**Comment by Velua** [comment]
@yudilevi Let me know when we've got an empty pool on ropsten.

**Comment by yudilevi** [comment]
@Velua the latest version doesn't do that so you'll need to emulate it (or create a new pool and not even activate it)

**Comment by yudilevi** [comment]
Btw, if the pool isn't activated, we shouldn't show it - so need to make sure that's the case for v2 (regardless of the weights).
