### ISSUE TITLE
Refactor navigation

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#730]

**Comment by Velua** [comment]
Components ```SideBar.vue```, ```SidebarBottom.vue```, ```SideBarLeft.vue``` has some pretty atrocious in house routing logic that isn't in best practices with the Vue Router library, please refactor entirely with a good understanding of Vue Router best practices, feel feel to start these from scratch.

**Comment by pingustar** [comment]
This might be worth checking out: https://bootstrap-vue.org/docs/components/sidebar

I think it would be kind a cool to be able to hide the sidebar, or have a minimized version of it that just shows the icons. But this is just a thought. @ashachaf what do you think about that?

- [ ] While doing this refactor, lets also add the 'external link' icons to the menu items that open in a new tab.
- [ ] Lets see if we can center the main content - it looks kind a weird when the text of the blue bar isnt aligned with the content.

**Comment by sirius651** [comment]
![스크린샷 2020-12-28 오후 4 13 25](https://user-images.githubusercontent.com/1606820/103197163-e5ed8480-4928-11eb-9120-d0a845df4b12.png)

![스크린샷 2020-12-28 오후 4 13 32](https://user-images.githubusercontent.com/1606820/103197191-f0a81980-4928-11eb-9b53-3a39fdffa94d.png)

Added sidebar for replacing with bottom bar. What does it look like? It seems confused drawer button with other top buttons. @ashachaf @pingustar

**Comment by sirius651** [comment]
As discussed with @ashachaf , we decided to stop implementing this sidebar. And will going to #780

**Comment by Velua** [comment]
Alright @sirius651 just make sure that the refactoring idea of this one is fulfilled in #780 don't be afraid to delete components or re-work how routing works here.
