### ISSUE TITLE
Review SelectPoolRow.vue

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#731]
I've discovered some funky looking code in ```SinglePoolRow.vue``` 

```
  get positions(): PoolTokenPosition[] {
    return vxm.bancor.poolTokenPositions.filter((x: PoolTokenPosition) =>
      this.getPoolLabel(x.relay.reserves)
    );
  }
```

It appears ```getPoolLabel``` simply returns a string out of the reserves, in which case this is going be truthy so long as there's reserves in a relay?

@pingustar can I get your review of this.

**Comment by pingustar** [comment]
yea no idea why I added the filter there. Removed it.
