### ISSUE TITLE
pool creation - remove usdb option as base reserve

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#743]
when a user wants to create a new pool, we allow an initial selection between bnt and usdb as the base token that connects the pool to the network.

please remove the option to select usdb as an option.
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1564%3A2

**Comment by pingustar** [comment]
done, going to staging now.
