### ISSUE TITLE
space available new function

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#744]
we have decided to move the "space available" calculation to the contract level and prevent any logical calculations outside it. this will simplify the process for any external dev and integrators in the future.

### new function:
```poolAvailableSpace(poolAnchor)```
returns an array of two amounts
base token, bnt token

the return value is the available space for each reserve in the pool in wei and requires to normalize it based on the token's decimals.
for example, usdc/bnt pool:
usdc: 6 decimals
bnt: 18 decimals

**Comment by barakman** [comment]
Added in https://github.com/bancorprotocol/contracts-solidity/pull/507

**Comment by H34D** [comment]
so there will be another smart contract upgrade then?

**Comment by barakman** [comment]
@H34D : Yup.

**Comment by ashachaf** [comment]
this implementation should wait until the new contract is deployed.
@H34D

**Comment by ashachaf** [comment]
new contract is live on mainnet.
please implement this process.

new contract: 0xc9D9dc719C49edfc6bf9e0F0400Fc341cE93C298
