### ISSUE TITLE
User unable to remove single sided liquidity (insufficient vBNT balance)

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#748]
Insufficient vBNT balance even though the user has enough balance.
Potentially a rounding issue?

![image](https://user-images.githubusercontent.com/1134236/102604173-b3b77800-411b-11eb-899f-03dd12da2b77.png)

**Comment by pingustar** [comment]
cannot replicate. Do we have information if the user has been able to withdraw by now?

**Comment by ashachaf** [comment]
user indicated this might have been a result of switching wallets and vBNT balance not updating.
this issue was addressed in task #752
