### ISSUE TITLE
protected table - missing APR values

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#750]
![image](https://user-images.githubusercontent.com/40430285/102707741-3e2be300-42a6-11eb-8023-e38b5c396d78.png)

missing APR values.
no error in console.

**Comment by ashachaf** [comment]
duplicated. closing.

**Comment by H34D** [comment]
i cannot reproduce this on ropsten, how did you get this @ashachaf ?

**Comment by H34D** [comment]
and most importantly: what are the expected values?

**Comment by ashachaf** [comment]
reference task that use the base APR caluclation and average it out for the data table. protection table use single side APR as it indicates the APR for the token side you have the position in.
https://github.com/bancorprotocol/webapp/issues/392

**Comment by H34D** [comment]
fixed https://github.com/bancorprotocol/webapp/commit/afe3580c263124543ed8baf1877ef5841c4c419a

**Comment by H34D** [comment]
i created a PR. @pingustar can you nurse this through to production please? https://github.com/bancorprotocol/webapp/pull/767

**Comment by H34D** [comment]
> i created a PR. @pingustar can you nurse this through to production please? #767

already merged
