### ISSUE TITLE
Voting - create proposal window doesn't close until the transaction is mined

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#751]
When creating a new proposal, the proposal window stays open while the tx is pending which makes the user think the action didn't register and can cause them to create another proposal

1. Vote screen
2. Click the new proposal button
3. Fill in the details and hit the "propose" button
4. Sign the tx
5. The new proposal window stays open

The new proposal window should be replaced by the tx submitted window.

Tested on desktop/chrome.

**Comment by Velua** [comment]
@sirius651 did this get done?

**Comment by sirius651** [comment]
@Velua  yes, done.
