### ISSUE TITLE
unstake bnt position - not updating vBNT balance on frontend

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#752]
when removing bnt position, wee check vBNT balance first and indicate if there is a possible error.
if a user perform several withdrawals one after the other,  frontend doesnt fetch updated vBNT balance, as a result does not indicate if balance is not sufficient and allow user to trigger metamask transaction that will result in an error.

### reproduce:
- go to protection table
- find a bnt position that is larger than current balance of vBNT
- identify where the error inidication happens
- withdraw a different bnt position
- once confirmed, go back to the first position and try to withdraw it.

video shows how when trying to withdraw the same amount after page loads and another position was withdrew, there is a metamask error without frontend alert.

https://streamable.com/npu1yx

### possible solution:
when loading the withdraw window, make sure you refresh vBNT balance every 15sec.

**Comment by pingustar** [comment]
fixed.

I have added balance fetching everytime you visit the withdraw page + an interval to check every 10 sec while on the withdraw page.

I also added a bit more context to the error, it now shows how much vBNT you are missing.

![image](https://user-images.githubusercontent.com/7262066/102785843-e3c27d80-439e-11eb-8086-cba2cc4362c5.png)
