### ISSUE TITLE
Move Votes to the 'Done Proposal'-Tab

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#755]
- [ ] Move Votes that are done to the 'Done Proposal'-Tab
- [ ] migrate done proposal component to utilize the data table

**Comment by H34D** [comment]
> * Move Votes that are done to the 'Done Proposal'-Tab

well, this happens automatically once the right methods have been called on the governance contract. You can either call tallyVotes or execute on the contract. Once one of them is executed they will show up under done.

**Comment by pingustar** [comment]
ah gotcha. so this is something that @yudilevi has to do on a contract level?

**Comment by H34D** [comment]
> @H34D ah gotcha. so this is something that @yudilevi has to do on a contract level?

basically everyone can do it, they are public once the voting period has expired. It is only costing gas so it might be good to do it when the blockchain is not so expensive.
