### ISSUE TITLE
swap tokens - rate toggle

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#757]
as a user, i would like to have the option to toggle the rate of the assets in display.

when i click the rate area (where it says "1 BNT = 0.0023467 ETH", you should display the inverse rate 

example:
set the swap window to convert from ETH->BNT, rate will be: "1 ETH = 489.405610684 BNT"
click the rate area
update the rate to display the inverse rate (as if i am setting the swap window to BNT->ETH): "1 BNT = 0.002039102 ETH"

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1328%3A7

**Comment by pingustar** [comment]
@ashachaf can you check staging. The math seems correct. But there is a difference in swapping BNT->ETH and ETH->BNT - I am not sure if that is expected or not.

Please double check.

**Comment by pingustar** [comment]
Checked with Asaf. Done.
