### ISSUE TITLE
approve - improved logic to prevent approve transaction when not needed

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#758]
we force approve 0 on all tokens.
however, some tokens support approve amount if current approve is not 0.

what to do?
1.  check user current approve: IF current approve amount > amount we need, do not trigger approve and only trigger:
- transaction
2. run a check with "approve {amount}", if web3 doesnt return any error/issue, 
- trigger approve {amount}
- transaction 
3. else, if approve {amount} returns error, it means that we need to trigger:
- approve 0
- approve amount
- transaction

**Comment by Velua** [comment]
Moving to #727
