### ISSUE TITLE
Disable pool token protection

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#759]
## Goal
Remove redundancy of processes and alight the app with our main single side staking flow.

#### Stake for protection flow
following the click on the "stake" CTA:
- open the pool selection window. following a user selection
- open the single side staking popup and add the blue text box (remove the single/dual side protection selection popup)
- https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1595%3A0

#### Add liquidity flow
- IF the pool support single side staking, open the single side staking popup (add the blue text box)
- https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1595%3A0

#### Pool option
1. Join a pool -> follow the same process as “data->add liquidity”
2. Existing pool -> protect my pool tokens:
- remove the CTA indicating "Protect My Pool Token"

**Comment by ashachaf** [comment]
single side staking error message update:
current message:
ALEPH limit reached. Additional BNT liquidity should be staked to allow for ALEPH single-sided staking. Alternatively, provide dual-sided liquidity (BNT+ALEPH)

updated message:
ALEPH limit reached. Additional BNT liquidity should be staked to allow for ALEPH single-sided staking. 

![image](https://user-images.githubusercontent.com/40430285/102871150-bd581d00-4446-11eb-963b-66d6ea94f55f.png)

**Comment by ashachaf** [comment]
data->add liquidity
check if BNT reserve balance > 1000, open single side.
otherwise, open dual side option.

protection -> stake -> token selection
if pool bnt reserve is < 1000, do not show it in the list.

1000 is a value we have in the contract so you should use it from there.
contract protoectionSettings
https://etherscan.io/address/0xd444ec18952c7cAf09636f21807683DaCC1d7dA9#readContract
function: minNetworkTokenLiquidityforMinting
return the min amount of bnt in the pool to allow single side staking.

**Comment by pingustar** [comment]
done, going to production now.
