### ISSUE TITLE
Pool whitelist is still taken from the protection store contract instead of from the protection settings contract

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#760]
The pool whitelist was moved from the protection store to the protection settings contract.
The webapp still uses the old location which means that whitelisting a pool isn't reflected in the app.

Example: SNX is currently whitelisted but has no "shield" in the app.

**Comment by H34D** [comment]
> The pool whitelist was moved from the protection store to the protection settings contract.
> The webapp still uses the old location which means that whitelisting a pool isn't reflected in the app.
> 
> Example: SNX is currently whitelisted but has no "shield" in the app.

what is the field to query on the settings contract?

**Comment by H34D** [comment]
found it

**Comment by H34D** [comment]
fixed
