### ISSUE TITLE
User reported that ledger wallet isn't working in the app

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#761]
Only info we got:
"When I select a Ledger wallet here http://app.bancor.network page - nothing happens".

No idea if we ever tested it but it should be tested and confirmed working.

**Comment by pingustar** [comment]
I have a Ledger, just need to find it and set it up.

**Comment by pingustar** [comment]
tested, and works fine.

Login, loads balances, can confirm transaction.

Only worked on mainnet though. Ropsten didnt load the balances.
