### ISSUE TITLE
pool tokens - remove liquidity (withdraw) popup update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#762]
we would like to update the withdraw pool token popup.
swap->pool->remove liquidity
![image](https://user-images.githubusercontent.com/40430285/102800200-36f6f900-43bc-11eb-82db-f9516285cfd5.png)

current screen:
![image](https://user-images.githubusercontent.com/40430285/102800244-470ed880-43bc-11eb-8fbb-1b01fb13a59b.png)

new design:
- when the user select %, calculate how much from his pool token to withdraw. example, if the user has 100 pool tokens, and indicates to withdraw 50%, the transaction would calculate the reserve value of 50 pool tokens.
- https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1605%3A445

**Comment by pingustar** [comment]
done. Going to staging now.
