### ISSUE TITLE
pool selection popup - slow to response

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#768]
pool selection popup can be opened from different flows.
some flows cause it to have performance issues and be extremely slow.

fast flow:
protection tab -> stake -> single side staking
search and pool selection response immediately.

slow flow:
protection tab -> stake -> single side staking -> select a pool -> click the pool to select a new pool
try to search or select a pool

slow flow 2:
swap tab -> pool -> join a pool 
try to search or select a pool

**Comment by Ran73Cohen** [comment]
@ashachaf  All of them are fast for me check it again to make sure and we can close this

**Comment by ashachaf** [comment]
seems that the new API is fixing this issue.
