### ISSUE TITLE
Data - pool page - changed UI for 3 and more tokens

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#77]
We've added a few changes to UI in order to be able to show 3 and more tokens on "pool" page. 

1. Pool stats and info on top left, graph on right
2. Pool tokens table below (new), displaying token name/weight, token address, amount of pooled tokens and their usd value.

**Links to Zeplin**
- Desktop: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f1d2825d4821138d9df3a8f/
- Mobile: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f1d2824e1f46e42e4224608/
- Mobile with 3 buttons: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f32a7b9f661b421a170b1bd/

<img width="1322" alt="Screenshot at Aug 11 17-36-24" src="https://user-images.githubusercontent.com/69288176/89911240-dd0a4980-dbf9-11ea-8664-3fb9a3607d7a.png">

**Comment by Velua** [comment]
@katyarozenfeld Forgive me if I've missed it, do we have this pool detail page for v2 pools? As perhaps there should be some there should be some more distinction between a connector weight on v1 pools and effective reserve weights on v2 pools as they're not the same thing. What do you think @yudilevi  ?

**Comment by yudilevi** [comment]
yup, there should be something that reflects the difference between constant weights and dynamic weights

**Comment by Velua** [comment]
> yup, there should be something that reflects the difference between constant weights and dynamic weights

@katyarozenfeld As @yudilevi said can we get the mockups to guide us on how this is communicated to the user?

**Comment by katyarozenfeld** [comment]
@yudilevi I thought this page will be the same for V1 and V2 pools. Is this important for users to see the difference between constant and dynamic weights? I think in V2 the pie chart can automatically being modified according to the changes in weights...please correct me if I'm wrong.

**Comment by yudilevi** [comment]
@katyarozenfeld @Velua I think the difference should be pretty minor, just an indication that it's type = 2 and maybe something that shows that weights are dynamic.

**Comment by katyarozenfeld** [comment]
@Velua Here is a link to V2 pool page mockup in Zeplin: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f3a9efb48bee82848f4b2a7/

We decided to add a tooltip explaining that V2 pools have dynamic token ratio.

Thanks!

<img width="420" alt="Screenshot at Aug 17 18-34-21" src="https://user-images.githubusercontent.com/69288176/90414335-500f3680-e0b8-11ea-9af5-2a4f087855b4.png">
