### ISSUE TITLE
Show the user how much BNT has to be added to a pool in order to open up more space for TKN

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#772]
It's currently unclear how much BNT (minimum) needs to be added to a pool in order to start opening up space for more TKN.
Would be useful to show that number somewhere in the app.

@ashachaf need your input here on design.

**Comment by ashachaf** [comment]
this was discussed with @nhindman23 and indicated this might not be a valuable data point for the users.

**Comment by pingustar** [comment]
@ashachaf this is the same as #775 or?

Going to close this and lets continue at #775 as we have the calculations there.
