### ISSUE TITLE
add indication of space available

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#775]
### in space available
**IF TKN space available is smaller than 1**, add indication to show how many bnt are needed to open up space for tkn side
amount needed to open up space: {amount of bnt to free up space for 1 tkn staking}
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1696%3A2
info bubble should open tool tip:
text: For more information [click here](https://docs.bancor.network/faqs#why-is-there-no-space-available-for-my-tokens-in-certain-pools)
url: https://docs.bancor.network/faqs#why-is-there-no-space-available-for-my-tokens-in-certain-pools

### calculating the required amount:
1. how many bnt equal 1 tkn = (bnt reserve balance) / (tkn reserve balance)
2. identify the amount of bnt needed to reach the top end of the limit = spaceAvailable - limit
3. include the amount from step 1 in order to indicate the amount to free up space for 1 tkn = step2+step1

### in details example:
ren pool token: 0x6b181C478b315bE3f9E99c57CE926436c32e17a7
poolAvailableSpace function response:
- ren :  0
- bnt :  1403404058171372713746323

networkTokenMintingLimits function response:
- 1000000000000000000000000 bnt

current balance:
- 1,711,365.486100309578494856 bnt
- 7,542,395.245134802630180142 ren

#### steps in calculation:
1. how many bnt equal 1 tkn = 1,711,365.486100309578494856/7,542,395.245134802630180142 = 0.22689947032 bnt
2. amount of bnt needed to reach top end of the limit = 1403404.058171372713746323 - 1000000 = 403404.058171 bnt
3. in order to free up space for 1 tkn, user should stake = 403404.058171 + 0.22689947032 = 403404.28507 bnt

**Comment by Velua** [comment]
We can't determine the available space with the method ```poolAvailableSpace``` on the protection contract? @ashachaf

**Comment by ashachaf** [comment]
poolAvailableSpace indicates how much tkn and bnt can be staked.
it does not indicate how much bnt you need to stake in order to have room for 1tkn.

**Comment by Velua** [comment]
@ashachaf There's a clarification we'd like to make on performing the calculation, @Ran73Cohen will be engaging you. 

@Ran73Cohen 
- [ ] Export all maths logic Asaf has got for us into a pure function
- [ ] Write two tests for this, one that Asaf has demonstrated for us and try out another. 

Once we're happy with the maths results we'll proceed with finishing this off. 

- [ ] Expand on the method available to the view layer currently called ```getMaxStakesView``` or whatever, to give back the further information you need. 
- [ ] Under the hood, have this new method call both the getMaxStakes and whatever other stuff you're calling.

**Comment by Ran73Cohen** [comment]
![image](https://user-images.githubusercontent.com/51334627/106010790-81a61800-60c2-11eb-99ee-3cc4663138eb.png)

This is the result I got from WBTC pool
@ashachaf Is this number legit?

**Comment by ashachaf** [comment]
after review, few things:
1. when switching between pools, the calculated amount needed does not change to fit the pool
2. when on TKN view, when you click on the "amount needed to open up space" value, expected to switch to BNT and input the amount
3. when on BNT view, when you click on the "amount needed to open up space" value, expected to input the amount needed and not the "space available" amount
4. update the text: 
- current: "amount needed to open up space"
- updated: "BNT needed to open up WBTC space" (where WBTC is dynamic based on the token in the pool)
5. calculation of BNT needs seems close but a bit over the needed number. need to check further.

**Comment by ashachaf** [comment]
in details example:
ocean pool token: 0xCDfF066eDf8a770E9b6A7aE12F7CFD3DbA0011B5
poolAvailableSpace function response:
ocean : 0
bnt : 1972789274644765492871418

networkTokenMintingLimits function response:
1000000000000000000000000 bnt

current balance: (need to normalize based on decimal)
2317340.673018588329242155 bnt
8128141.063498781316957537 ocean

steps in calculation:
how many bnt equal 1 tkn = 2317340.673018588329242155/8128141.063498781316957537 = 0.28510094189 bnt
amount of bnt needed to reach top end of the limit = 1972789.274644765492871418 - 10000000.00000000000000000 = 972789.274645 bnt
in order to free up space for 1 tkn, user should stake = 972789.274645 + 0.22689947032 = 972789.501544 bnt

**Comment by ashachaf** [comment]
### calculation update:
1. how many bnt equal 1 tkn = (bnt reserve balance) / (tkn reserve balance)
2. identify the amount of bnt needed to reach the top end of the limit = (spaceAvailable + step1) - limit
3. amount needed to add to free up space = step2
--

for WBTC:
0xfee7eeaa0c2f3f7c7e6301751a8de55ce4d059ec 

BNT amount: 6369563239385620312429826
TKN amount: 37612707824
Space available: 988628478251166751927599
limit: 1000000000000000000000000

steps in calculation:
how many bnt equal 1 tkn = 6369563.239385620312429826/376.12707824 = 16934.6043076 bnt
amount of bnt needed to reach top end of the limit = (988628.478251166751927599+16934.6043076) - 1000000.000000000000000000 = 5563.08255877 bnt
in order to free up space for 1 tkn, user should stake = 5563.08255877 bnt

--
in details example:
ocean pool token: 0xCDfF066eDf8a770E9b6A7aE12F7CFD3DbA0011B5
poolAvailableSpace function response:
ocean : 0
bnt : 1972789274644765492871418

networkTokenMintingLimits function response:
1000000000000000000000000 bnt

current balance: (need to normalize based on decimal)
2317340.673018588329242155 bnt
8128141.063498781316957537 ocean

steps in calculation:
how many bnt equal 1 tkn = 2317340.673018588329242155/8128141.063498781316957537 = 0.28510094189 bnt
amount of bnt needed to reach top end of the limit = (1972789.274644765492871418+ 0.28510094189)- 1000000 = 972789.559746 bnt
in order to free up space for 1 tkn, user should stake = 972789.559746 bnt

**Comment by ashachaf** [comment]
pool token: 0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533
on contract: 0xeead394A017b8428E2D5a976a054F303F78f3c0C
[ poolAvailableSpace method Response ]
    uint256 :  0
    uint256 :  7939095692002178796090485

pool contract:0xe24c8bbdba150aa3cb13c785d3a19d012ddc1e86
balances: 
  |uint256 :  17231379679880050707841059
  |uint256 :  28640948892010240170099

protection setting: 0xF7D28FaA1FE9Ea53279fE6e3Cde75175859bdF46
pool limit
8000000000000000000000000

steps in calculation:
how many bnt equal 1 tkn = 17231379.679880050707841059/28640.948892010240170099 = 601.634385259 bnt
amount of bnt needed to reach top end of the limit = (7939095.692002178796090485 + 601.634385259)- 8000000.000000000000000000 = -60302.6736126 bnt

**Comment by ashachaf** [comment]
## process/calculation update:
for TKN side, we need to pull the networkTokensMinted amount and use it in the calculation.

### which contract to check?
LiquidityProtectionSystemStore (0xc4C5634De585d43DaEC8fA2a6Fb6286cd9B87131)

### which function to call?
networkTokensMinted (pool token anchor)

### response:
amount of minted BNT in wei

## calculation:
### current:
1. how many bnt equal 1 tkn = (bnt reserve balance) / (tkn reserve balance)
2. identify the amount of bnt needed to reach the top end of the limit = (**spaceAvailable** + step1) - limit
3. amount needed to add to free up space = step2

### updated:
1. how many bnt equal 1 tkn = (bnt reserve balance) / (tkn reserve balance)
2. identify the amount of bnt needed to reach the top end of the limit = (**networkTokensMinted** + step1) - limit
3. amount needed to add to free up space = step2

## example:

pool token: 0xb1CD6e4153B2a390Cf00A6556b0fC1458C4A5533
on contract: 0xeead394A017b8428E2D5a976a054F303F78f3c0C
[ poolAvailableSpace method Response ]
uint256 : 0
uint256 : 7939095692002178796090485

pool contract:0xe24c8bbdba150aa3cb13c785d3a19d012ddc1e86
balances:
|uint256 : 17231379679880050707841059
|uint256 : 28640948892010240170099

protection setting: 0xF7D28FaA1FE9Ea53279fE6e3Cde75175859bdF46
pool limit
8000000000000000000000000

networkTokenMinded function on 0xc4C5634De585d43DaEC8fA2a6Fb6286cd9B87131
[ networkTokensMinted method Response ]
    uint256 :  8019890870870961053410978

steps in calculation:
how many bnt equal 1 tkn = 17231379.679880050707841059/28640.948892010240170099 = 601.634385259 bnt
amount of bnt needed to reach top end of the limit = (8019890.870870961053410978 + 601.634385259)- 8000000.000000000000000000 = **20492.5052562 bnt**
