### ISSUE TITLE
Improvement design of navigation

### ISSUE THREAD

**Issue by sirius651** [bancorprotocol/webapp#780]
**Is your feature request related to a problem? Please describe.**
As discussed with @ashachaf, It is necessary to improve the current navigation design.

- Side navigation takes up a lot of space on the desktop.
- The current bottom sticky bar on the mobile looks good, but if more menus, it needs have options to choose from.

**Describe the solution you'd like**

- A toggle button to shrink or expand space on sidebar. When shrink, only visible menu icons without title of menu.
- Insert the arrow button in the current position of the vote button, and click this button to open a pop-up and view another menu.

**Describe alternatives you've considered**

**Additional context**
Related #730

**Comment by ashachaf** [comment]
side menu is taking up too much space from the tables we want user to view.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1679%3A20
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1682%3A25
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1682%3A134

https://streamable.com/22sf5o
https://streamable.com/heri7y

**Comment by sirius651** [comment]
![스크린샷 2021-01-04 오후 2 11 16](https://user-images.githubusercontent.com/1606820/103512993-15623b00-4ead-11eb-8d6b-237b595d1cae.png)

![스크린샷 2021-01-04 오후 4 09 47](https://user-images.githubusercontent.com/1606820/103513100-4478ac80-4ead-11eb-8a57-de790b42d8ca.png)
![스크린샷 2021-01-04 오후 4 09 53](https://user-images.githubusercontent.com/1606820/103513139-55c1b900-4ead-11eb-980c-f4e09a9bb053.png)

This is current ongoing screenshot what I'm working on. any comment for this? @ashachaf 
https://streamable.com/22sf5o also good idea. but, currently displaying small popup would be more simple way.

**Comment by ashachaf** [comment]
IF the side menu on desktop opens up on mouse over, there is no real need for the arrow at the top.
as for mobile menu, if https://streamable.com/22sf5o takes too much work to implement, keep your solution. however, if the delta is small, consider implementing it this way.

**Comment by sirius651** [comment]
https://user-images.githubusercontent.com/1606820/103610262-0938b500-4f63-11eb-9f29-582bca96a2e4.mp4

It's a recorded video reflecting your suggestion. pls give me thoughts for this @ashachaf 
And, I'm also thinking of https://streamable.com/22sf5o . maybe creating new task.

**Comment by ashachaf** [comment]
few comments:
desktop:
- are we able to implement the side menu expand on mouse over? this means it will open up on mouse over and close once mouse is away.
- this is a video how how it should behave on desktop https://streamable.com/heri7y

mobile:
- we can keep the current solution
- will open a new task to update it to behave like this https://streamable.com/22sf5o

**Comment by sirius651** [comment]
> few comments:
> desktop:
> 
> * are we able to implement the side menu expand on mouse over? this means it will open up on mouse over and close once mouse is away. current implementation allows me to expand but not to close the menu, which is not ideal.
> * this is a video how how it should behave on desktop https://streamable.com/heri7y
> 
> mobile:
> 
> * we can keep the current solution
> * will open a new task to update it to behave like this https://streamable.com/22sf5o

I'm currently implementing this with transition. also created new task #793

**Comment by sirius651** [comment]
https://user-images.githubusercontent.com/1606820/103860993-08895580-5100-11eb-9011-f6c41eb618b0.mp4

I improved it based on your suggestion @ashachaf . give me feedback please.

**Comment by Velua** [comment]
This is now in staging @ashachaf

**Comment by Velua** [comment]
Is the Bancor logo meant to go away when minimised? As without it the links move and make it a bit tedious.

**Comment by Velua** [comment]
https://user-images.githubusercontent.com/8017434/104115698-a7f75400-535d-11eb-925c-fd685b900c30.mov

I'm finding when I mouse over one menu, the links will shift and then suddenly my mouse is hovering over another menu instead.

**Comment by Velua** [comment]
@sirius651 let's tackle this tomorrow.

**Comment by ashachaf** [comment]
1. bancor logo should always be visible. top section should not fold with the menu
![image](https://user-images.githubusercontent.com/40430285/104117485-4f5a9380-532a-11eb-83f2-e88856dee932.png)
2. closed view, icon should be centered in the selected area (how it is on open mode)
current: ![image](https://user-images.githubusercontent.com/40430285/104117501-7022e900-532a-11eb-8ce3-e75b4daf9f1d.png)
expected: 
![image](https://user-images.githubusercontent.com/40430285/104117511-8761d680-532a-11eb-8a5b-fcbadf1791b3.png)
3. open / close movement is not smooth. it has jumps and is too slow. we should try and make it move seamlessly.  (reference: https://streamable.com/heri7y)
4. icons position should stay the same "height". they should not jump up and down when open / close. https://streamable.com/rjtpkb

mobile:
1. right side should have some blur to it in order to indicate scroll effect
current: 
![image](https://user-images.githubusercontent.com/40430285/104117654-a3b24300-532b-11eb-8dc2-57137b6fc1d2.png)
expected: 
![image](https://user-images.githubusercontent.com/40430285/104117644-8c735580-532b-11eb-9ef5-a30c56bc941b.png)

**Comment by sirius651** [comment]
![스크린샷 2021-01-11 오후 5 13 28](https://user-images.githubusercontent.com/1606820/104158336-74d1c500-5430-11eb-9ffa-f5c806fce66f.png)

![스크린샷 2021-01-11 오후 5 11 39](https://user-images.githubusercontent.com/1606820/104158342-7a2f0f80-5430-11eb-8546-1a7c6208bc99.png)

regarding mobile view, why don't we use arrow indicator rather than blur things? @ashachaf

**Comment by Velua** [comment]
@sirius651 Had a chat with @ashachaf  we reckon the blurryness would still be the way to go, lets see it in action and see what it looks like.

**Comment by sirius651** [comment]
> @sirius651 Had a chat with @ashachaf we reckon the blurryness would still be the way to go, lets see it in action and see what it looks like.

Okey, because when I tried blur first, it's not clearly distinguished. will look more into it again.

**Comment by Velua** [comment]
How is this going?

**Comment by sirius651** [comment]
> How is this going?

This https://github.com/bancorprotocol/webapp/pull/799 is for this issue
