### ISSUE TITLE
adding rewards indication to aave pool

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#784]
we would like to activate the rewards on the **aave** pool as the vote indicated.

counter destination date:
Thursday, March 25, 2021 9:00 am GMT

pool address:
0x5bEdB6E03fA9aA4A5a35152dab8336bC57376b90

pool token address:
0x6c84F4ccC916ACf792538f1293b286b540906A2a

this is a mid size rewards pool. as such, the rewards are between 10,000-20,000 bnt per week.
calculating rewards (reminder as this code exists):
IF SMALL CAP:
IF BNT: (14000000000000000000000*52/total protected BNT in the pool)100
IF TKN: (6000000000000000000000((total TKN reserve)/(total BNT reserve))*52/total protoected TKN in the pool)*100

**Comment by pingustar** [comment]
Title says AAVE and comment says SNX. To clarify. I have added SNX a couple of days ago. This must be AAVE then.

Blocked due to missing timestamp for reward endtime.

@ashachaf please comment once available.

**Comment by ashachaf** [comment]
i duplicated the task.
this one is for aave.
no date because it hasnt reached the limit yet.

**Comment by pingustar** [comment]
added.
