### ISSUE TITLE
UI - Data - pools/tokens

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#79]
Hi, I just reviewed data - exciting, looks great! But still there are a few deltas between design and live app. Here is a list:

1. Title "Statistics" text style isn’t correct
2. Please add a separation line below the title
3. Body text color doesn't fit the design - main body text color is 0A2540
4. Is is possible to change card's shadows exactly as it is in Zeplin? As this page is full of information, shadows look slightly distractive, so the if you can make shadow more gentle would be great.
5. Please change arrow icons in the header of the table
6. Please add icon to a search box
7. Please change the color of "search" to D0D7DF
8. Please add shadow to token images - tokens with white backgrounds are problematic
9. Separation lines inside the table (and grey header box) should reach the edges
10. Please change the style of V1/V2 tags - relevant to all pages
11. Is it possible to fix alignment in the table? Titles and numbers should be aligned left. 

Thanks a lot

<img width="1746" alt="Screenshot at Aug 12 08-38-39" src="https://user-images.githubusercontent.com/69288176/89979735-22ba2700-dc79-11ea-9d87-30b3e62822f1.png">

**Comment by Velua** [comment]
Thanks for the feedback @katyarozenfeld  this ones still a work in progress, going forward keep an eye out for any issues already created that's related, in this case I think the conversation can be continued at #65, this will help keep relevant information contained in the one place.
