### ISSUE TITLE
Timer on my stake is off

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#798]
I just deposited link and for some reason my timer shows 18d until vesting, when it should say 30d

![image](https://user-images.githubusercontent.com/53524917/104134271-3933ee00-5391-11eb-9838-ab5a92c8ca76.png)

**Comment by ashachaf** [comment]
expand the group to see all positions.
we mark the "oldest" position vesting in the grouped view.

**Comment by Velua** [comment]
Considering this by design and not a bug, let me know if otherwise.
