### ISSUE TITLE
maintenance - disable stake/unstake from protection

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#800]
we would like to plan for a maintenance that would disable the option to stake/unstake from protection.

we need to upgrade thee contracts which might result in some down time.
during this down time, we should do the following:
1. disable the option to stake into pools
- data tab - pools that are white listed and clicking the + opens stake for protection (single side staking)
- protection page - stake to protection
2. disable the option to unstake from protected position
- protection page - option to withdraw a protected position
3. indicate this is a schedule maintenance

mockup:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1824%3A20
mockup only shows protection tab but we should use the same "disable" look for the different call to actions on the data page as well.

**Comment by Velua** [comment]
When should maintenance mode be activated? Based on a time schedule or do we want to make specific app deployments to turn off and on? Or have it based on an external resource?

**Comment by Velua** [comment]
## To Do
Create a hardcoded  boolean getter ```stakeMaintenanceMode``` in Vuex.
Have the app reflect the changes as per Figma when ```stakeMaintenanceMode``` is ```true``` and normal when it is ```false```

**Comment by Ran73Cohen** [comment]
I will take on this assignment

**Comment by Velua** [comment]
How is this going @Ran73Cohen  ?
