### ISSUE TITLE
Some coins cause an error when trying to swap

### ISSUE THREAD

**Issue by Ran73Cohen** [bancorprotocol/webapp#814]
Go to swap tab
Select USDC (from)
Select OCEAN (to)

Error - execution reverted
![image](https://user-images.githubusercontent.com/51334627/104584482-586d9c80-566b-11eb-8c09-bf897394e6c9.png)

When switching this error will pop (and catched) every time because it is trying to recalcualte the rate in SwapAction.vue:334
With ETH and BNT this issue doesn't happen

**Comment by Velua** [comment]
and this happened on prod and not staging?

**Comment by Ran73Cohen** [comment]
> 
> 
> and this happened on prod and not staging?

Happened on staging

**Comment by Velua** [comment]
Determine what function exactly is getting thrown to create this error and review parameters sent, can discuss your findings tomorrow @Ran73Cohen

**Comment by Ran73Cohen** [comment]
Doesn't happen anymore the exception was because of an API error.

File
SwapAction.vue 

Method:
calculateRate

API Call:
vxm.bancor.getReturn

Leads to:
@action async getReturn(proposedTransaction: ProposedFromTransaction) {
    return this.dispatcher(["getReturn", proposedTransaction]);
}

Closing
