### ISSUE TITLE
Missing REN logo

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#82]
![image](https://user-images.githubusercontent.com/53524917/90064876-11fac700-dcf4-11ea-8860-617736494ba6.png)

**Comment by Velua** [comment]
Looks like it's there for me now, re-open if you have any issues.

**Comment by ashachaf** [comment]
please use this logo
![Token Image](https://user-images.githubusercontent.com/40430285/90114237-1f976780-dd5b-11ea-8034-3d70cdae6e61.png)

**Comment by Velua** [comment]
Logo now in use.
