### ISSUE TITLE
Ignore V2 Pools with no pool tokens 

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#84]
App freaks out when it cannot find pool tokens for a pool, v2 pools without any pool tokens set are currently useless to the app, ignore.

**Comment by Velua** [comment]
@ashachaf I believe it's actually this bug that's causing your ropsten pains, try it out on ropsten now via staging.

**Comment by ashachaf** [comment]
checked and i can now see v2 pools on ropsten.
still need to check this for cases of empty bancor v2 pools.

**Comment by Velua** [comment]
Yeah handling that in #73
