### ISSUE TITLE
exit fee change based on amount

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#85]
when i change the amounts i would like to remove, the exit fee changes.
this should not be the case as the percentage is not related to the amount i liquidate.

bonus bug: the "output" amount when selecting 25% is showing as 5e-7 instead of the actual number (0.00000050) in a readable format.

https://streamable.com/fyly6d

**Comment by Velua** [comment]
Solved the 'bonus bug' 

Are we sure about the exit fee? I can only make it change on very small amounts, exit fee is calculated from on-chain data. @ashachaf

**Comment by ashachaf** [comment]
might be related to very small numbers where you lose accuracy for lack of decimals which results in different exit fee.
can only reproduce when i try to remove liquidity for very small numbers.
