### ISSUE TITLE
Flakey download bad gateway error on Web3

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#852]

**Comment by pingustar** [comment]
![image](https://user-images.githubusercontent.com/7262066/105683704-3807d280-5ef4-11eb-9310-fc15318106a4.png)

Network: **Ropsten** ( could not test on mainnet as contracts are not deployed yet. )

Not sure if it is related or not but I was doing lots of TX on Ropsten, and every now and then the above error was thrown and the protected table didnt render, as well as the protected shield on data table
