### ISSUE TITLE
claim rewards - update restake to stake

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#858]
we would like to change the word "restake" to "stake"
protection table:
![image](https://user-images.githubusercontent.com/40430285/105965630-54d70e00-608c-11eb-81e9-c0d09a446fe5.png)

restake popup:
![image](https://user-images.githubusercontent.com/40430285/105965674-63252a00-608c-11eb-9f4e-0f72b83d8140.png)

withdraw popup:
- warning text
**current:** Withdrawing rewards will reset your rewards multiplier for all active positions back to x1 and reduce the future rewards you are able to receive. In order to claim and re-stake your rewards atomically without resetting your current multipliers, click the “Restake my rewards” button below.
**updated:** Withdrawing rewards will reset your rewards multiplier for all active positions back to x1 and reduce the future rewards you are able to receive. In order to claim and stake your rewards atomically without resetting your current multipliers, click the “Stake my rewards” button below.
- button
![image](https://user-images.githubusercontent.com/40430285/105965741-77692700-608c-11eb-8e61-bc375e6cac18.png)

**Comment by ashachaf** [comment]
@pingustar

**Comment by pingustar** [comment]
done
