### ISSUE TITLE
protection table - how to claim rewards when there are no active positions

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#861]
**Describe the bug**
if a user opened protected positions, remove them and receive rewards, there is no option for him/her to claim the rewards as we only load the page when protected positions >0.

**To Reproduce**
1. create a protected positions on a pool with rewards
2. wait few min to receive rewards
3. withdraw the entire position
4. claim BNT (if needed)
5. try to claim/stake your rewards

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2196%3A71
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2163%3A20

**Comment by pingustar** [comment]
@ashachaf sounds good. One question though:

this seems outdated. Should we keep it, remove it or change it?

![image](https://user-images.githubusercontent.com/7262066/106012949-40126e80-60bc-11eb-97c9-0863dbfe549b.png)
