### ISSUE TITLE
loading time and performance issues

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#862]
initial load is much faster now, but some data takes up to 45+ seconds to load.
@Velua

https://streamable.com/t5ekug

**Comment by Velua** [comment]
I've been able to speed this up in my dev environment, will require a bit more work till it's fit for prod.

**Comment by Velua** [comment]
We're now caching several contracts including things like liquidity settings, these are then acted upon optimistically. 
As part of this update I'm also adding more loading stages of the protection positions, we know the positions initial stake long before anything is actually rendered to the screen so I'm changing it to display all the different pieces of data as it comes in. 

This will be a nicer experience for the end user and give them greater assurance of their positions. @ashachaf
