### ISSUE TITLE
protection table - fee column shows 0

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#864]
**Describe the bug**
on the protection table, many positions are reported to show fees value as 0.

related to task #531 

position 1298.
function removeLiquidityReturn(1298, 1000000, 1893456000)
returns:
- uint256 :  10107821463534933095
- uint256 :  10107821463534933084
- uint256 :  0

function protectedLiquidity(1298)
returns:
- address :  0x5f7a009664B771E889751f4FD721aDc439033ECD
- address :  0xCDfF066eDf8a770E9b6A7aE12F7CFD3DbA0011B5
- address :  0x967da4048cD07aB37855c090aAF366e4ce1b9F48
- uint256 :  684335152079891793
- uint256 :  10000000000000000000
- uint256 :  2393723735936477059923424
- uint256 :  3177049956968218926567437
- uint256 :  1605539988

calculation should be:
10107821463534933095 - 10000000000000000000 = 107821463534933095

normalize this value based on the token decimals (in this case token is 0x967da4048cD07aB37855c090aAF366e4ce1b9F48 with 18 decimals): 
107821463534933095/10^18= 0.10782146353 OCEAN in fees

in the console, i see that we've calculated the fees to be a negative number
![image](https://user-images.githubusercontent.com/40430285/106022731-d485cc80-60ce-11eb-9228-e0272227eff4.png)

**Comment by ashachaf** [comment]
@pingustar @Ran73Cohen

**Comment by pingustar** [comment]
fixed.
