### ISSUE TITLE
protection table - stats section update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#876]
currently, we show ROI in the stats section.
this number is not accurate enough and we would like to replace it with total fees.

**current:**
![image](https://user-images.githubusercontent.com/40430285/106121723-8d481c00-6160-11eb-816d-82a89e98723a.png)

**updated:**
![image](https://user-images.githubusercontent.com/40430285/106122340-46a6f180-6161-11eb-9c72-382e9c87aba4.png)

**calculation:**
total fully protected value - total initial position value = total fees value

**Comment by pingustar** [comment]
@ashachaf if ROI isn't accurate in the summary view, then it isn't accurate in the table as well?!

**Comment by pingustar** [comment]
after feedback from @ashachaf 

just fees without rewards. ROI data is accurate but the stake summary should show USD value of all fees accumulated.

**Comment by Ran73Cohen** [comment]
Fixed [here](https://github.com/bancorprotocol/webapp/commit/700dfe405bfed245ed7cc65284782c3ed150cadf)
