### ISSUE TITLE
Dropdown menu - switch the order of the community/developers section and rename community section

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#886]
Many users get into the dev group chat and ask for support since it's the first link.

The community section should be first and should be renamed to "Community & Support".
And only then the developers section.

**Comment by Ran73Cohen** [comment]
Fixed [here](https://github.com/bancorprotocol/webapp/commit/ca26b0266302672e6f52c903278f7f9e538c54b0)
