### ISSUE TITLE
Crash in the protection page

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#887]
User reported: protection page doesn't load positions, all numbers are 0 or n/a and the page only shows loading animation.
The user has a single ETH option position.

![image](https://user-images.githubusercontent.com/1134236/106355126-ff9a3700-62ed-11eb-85f1-363a2e6a147b.png)

**Comment by Velua** [comment]
Can we get the users info? Unable to replicate on my end

**Comment by AVShatokhin** [comment]
i am here

**Comment by Ran73Cohen** [comment]
Old, loading was changed
