### ISSUE TITLE
withdraw rewards confirmation popup text update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#889]
**Describe the bug**
when you try to withdraw your rewards, the transaction confirmation popup is using the text "You are staking and protecting:"
![image](https://user-images.githubusercontent.com/40430285/106364773-38f89400-633a-11eb-92af-efb34fc2e678.png)

**To Reproduce**
1. go to protection tab
2. click "withdraw" rewards
3. proceed with "withdraw"
4. see a confirmation popup 

current text: You are staking and protecting:
updated text: You are withdrawing rewards:

**Comment by Ran73Cohen** [comment]
Fixed [here](https://github.com/bancorprotocol/webapp/commit/e21ad2c5158227614bf46ee61bb71928ad13f8cb)
