### ISSUE TITLE
withdraw protected position - include multiplier reset warning

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#890]
**Describe the bug**
when a user is trying to withdraw an existing protected position, we should indicate that this would reset the rewards multiplier.

mockup:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1443%3A1158

warning text:
"Withdrawing will reset your rewards multiplier for all active positions back to x1"

reproduce:
1. go to protection tab
2. click to withdraw an existing protected position

process update:
IF user has any rewards with multiplier, include the warning.

**Comment by Velua** [comment]
How do we recognise a multiplier? The positions pool token having a pool program?

**Comment by ashachaf** [comment]
we have this function in the contract that allows you to check user's multiplier:

    ```
function rewardsMultiplier(address provider, IDSToken poolToken, IERC20Token reserveToken) external view returns (uint32) {
        ProviderRewards memory providerRewards = providerRewards(provider, poolToken, reserveToken);
        PoolProgram memory program = poolProgram(poolToken);
        return rewardsMultiplier(provider, providerRewards.effectiveStakingTime, program);
    }
```

suggested process:
1. identify all positions for the wallet
2. for the list of positions
- check position for multiplier
- if multiplier > 1, stop the check process and display the warning
- repeat until you check all positions
- if all positions = 1, do not display the warning.

**Comment by ashachaf** [comment]
why did you include the warning in a new box?

**Comment by Ran73Cohen** [comment]
> 
> 
> why did you include the warning in a new box?

I saw this pattern somewhere else and this is how our alert component works
I can make it in a different row
Do you want me to add the Icon next to each warning as well? (in every alert or just this one?)

**Comment by ashachaf** [comment]
same box.
include icon to each point.
