### ISSUE TITLE
Protection page refreshes infinitely

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#892]
Occasionally, the protection page refreshes the data automatically every 10 seconds or so.
So it loads fine initially, then after 10 secs all data disappears and the loading animation shows up and this behavior repeats infinitely.
Refresh usually fixes it.

**Comment by pingustar** [comment]
@Velua this seems to happen after `stake for protection` - does this trigger a position refresh on `onConfirmed` or something?
