### ISSUE TITLE
During Remove liquidity process: “your liquidity” acts up

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#9]
While remove liquidity is in process the balances are wrong

<img width="432" alt="image" src="https://user-images.githubusercontent.com/7262066/89396492-e766a800-d70e-11ea-83d5-f60af51f1732.png">

**Comment by Velua** [comment]
Just tried replicating this one and failed, might already be sweet, @pingustar can you replicate this on your end?

**Comment by pingustar** [comment]
@Velua nope can not reproduce. But I noticed that there is only 1 balance anymore. I know I removed shortly after launch the Token symbol because it caused some issues on mainnet. But shouldnt there be 2 balances for v1 pools?

**Comment by ashachaf** [comment]
on swap.bancor.network
click pool
select any v2 pool that you have liquidity in
click remove liquidity
enter amount and trigger the metamask transaction popup (dont sign it)
navigate back to "pool" and click the same pool.
view your balance.

https://streamable.com/0avu01

**Comment by Velua** [comment]
@ashachaf found a bug in the code that would explain this behaviour, haven't been able to reproduce on ropsten.
