### ISSUE TITLE
when selecting entire eth balance, deduct expected tx cost from the input amount

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#90]
swap.bancor.network
from token selection - ETH
click the eth balance
(this is only true for eth)
expected - input field will be populated with the (entire balance - expected tx gas cost)

**Comment by Velua** [comment]
What do you want to base gas price off?

**Comment by Velua** [comment]
I'm not sure how to deliver this given it will break should the user mutate the gas price unless we over estimate what the user would go for gas price wise and leave the remaining as dust. 

Otherwise we update the UI to prompt for the gasPrice and gasAmount for the TX and then pass that data into the wallet, so it's already inline with what the user wants. @ashachaf

**Comment by ashachaf** [comment]
can you estimate the transaction cost and deduct this amount from the eth balance when the user clicks "max" (or his balance)?

possible process:
go to swap.bancor.network
click to enter your full balance (only when. you click the "max" or balance,  this process works)
calculate transaction gas estimation
deduct this amount from the balance
input the calculated value into the input field.

**Comment by Velua** [comment]
With this we'd have to guess what the user wants to set as ```gas price``` and any extra ```gas``` unused would be left in their account by doing. Could get a bit messy. 

Unless we bring up a special modal which offers a decent gas price, decent gas estimate and let the user approve of this before triggering the wallet transaction?

**Comment by yudilevi** [comment]
How is this handled by other platforms in the space?

**Comment by Velua** [comment]
Looks like Uniswap doesn't let the user spend their last .01 ETH

**Comment by ashachaf** [comment]
we can have the same setup than.
when clicking on the ETH balance in the swap window, deduct 0.01eth from the amount you input the field.

**Comment by Velua** [comment]
Fixed in https://github.com/bancorprotocol/webapp/commit/5cfae1aaad16d1a71af9dea66f4193f4e857e9f4
