### ISSUE TITLE
v2 pool tokens - make visible

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#903]
pool tokens for these two pools should be visible and allow users to interact with them.

pool anchors:
1. linkbnt anchor: 0xA6CC5967be74A2b959D18469eBfb54ED317bC4B3
2. renbnt anchor: 0xD5aA38C6Df168741839F9E1e9c51e6d24b986970

where should this be visible?
1. go to swap
2. pool
3. your liquidity
![image](https://user-images.githubusercontent.com/40430285/106491574-ac77de00-64bf-11eb-9a62-1216f1ce2905.png)

actions a user can do on these pools?
1. remove liquidity

**Comment by Velua** [comment]
Pools no longer in registry and won't be supported.
