### ISSUE TITLE
UI - Data - Tokens/Pools Table 

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#91]
Hi, here are a few comments for data pool/token table:

- [ ] Tabs - "token"/"pool" text color - please fix

- [ ] Search - "search" text color - please fix (should be lighter). Also relevant to typing mode - need to be 0A2540.

- [ ] Tabs - blue line looks broken - "trapeze" shape

- [ ] Please align tabs with table content. No need to make blue line wider than tab name.

- [ ] Can we fix the width of the buttons? Just as it is in Zeplin? 132 px & 132 px

- [ ] Pagination - Please replace icons to what we have in Zeplin

- [ ] Pagination - Please change text color

Mobile

- [ ] Please move "search" box to top right (screenshot attached)

- [ ] Please fix spacing in statistics card (screenshot attached)

Dark mode

I'm sorry, it feels too late - but I've prepared design only for one page in dark mode to be as a guide for you, but now I feel it wasn't enough. Therefore, I've added dark mode version of pool page here, and there are a few points that need to be changed: https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f3668ef86e30c68d2f09039/
Please let me know if you need a detailed guide for the dark mode in addition to what we have in Zeplin or do you prefer to receive the list of changes per each page?

Thanks!

![photo_2020-08-14 13 23 08](https://user-images.githubusercontent.com/69288176/90340407-a882fd00-e000-11ea-81d0-433e074bf9d6.jpeg)
![photo_2020-08-14 13 23 03](https://user-images.githubusercontent.com/69288176/90340408-aae55700-e000-11ea-881a-af5dbc63d46a.jpeg)
<img width="1519" alt="Screenshot at Aug 14 13-18-02" src="https://user-images.githubusercontent.com/69288176/90340421-c05a8100-e000-11ea-90fd-40d9b5cd4428.png">

**Comment by Velua** [comment]
Thanks @katyarozenfeld sent you a message in #65 !
