### ISSUE TITLE
Price volatility is visible even though the average rate equals the actual rate

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#912]
The issue is visible in the YFI pool.

Here's the average rate from etherscan -

![image](https://user-images.githubusercontent.com/1134236/106745728-7189bd80-6619-11eb-9be0-5cafd198aba5.png)

And the balances:
![image](https://user-images.githubusercontent.com/1134236/106745769-7e0e1600-6619-11eb-84fd-59f6202d7a8e.png)
![image](https://user-images.githubusercontent.com/1134236/106745785-823a3380-6619-11eb-8735-cbc08dd8288a.png)

As you can see, the rates are identical.

And still this is what users see (I can also reproduce) on the app when trying to remove liquidity from the YFI pool -
![image](https://user-images.githubusercontent.com/1134236/106745842-9716c700-6619-11eb-8fd2-9c33b189b3ab.png)

We both tried on desktop/chrome.

**Comment by pingustar** [comment]
related to #914

issue isolated to faulty api data

actions taken: disabled price deviation warning until api functional again.
