### ISSUE TITLE
stake liquidity deviation error when logged out

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#914]
**Describe the bug**
when you are logged out and try to stake liquidity into a pool, it will give you an error indicating "price deviation is too high".
while the expected behavior should be to indicate the user should connect his wallet.

![image](https://user-images.githubusercontent.com/40430285/106746912-dbab5e00-662b-11eb-91dd-ec48e1915aec.png)

**Comment by pingustar** [comment]
issue caused by faulty data returned by api
