### ISSUE TITLE
Catch error for checkPriceDeviationTooHigh function

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#919]
- [x] add sanity check to `checkPriceDeviationTooHigh` function that throws error when calculation fails
- [x] display error message to user when error thrown

@ashachaf what should the error message text be like?

**Comment by ashachaf** [comment]
- [ ] error message: "Price deviation calculation error. Please contact support."

- [ ] we should also have some indication of the issue so we can address it before users complain

**Comment by pingustar** [comment]
error handling is updated and linked PR is ready for review @ashachaf 

About the indication to us, I am throwing an error, so Sentry will pick it up. But currently we are not really utilizing sentry to this extent. Probably worth its own task to improve our sentry error handling.
