### ISSUE TITLE
Font used in mockups

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#96]

**Comment by Velua** [comment]
Hi @katyarozenfeld 

If we are not going to use the font used in the mockups is it worth updating the mockups so it's reflective of our work? I believe there's a difference between font weights used.

**Comment by katyarozenfeld** [comment]
Yes, I agree, I will update fonts in Zeplin. But font weights should be the same - regular → regular, medium → medium

**Comment by pingustar** [comment]
@katyarozenfeld can you have a look into the sizing and font weights. I think the other font we are using is slightly different in terms of size and weight. Eg. size 12px on Helvetica seems a bit bigger than size 12px on Inter. If you dont think so then I have to check my code again to see where that discrepancy is coming from. Thanks!

**Comment by katyarozenfeld** [comment]
@pingustar Ok, so Regular - 400, medium - 500. 

I've started updating fonts in my design file, but haven't finished yet. Helvetica and Inter are slightly different, but i didn't notice any problems it causes and everything looks fine (live app as well). Will try to update all screens in Zeplin today. Thanks!

**Comment by pingustar** [comment]
ok thanks @katyarozenfeld
