### ISSUE TITLE
withdraw popup update

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#963]
**Is your feature request related to a problem? Please describe.**
on the withdraw popup, we would like to remove the initial value and only show the claimable amount for the user.

current bug:
we display claimable value under the "fully protected value"/

design update:
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2228%3A0

**Describe the solution you'd like**
following updates:
1. remove the "initial stake" amount and only keep the "claimable" amount
2. make sure we use the "claimable value" and not initial/fully protected value for the position

**Comment by ashachaf** [comment]
@Velua please see if we can fix bug part first thing

**Comment by Velua** [comment]
> current bug:
we display claimable value under the "fully protected value"/

Are we sure? They look correct on my end. Can you send a screen shot? 

The Figma link doesn't appear to work, just goes to a withdraw page instead. 
I've removed the column and brought the pool logos over, available to check out in the linked PR.

**Comment by ashachaf** [comment]
this is the data from the protection table.
![image](https://user-images.githubusercontent.com/40430285/107191169-745b2880-69f4-11eb-9ec2-a2aea07e33ec.png)

this is where the error is, on the withdraw popup. you can see that the text says "fully protected value" but shows the claimable one instead.
![image](https://user-images.githubusercontent.com/40430285/107191201-7f15bd80-69f4-11eb-975a-5349cc2d57cd.png)

this is the updated mockup.  display only claimable value on the top part.
![image](https://user-images.githubusercontent.com/40430285/107191385-c00dd200-69f4-11eb-9a3a-7338c96e9488.png)

**Comment by Velua** [comment]
Ohhh my bad, completely misunderstood. We'll keep initial stake on the protected table then?

**Comment by ashachaf** [comment]
yes, only updating the information on the withdraw popup

**Comment by ashachaf** [comment]
seems you have removed the "initial value" from the protection table.
this is not the task. protection table should stay as is.

**Comment by Velua** [comment]
New branch is up for this one, though investigating an discrepancy between the table amount version and the withdraw page one.

**Comment by ashachaf** [comment]
flow seems fine.
i was able to see the issue you have mentioned with diff values on the protection table and withdraw popup.

**Comment by ashachaf** [comment]
@Velua the diff is the rewards on the position.
values are fine.

**Comment by ashachaf** [comment]
on the withdraw popup, please add an info icon with this:
tool tip text: Claimable value does not include earned liquidity mining rewards. You can withdraw or re-stake rewards from the Protection screen, by clicking “Withdraw” in the rewards widget.

![image](https://user-images.githubusercontent.com/40430285/107872981-4de73280-6eb7-11eb-8cab-fb3b748e26f5.png)
