### ISSUE TITLE
stake single vs dual side

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#973]
**Describe the bug**
when trying to stake into uni pool, it opens single side staking.
however, due to liquidity changes, it is no longer valid for single side and can only support dual side at this stage.

**To Reproduce**
1. go to data
2. search uni
3. click "stake"

**Expected behavior**
when bnt balance in the pool is below the defined restriction in the contract, we should open dual side staking.

**Comment by pingustar** [comment]
@Velua can you take this on? Commit history suggests that you might have an idea what went wrong with changing this behaviour in PR #801

**Comment by Velua** [comment]
Yeah good catch @pingustar thanks 

@ashachaf I've engaged you on Telegram in regards to this one.
