### ISSUE TITLE
App doesn't load pool data

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#974]
**Describe the bug**
Multiple users report that the app won't load any pools. Spinning loading icon and empty data table is the result.

**To Reproduce**
I am not able to reproduce myself, but screenshots show the behaviour and errors logged to console:
![telegram-cloud-photo-size-5-6124931803333634846-y](https://user-images.githubusercontent.com/7262066/107194610-8cc94400-69f0-11eb-9e7a-8878d4c4b57b.jpg)

![telegram-cloud-photo-size-5-6127258279743695820-y](https://user-images.githubusercontent.com/7262066/107194579-85099f80-69f0-11eb-8a1d-eb2ccc46f92f.jpg)

**Additional context**
User is using Brave Browser

**Comment by pingustar** [comment]
api seems to throw the following error: 

![telegram-cloud-document-1-4974237015475224880](https://user-images.githubusercontent.com/7262066/107194929-f5b0bc00-69f0-11eb-9831-dfb298be0481.jpg)

**Comment by Velua** [comment]
@pingustar Shall we look into some kinda toast notification system? Should have a popup when shit goes wrong.

**Comment by Velua** [comment]
I saw in your recent PR I just merged it looks like we're further logging an error when this API request fails too. 
See if we're picking this up in Sentry and can report the evidence to Yariv.

**Comment by pingustar** [comment]
@Velua I like the idea of a toast notification system. Maybe we can come up with a system that monitors pending transactions and errors as well.
