### ISSUE TITLE
Token decimals aren't handled correctly in add/remove liquidity

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#99]
See the POWR / BNT pool (POWR has 6 decimals) -
https://swap.bancor.network/eth/pool/add/0x168D7Bbf38E17941173a352f1352DF91a7771dF3

![image](https://user-images.githubusercontent.com/1134236/90414122-0c1c3180-e0b8-11ea-88a7-0b11c6322541.png)

**Comment by Velua** [comment]
Are you saying it should be ```0.000001``` in ```POWR per BNT```? If BNT has 18 decimals should we be displaying it to that extent too?

**Comment by yudilevi** [comment]
These are the current converter balances -

![image](https://user-images.githubusercontent.com/1134236/90484073-5e079a80-e13e-11ea-820c-5095bf08b8a1.png)

So I think it should be around 1 BNT : 20 POWR.

**Comment by Velua** [comment]
Recognised a fault,
